### ISSUE TITLE
Composer update installs drupal every time

### ISSUE THREAD

**Issue by dutchiexl** [drupal-composer/drupal-composer-project#1]
When I run composer require, or composer update, drupal is installed every time.

**Comment by kasperg** [comment]
Yep. This is an issue with `azt3k/non-destructive-archive-installer`. It is not very clear in that regard.

The best bet here is either to find a better solution to installing core or to fix it there.

**Comment by derhasi** [comment]
This should be fixed, once https://github.com/drupal-composer/drupal-composer-project/pull/5 is merged.

**Comment by derhasi** [comment]
Merged it right now.
