### ISSUE TITLE
Example of using git revision of module

### ISSUE THREAD

**Issue by mikkeschiren** [drupal-composer/drupal-composer-project#100]
I have been pulling my hair to use a git revision to use in composer.json, but I can not seem to get it to work, this is what I am using right now:

```
"require": {
        "drupal/devel": "dev-8.x-1.x#d913e1d"
}
```

What happens is that latest commit from HEAD is used. Is there a way around this? The "simple" way around it is to fork and tag the commit, but I would like to avoid that.

**Comment by webflo** [comment]
Sorry, i have no idea why this should not work.

**Comment by mikkeschiren** [comment]
Seems that the bug is related to wikipedia composer-merge-plugin - I am using a second composer.json with the modules. I will report that in that project. I close this.
