### ISSUE TITLE
Uncomment default.settings.php local.settings.php area

### ISSUE THREAD

**Issue by allgood2386** [drupal-composer/drupal-composer-project#102]
default.settings.php comes with the following lines commented out:

```
# if (file_exists(__DIR__ . '/settings.local.php')) {
#   include __DIR__ . '/settings.local.php';
# }
```

These should be uncommented by default going forward. Acquia hosting does this by default and now more and more drupal projects would like to use settings.php as a configuration piece for non-sensitive information while db connection info is kept in local.settings.php

This also may require edits to .gitignore. I haven't provided a pr for this but am more than willing once we have a discussion/ it's decided it's a good direction for the project.

**Comment by colinodell** [comment]
+1

**Comment by greg-1-anderson** [comment]
c.f. #77, which removes this file.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
