### ISSUE TITLE
Why is git remote origin pointing to the project after installation?

### ISSUE THREAD

**Issue by allella** [drupal-composer/drupal-composer-project#108]
Installed the package with no issues, but now that I'm modifying files it's unclear why the git remote origin is pointing to git://github.com/drupal-composer/drupal-project.git  I obviously don't want to push my customizations to this Github project.

I know I could change the origin to my own git repo and push/pull as usual, but want to make sure I'm doing it the way that's intended.

Sorry if I missed the documentation, but I read the Readme and multiple tutorials on the drupal-composer way and the only thing they say is not to commit /vendors, which I understand.

What I'm talking about is committing changes to my composer.json, /sites and eventually custom module and theme code.

I'm glad to put in time writing up more info for a Readme or Wiki page if this is something simple like changing the remote origin after install.

**Comment by derhasi** [comment]
Did you use `--keep-vcs` in the `create-project` command?

**Comment by allella** [comment]
Checked the bash_history and this was the last attempt

`composer create-project drupal-composer/drupal-project:8.x-dev public_html/test --stability dev --no-interaction`

The only thing unusual was an out of memory error when I ran composer update, but that would have been after this step.

I'll try again and see if I can replicate.

**Comment by allella** [comment]
The .git directory remained after an out of memory error and when I freed up memory and re-ran the command it must have never cleaned up from the previous failure.
`Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory'`

It is curious when I had so much OOM errors with at least 1/2GB of RAM and 1/2 GB or Swap free, but I guess that's a composer and server thing.
