### ISSUE TITLE
PHP file-based warnings followed by an ERROR?

### ISSUE THREAD

**Issue by jpstacey** [drupal-composer/drupal-composer-project#109]
Thanks for this project. I'm really excited to be using Composer rather than Drush Make, much as I've loved the latter over the years.

When I run your example command locally, composer installs all of its dependencies, then writes the lock and autoload files.... and then after

```
Extracting /tmp//drupal-scaffold-1455809014/drupal-8.0.3.tar.gz
```

I get a number of PHP warnings:

```
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /ROOT/vendor/drupal-composer/drupal-scaffold/src/Extract.php on line 70
PHP Stack trace:
...
PHP  12. rename() /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php:70

Warning: rename(): The first argument to copy() function cannot be a directory in /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php on line 70

Call Stack:
...
   17.9383    5397824  12. rename() /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php:70

PHP Warning:  rename(/var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/scripts/tmp17716083661455809031/drupal-8.0.3,/tmp//drupal-scaffold-1455809014/drupal-8): Invalid cross-device link in /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php on line 70
PHP Stack trace:.
...
PHP  12. rename() /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php:70

Warning: rename(/var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/scripts/tmp17716083661455809031/drupal-8.0.3,/tmp//drupal-scaffold-1455809014/drupal-8): Invalid cross-device link in /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php on line 70

Call Stack:
...
```

etc. I wouldn't mind them being PHP warnings, but the entire process ends with:

```
 [Remote\Rsync] Running rsync -a -v -z --include 'sites' --include 'sites/default' --include 'sites/default/default.settings.php' --include 'sites/default/default.services.yml' --include 'sites/development.services.yml' --include 'sites/example.settings.local.php' --include 'sites/example.sites.php' --exclude '.gitkeep' --exclude 'autoload.php' --exclude 'composer.json' --exclude 'composer.lock' --exclude 'core' --exclude 'drush' --exclude 'example.gitignore' --exclude 'LICENSE.txt' --exclude 'README.txt' --exclude 'vendor' --exclude 'themes' --exclude 'profiles' --exclude 'modules' --exclude 'sites/*' --exclude 'sites/default/*' /tmp//drupal-scaffold-1455809014/drupal-8/ /var/www/personal/drupal8-magneticphield/some-dir/web
sending incremental file list
rsync: change_dir "/tmp//drupal-scaffold-1455809014/drupal-8" failed: No such file or directory (2)

sent 20 bytes  received 12 bytes  64.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1183) [sender=3.1.0]
 [Remote\Rsync] sending incremental file list
 [Remote\Rsync] sent 20 bytes  received 12 bytes  64.00 bytes/sec
 [Remote\Rsync] total size is 0  speedup is 0.00
 [Remote\Rsync]  Exit code 23  Time 0.153s
 [Robo\Result] Stopping on fail. Exiting....
 [Robo\Result] Exit Code: 23
ERROR: rmdir(/var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/scripts/tmp17716083661455809031): Directory not empty 
in /var/www/personal/drupal8-magneticphield/some-dir/vendor/drupal-composer/drupal-scaffold/src/Extract.php:71

cp: cannot stat ‘web/sites/default/default.settings.php’: No such file or directory
chmod: cannot access ‘web/sites/default/settings.php’: No such file or directory
Create a sites/default/settings.php file with chmod 666
cp: cannot stat ‘web/sites/default/default.services.yml’: No such file or directory
chmod: cannot access ‘web/sites/default/services.yml’: No such file or directory
Create a sites/default/services.yml services.yml file with chmod 666
Create a sites/default/files directory with chmod 777
```

(I've attached [a full paste](%28https://github.com/drupal-composer/drupal-project/files/136456/drupal-composer-perm-probs.txt%29 of my command and the output.)

The site that ends up being produced is _somewhat_ functional, but e.g web/sites/default is completely empty. So I'm loath to go any further!

Any ideas? I've asked a couple of people on IRC and I've had confirmation it can be repeated, but they think it was working yesterday; maybe a recent change?

[drupal-composer-perm-probs.txt](https://github.com/drupal-composer/drupal-project/files/136456/drupal-composer-perm-probs.txt)

**Comment by webflo** [comment]
Filled a PR against robo to fix the issue. https://github.com/Codegyre/Robo/pull/275

**Comment by greg-1-anderson** [comment]
@webflo Thanks for tracking this down. I'll push for a tagged release of Robo asap.

**Comment by greg-1-anderson** [comment]
Workaround:  In your composer.json `require` section, change your drupal-scaffold line to:

`"drupal-composer/drupal-scaffold": "dev-use-better-apis",`

Once we have a tagged release of Robo available, we'll be able to make a stable release of drupal-scaffold that fixes this problem.

**Comment by jpstacey** [comment]
Thanks for chasing this up: unfortunately, running `composer install` on a clone of 8.x HEAD yields the same errors, with or without that change to the `"require"` section of `composer.json`. I even entirely deleted `vendor/` and `web/` between installs, just to make totally sure.

Let me know if there's anything I'm missing re this fix.

**Comment by greg-1-anderson** [comment]
This worked for me:

```
mkdir 'scaffold clone test'
cd 'scaffold clone test'
git clone git@github.com:drupal-composer/drupal-project.git
cd drupal-project/
vi composer.json # change required version of drupal-scaffold to 'dev-use-better-apis'
composer install
```

If you have the new code, you will see `[Archive\Extract] Extracting...` in the log messages. The old code says `[DrupalComposer\DrupalScaffold\Extract] Extracting...`.  Maybe if you ran `composer install` once without changing the required version of drupal-scaffold, Composer may have cached the older code. Try again with from a clean directory, and see if that clears things up.

**UPDATE**: I realized I wasn't completely clear above. If you delete vendor and web, but leave composer.lock behind, then you're still going to get the same version of drupal-scaffold if you run composer install again.  Only composer update changes composer.lock, so be sure to get rid of that file too if you want to start over.

**Comment by jpstacey** [comment]
Yeah, I deleted the lock too; or rather, moved it aside so I could diff it with the new one and see if I could see any obvious differences (there were rather too many to point to any one thing!) I'll run a scorched earth now, with the edit, following your steps above.

**Comment by jpstacey** [comment]
Right, I'm still getting the error, although bits of the log _have_ changed:

```
...
 [Archive\Extract] Extracting /tmp//drupal-scaffold-1455877126/drupal-8.0.3.tar.gz
 [Archive\Extract] /tmp//drupal-scaffold-1455877126/drupal-8.0.3.tar.gz extracted
PHP Warning:  rename(): The first argument to copy() function cannot be a directory in /var/www/personal/drupal8-magneticphield/drupal-project-issue-109/drupal-project/vendor/codegyre/robo/src/Task/Archive/Extract.php on line 92
...
```

Rather than doing the whole build again, I believe I can do:

```
rm web/autoload.php
sh  ./scripts/composer/post-install.sh
```

and that forces `drupal-scaffold` to re-run. Let me know if I'm missing anything in doing that, because if I get a chance I'm going to do that locally, to try to bugfix.

**Comment by jpstacey** [comment]
Aha, I think this could be a cross-volume thing: `/var/www` and `/tmp` are on different volumes on this machine. @greg-1-anderson this seems to be something you encountered with drush:

https://www.drupal.org/node/965878

(only five years ago, so I'm not surprised it rang any bells). It also seems to be related to this core PHP bug:

https://bugs.php.net/bug.php?id=54097

I'll have a look to see if the `exec()` workaround there is simple enough to try here.

**Comment by greg-1-anderson** [comment]
This should be fixed now.  Run `composer update` and ensure that you get drupal-scaffold 1.1.1 and codegyre/robo 0.7.0 (or later).

**Comment by jpstacey** [comment]
Great, I can confirm this works fine now; thanks for all the help getting this sorted.

Just a quick note for anyone reading this thread, you need to revert the workaround:

```
"drupal-composer/drupal-scaffold": "dev-use-better-apis",
```

so that 1.1.1 can be picked up instead.
