### ISSUE TITLE
Adding 8.x variant

### ISSUE THREAD

**Issue by derhasi** [drupal-composer/drupal-composer-project#11]
In an 8.x branch we can provide an example for Drupal 8. Maybe based on https://github.com/tstoeckler/drupal-site-template . Maybe we do not need the subtree split and use `drupal/drupal:8.*` from our drupal packagist.

**Comment by webflo** [comment]
I tried to update the site template against latest Drupal 8 beta and Drush. The current version is available on https://github.com/webflo/drupal-site-template/tree/dev

**Comment by webflo** [comment]
Merged the latest code from `webflo/drupal-site-template`. Huge thanks to @tstoeckler for the initial version.

@tstoeckler Please review the 8.x branch if i missed anything.
