### ISSUE TITLE
Could not authenticate against github.com

### ISSUE THREAD

**Issue by iainhouston** [drupal-composer/drupal-composer-project#112]
OK it's only noise, but is there any way of preventing `composer create-project drupal-composer/drupal-project:8.x-dev my-composer-project  --stability dev --no-interaction` producing loads of these authentication warnings (example below) as it tries the repo before the source and successfully installing the dependency?

`  - Installing doctrine/instantiator (1.0.5)
    Downloading: Connecting...    Failed to download doctrine/instantiator from dist: Could not authenticate against github.com
    Now trying to download from source
- Installing doctrine/instantiator (1.0.5)
  Cloning 8e884e78f9f0eb1329e445619e04456e64d8051d`

**Comment by derhasi** [comment]
Does following https://getcomposer.org/doc/articles/troubleshooting.md#api-rate-limit-and-oauth-tokens solve this problem?

**Comment by iainhouston** [comment]
Thanks @derhasi. 

FYI I used the same  Github OAuth token I use for Homebrew. 

So, given  I have `export HOMEBREW_GITHUB_API_TOKEN="<my_secret_token>"` in `~/.bash_exports`; 
I then do `composer config -g github-oauth.github.com <my_secret_token>` which causes  composer to remember <my_secret_token>  in `~/.composer/auth.json`   

Sorted!
