### ISSUE TITLE
Guzzle exception during install

### ISSUE THREAD

**Issue by wongataa** [drupal-composer/drupal-composer-project#116]
During fresh installation (on Ubuntu 15.10), I get an error during the install command

`composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`

The error:

`[GuzzleHttp\Exception\RequestException]                                                                                                                                                           
  Unable to open /tmp//drupal-scaffold-1456263912/drupal-8.0.3.tar.gz using mode r+: fopen(/tmp//drupal-scaffold-1456263912/drupal-8.0.3.tar.gz): failed to open stream: No such file or directory`

It happens during the "Generating Autoload Files" step. I've tried running the command with and without sudo but it makes no difference. It looks like Drupal core is not being downloaded properly or the tarball is being deleted somehow before it's unzipped.

As a result of the error (I think, not having successfully installed the project yet) I'm missing some key files for Drupal - the site can't properly load without them. If I copy/paste these files in from a simple `drush dl drupal-8` install, the site properly works (though I'm not sure what else I may be missing):
- web/.htaccess
- web/sites/default/default.services.yml
- web/sites/default/default.settings.php
- web/sites/default/settings.php
- web/sites/development.services.yml
- web/sites/example.settings.local.php
- web/sites/example.sites.php

Do you know how I can avoid this Guzzle error? Full log of the create-project command below.

**Comment by wongataa** [comment]
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction
Installing drupal-composer/drupal-project (8.x-dev 41dd0013bc492da50339b4878399f4a7876f1e89)
- Installing drupal-composer/drupal-project (8.x-dev 41dd001)
  Cloning 41dd0013bc492da50339b4878399f4a7876f1e89

Created project in some-dir
Loading composer repositories with package information
Installing dependencies (including require-dev)
- Installing cweagans/composer-patches (1.3.0)
  Loading from cache
- Installing composer/installers (v1.0.23)
  Loading from cache
- Installing psr/http-message (1.0)
  Loading from cache
- Installing guzzlehttp/psr7 (1.2.3)
  Loading from cache
- Installing guzzlehttp/promises (1.0.3)
  Loading from cache
- Installing guzzlehttp/guzzle (6.1.1)
  Loading from cache
- Installing jcalderonzumba/gastonjs (dev-master 21bebb8)
  Cloning 21bebb8ca03eb0f93ec2f3fad61192fb079e2622
- Installing twig/twig (v1.24.0)
  Loading from cache
- Installing symfony/polyfill-mbstring (v1.1.0)
  Loading from cache
- Installing symfony/css-selector (v2.7.9)
  Loading from cache
- Installing behat/mink (v1.7.0)
  Loading from cache
- Installing jcalderonzumba/mink-phantomjs-driver (v0.3.1)
  Loading from cache
- Installing pear/pear_exception (v1.0.0)
  Loading from cache
- Installing pear/console_getopt (v1.4.1)
  Loading from cache
- Installing pear/pear-core-minimal (v1.10.1)
  Loading from cache
- Installing pear/archive_tar (1.4.1)
  Loading from cache
- Installing symfony/event-dispatcher (v2.7.9)
  Loading from cache
- Installing symfony/filesystem (v2.7.9)
  Loading from cache
- Installing symfony/config (v2.7.9)
  Loading from cache
- Installing henrikbjorn/lurker (1.1.0)
  Loading from cache
- Installing symfony/process (v2.7.9)
  Loading from cache
- Installing symfony/console (v2.7.9)
  Loading from cache
- Installing symfony/finder (v2.7.9)
  Loading from cache
- Installing codegyre/robo (0.7.0)
  Loading from cache
- Installing drupal-composer/drupal-scaffold (1.1.1)
  Loading from cache
- Installing composer/semver (1.2.0)
  Loading from cache
- Installing zendframework/zend-diactoros (1.3.3)
  Loading from cache
- Installing symfony/http-foundation (v2.7.9)
  Loading from cache
- Installing symfony/psr-http-message-bridge (v0.2)
  Loading from cache
- Installing masterminds/html5 (2.1.2)
  Loading from cache
- Installing doctrine/lexer (v1.0.1)
  Loading from cache
- Installing egulias/email-validator (1.2.11)
  Loading from cache
- Installing psr/log (1.0.0)
  Loading from cache
- Installing symfony/debug (v2.7.9)
  Loading from cache
- Installing symfony/http-kernel (v2.7.9)
  Loading from cache
- Installing stack/builder (v1.0.3)
  Loading from cache
- Installing zendframework/zend-stdlib (3.0.0)
  Loading from cache
- Installing zendframework/zend-escaper (2.5.1)
  Loading from cache
- Installing zendframework/zend-feed (2.7.0)
  Loading from cache
- Installing easyrdf/easyrdf (0.9.1)
  Loading from cache
- Installing symfony/routing (v2.7.9)
  Loading from cache
- Installing symfony-cmf/routing (1.3.0)
  Loading from cache
- Installing doctrine/annotations (v1.2.7)
  Loading from cache
- Installing doctrine/inflector (v1.1.0)
  Loading from cache
- Installing doctrine/collections (v1.3.0)
  Loading from cache
- Installing doctrine/cache (v1.6.0)
  Loading from cache
- Installing doctrine/common (v2.5.3)
  Loading from cache
- Installing symfony/yaml (v2.7.9)
  Loading from cache
- Installing symfony/translation (v2.7.9)
  Loading from cache
- Installing symfony/validator (v2.7.9)
  Loading from cache
- Installing symfony/serializer (v2.7.9)
  Loading from cache
- Installing symfony/dependency-injection (v2.7.9)
  Loading from cache
- Installing symfony/class-loader (v2.7.9)
  Loading from cache
- Installing drupal/core (8.0.3)
  Loading from cache
- Installing pear/console_table (v1.3.0)
  Loading from cache
- Installing symfony/var-dumper (v2.8.2)
  Loading from cache
- Installing jakub-onderka/php-console-color (0.1)
  Loading from cache
- Installing jakub-onderka/php-console-highlighter (v0.3.2)
  Loading from cache
- Installing dnoegel/php-xdg-base-dir (0.1)
  Loading from cache
- Installing nikic/php-parser (v2.0.0)
  Loading from cache
- Installing psy/psysh (v0.7.0)
  Loading from cache
- Installing drush/drush (8.0.3)
  Loading from cache
- Installing padraic/humbug_get_contents (1.0.4)
  Loading from cache
- Installing padraic/phar-updater (1.0.3)
  Loading from cache
- Installing stecman/symfony-console-completion (0.5.1)
  Loading from cache
- Installing phpseclib/phpseclib (2.0.1)
  Loading from cache
- Installing alchemy/zippy (dev-master 92c773f)
  Cloning 92c773f7bbe47fdb30c61dbaea3dcbf4dd13a40a
- Installing symfony/dom-crawler (v2.7.9)
  Loading from cache
- Installing drupal/console (0.10.12)
  Loading from cache
- Installing symfony/browser-kit (v2.8.2)
  Loading from cache
- Installing fabpot/goutte (v3.1.2)
  Loading from cache
- Installing behat/mink-browserkit-driver (v1.3.1)
  Loading from cache
- Installing behat/mink-goutte-driver (v1.2.0)
  Loading from cache
- Installing mikey179/vfsstream (v1.6.2)
  Loading from cache
- Installing sebastian/version (1.0.6)
  Loading from cache
- Installing sebastian/global-state (1.1.1)
  Loading from cache
- Installing sebastian/recursion-context (1.0.2)
  Loading from cache
- Installing sebastian/exporter (1.2.1)
  Loading from cache
- Installing sebastian/environment (1.3.3)
  Loading from cache
- Installing sebastian/diff (1.4.1)
  Loading from cache
- Installing sebastian/comparator (1.2.0)
  Loading from cache
- Installing doctrine/instantiator (1.0.5)
  Loading from cache
- Installing phpdocumentor/reflection-docblock (2.0.4)
  Loading from cache
- Installing phpspec/prophecy (v1.6.0)
  Loading from cache
- Installing phpunit/php-text-template (1.2.1)
  Loading from cache
- Installing phpunit/phpunit-mock-objects (2.3.8)
  Loading from cache
- Installing phpunit/php-timer (1.0.7)
  Loading from cache
- Installing phpunit/php-token-stream (1.4.8)
  Loading from cache
- Installing phpunit/php-file-iterator (1.4.1)
  Loading from cache
- Installing phpunit/php-code-coverage (2.2.4)
  Loading from cache
- Installing phpunit/phpunit (4.8.23)
  Loading from cache

behat/mink suggests installing behat/mink-selenium2-driver (slow, but JS-enabled driver for any app (requires Selenium2))
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
pear/archive_tar suggests installing ext-xz (lzma2 compression support.)
henrikbjorn/lurker suggests installing ext-inotify (>=0.1.6)
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component, for optionally caching feeds between requests)
zendframework/zend-feed suggests installing zendframework/zend-db (Zend\Db component, for use with PubSubHubbub)
zendframework/zend-feed suggests installing zendframework/zend-http (Zend\Http for PubSubHubbub, and optionally for use with Zend\Feed\Reader)
zendframework/zend-feed suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component, for easily extending ExtensionManager implementations)
zendframework/zend-feed suggests installing zendframework/zend-validator (Zend\Validator component, for validating email addresses used in Atom feeds and entries ehen using the Writer subcomponent)
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
symfony/routing suggests installing symfony/expression-language (For using expression matching)
symfony/validator suggests installing symfony/intl ()
symfony/validator suggests installing symfony/property-access (For using the 2.4 Validator API)
symfony/validator suggests installing symfony/expression-language (For using the 2.4 Expression validator)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
pear/console_table suggests installing pear/Console_Color2 (>=0.1.2)
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
drush/drush suggests installing drush/config-extra (Provides configuration workflow commands, such as config-merge.)
phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-mcrypt (Install the Mcrypt extension in order to speed up a few other cryptographic operations.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter)
sebastian/global-state suggests installing ext-uopz (*)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
Writing lock file
Generating autoload files

> sh ./scripts/composer/post-install.sh
> DrupalComposer\DrupalScaffold\Plugin::scaffold
>  [FileSystem\FilesystemStack] mkdir ["\/tmp\/\/drupal-scaffold-1456263912"]
>  [FileSystem\FilesystemStack] mkdir ["\/home\/andrew\/ahuber_skel\/git_repos\/some-dir\/web\/sites\/default"]
>  [FileSystem\FilesystemStack] _chmod ["\/home\/andrew\/ahuber_skel\/git_repos\/some-dir\/web\/sites\/default",493]
>  [FileSystem\CleanDir] Cleaned /tmp//drupal-scaffold-1456263912

  [GuzzleHttp\Exception\RequestException]  
  Unable to open /tmp//drupal-scaffold-1456263912/drupal-8.0.3.tar.gz using mode r+: fopen(/tmp//drupal-scaffold-1456263912/drupal-8.0.3.tar.gz): failed to open stream: No such file or directory 

  [RuntimeException]  
  Unable to open /tmp//drupal-scaffold-1456263912/drupal-8.0.3.tar.gz using mode r+: fopen(/tmp//drupal-scaffold-1456263912/drupal-8.0.3.tar.gz): failed to open stream: No such file or directory 

drupal_scaffold:download [--source [SOURCE]] [--webroot [WEBROOT]] [--excludes [EXCLUDES]] [--includes [INCLUDES]] [--] [<version>]

cp: cannot stat ‘web/sites/default/default.settings.php’: No such file or directory
chmod: cannot access ‘web/sites/default/settings.php’: No such file or directory
Create a sites/default/settings.php file with chmod 666
cp: cannot stat ‘web/sites/default/default.services.yml’: No such file or directory
chmod: cannot access ‘web/sites/default/services.yml’: No such file or directory
Create a sites/default/services.yml services.yml file with chmod 666
Create a sites/default/files directory with chmod 777

**Comment by webflo** [comment]
Is it still an issue?

**Comment by webflo** [comment]
I’m closing this issue because it has been inactive for a few weeks.  Please reopen if you still encounter this issue with the latest version.

Thanks!
