### ISSUE TITLE
windows line endings in post-install.sh

### ISSUE THREAD

**Issue by Lowell20** [drupal-composer/drupal-composer-project#117]
I may have 2 issues, this one I think is secondary
the primary seems to be that I have no sites directory with the default/settings.php, etc, files

this post-install.sh issue occurs when running the composer create-project command
`composer create-project drupal-composer/drupal-project:~8.0 PROJECTNAME --stability dev --no-interaction`
the post-install.sh file has windows line endings and the script can't be run because the first line actually looks like this to the interpreter
`#!/bin/sh^M`

I have updated composer with composer self-update and everything else seems to be working as expected

**Comment by Lowell20** [comment]
`Composer version 1.0-dev (cd3c3ac56dbcb0d663d7970db625e9981af5dc36) 2016-02-25 17:27:53`

**Comment by Lowell20** [comment]
ooh, great, I found that inside the post-install.sh script, the drupal-scaffold creates the sites directories
So it makes sense they aren't created yet when post-install.sh fails

**Comment by Lowell20** [comment]
I found a work-around for this issue by configuring my git settings with this.
`git config --global core.autocrlf input`
although I am now having subsequent trouble with 
`PHP Fatal error:  Call to undefined function DrupalComposer\DrupalScaffold\curl_init()`

**Comment by Lowell20** [comment]
pfffft, solved...needed to install php5-curl, duh

**Comment by webflo** [comment]
We should add curl as platform dependency
