### ISSUE TITLE
'composer install' after deploying project from Git doesn't move core and modules into web/ directory

### ISSUE THREAD

**Issue by brianV** [drupal-composer/drupal-composer-project#119]
When I initially create the project as per the instructions, I get a perfectly functional Drupal install. 

However, when I commit it to git (using the generated .gitignore), checkout on my remote server and 'composer install', it appears that drupal-scaffold fails to copy the core, modules and themes directories into the web/ directory.

For example - here is the directory tree after checking out from git and running 'composer install':

```
dev@jackalope-portal:~/portal/drupal$ tree web
web
├── autoload.php
├── index.php
├── robots.txt
├── sites
│   ├── default
│   │   ├── default.services.yml
│   │   ├── default.settings.php
│   │   ├── files
│   │   ├── services.yml
│   │   └── settings.php
│   ├── development.services.yml
│   ├── example.settings.local.php
│   └── example.sites.php
├── update.php
└── web.config
```

Notice the missing 'core', 'modules', 'profiles', and 'themes directories.

**Comment by webflo** [comment]
Is it still an issue?

**Comment by webflo** [comment]
I’m closing this issue because it has been inactive for a few weeks.  Please reopen if you still encounter this issue with the latest version.

Thanks!
