### ISSUE TITLE
autoload.php path on composer install is wrong

### ISSUE THREAD

**Issue by iampuma** [drupal-composer/drupal-composer-project#120]
Installing the project will currently assume the autoload.php is in the /web directory, but is actually in the /vendor folder. Manually changing the web/index.php "require autoload.php path" fixes that.

Also what about the install.php file?

Any help/documentation how to correctly use the autoload.php?

**Comment by webflo** [comment]
`web/autoload.php` should be auto-generated after the composer create-project command. `autoload.php` contains the following after installation. Which is correct afaik.

```
<?php

/**
 * @file
 * Includes the autoloader created by Composer.
 * This file was generated by drupal-composer/drupal-scaffold.
 * https://github.com/drupal-composer/drupal-scaffold
 *
 * @see composer.json
 * @see index.php
 * @see core/install.php
 * @see core/rebuild.php
 * @see core/modules/statistics/statistics.php
 */

return require __DIR__ . '/../vendor/autoload.php';
```

**Comment by iampuma** [comment]
I did a clean install but the autoload.php file still does not get created in the web/ directory. 

EDIT: Figures, I did not have sufficient permissions on my Vagrant machine. Executing as sudo generated the autoload.php file.

Thanks
