### ISSUE TITLE
post-install.sh line endings

### ISSUE THREAD

**Issue by nor4a** [drupal-composer/drupal-composer-project#124]
On the initial script install by typing: 
$composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction
I have an error: 
Script sh ./scripts/composer/post-install.sh handling the post-install-cmd event returned with an error
  [RuntimeException]
: command not found         mposer/post-install.sh: line 2:
: command not found                        4:
'  /scripts/composer/post-install.sh: line 10: syntax error near unexpected token `do
'                                 sh: line 10:`    do

It seams that the problem is related to line endings... 

By applying this command: 
$sed -i 's/\r//' /scripts/composer/post-install.sh
The problem seams to be fixed... and I can rerun the script and coninue the installation.

**Comment by webflo** [comment]
Hmm is it a problem in you git config? We had a similar bug report in https://github.com/drupal-composer/drupal-project/issues/117

**Comment by dsdobrzynski** [comment]
I am experiencing this as well. I created a PR fixing this.

**Comment by webflo** [comment]
Please test/review #128
