### ISSUE TITLE
How to install a specific non-dev version of drupal, e.g. 8.0.5 ?

### ISSUE THREAD

**Issue by therobyouknow** [drupal-composer/drupal-composer-project#129]
If I do:
sudo composer create-project drupal-composer/drupal-project:~8.0 d8.dev --stability dev --no-interaction

Then this works - off it goes downloading things.

BUT - the above is for the dev version of Drupal 8.

What if I want to use a production version of Drupal 8, e.g. 8.0.5 ?

If I try:

sudo composer create-project drupal-composer/drupal-project:~8.0.5 d8.dev --stability stable --no-interaction

I get an error saying that it can't find the version.

So what command should I use to download the latest stable version of drupal 8?

**Comment by webflo** [comment]
The project template contains the latest stable release of Drupal core by default. `8.x` in composer create-project is just the version of this template and not the version of Drupal core.

You can verify the core version via Drupal Backend UI or `composer info drupal/core`

**Comment by therobyouknow** [comment]
Thanks webflo. If that is the case, then would we still need to use "--stability dev" in the command if it contains the latest stable release? (is it superfluous?) since "--stability dev" implies that the latest dev release of Drupal 8 is pulled down (8.2.x-dev rather than a stable release.)

Also, what does the ~8.0 refer to please?

**Comment by webflo** [comment]
The create-project command creates a new project of drupal-composer/drupal-project. drupal-composer/drupal-project
 has a dependency to drupal/core stable. You can update core via composer afterwards. All options these options on the create-project command apply to the project template.

**Comment by andriokha** [comment]
See also #368
