### ISSUE TITLE
TravisCI build failure: non-existent service "renderer"

### ISSUE THREAD

**Issue by ohthehugemanatee** [drupal-composer/drupal-composer-project#130]
I was excited to see that this project includes a travisCI configuration. It seems simple enough, but none of the TravisCI tests can make it through site-install. 

```
$ ./../vendor/bin/drush site-install --verbose --yes --db-url=sqlite://tmp/site.sqlite

You are about to CREATE the 'tmp/site.sqlite' database. Do you want to continue? (y/n): y

Sites directory                                                         [notice]

/home/travis/build/ohthehugemanatee/d8-testbed/web/sites/default

already exists - proceeding.

Starting Drupal installation. This takes a while. Consider using the [ok]

--notify global option.

exception                                                            [error]

'Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException'

with message 'You have requested a non-existent service "renderer".'

in

/home/travis/build/ohthehugemanatee/d8-testbed/vendor/symfony/dependency-injection/ContainerBuilder.php:800

Stack trace:

#0

/home/travis/build/ohthehugemanatee/d8-testbed/vendor/symfony/dependency-injection/ContainerBuilder.php(444):

Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('renderer')

#1

/home/travis/build/ohthehugemanatee/d8-testbed/web/core/lib/Drupal.php(158):

Symfony\Component\DependencyInjection\ContainerBuilder->get('renderer')

#2

/home/travis/build/ohthehugemanatee/d8-testbed/web/core/includes/install.core.inc(1151):

Drupal::service('renderer')

#3

/home/travis/build/ohthehugemanatee/d8-testbed/web/core/includes/install.core.inc(1089):

install_database_errors(Array, './sites/default...')
```

[See a full build](https://travis-ci.org/ohthehugemanatee/d8-testbed/jobs/117177227#L695)

I thought I might be getting bitten by [this bug](https://www.drupal.org/node/2443839) but applying that patch in composer.json didn't seem to have an effect. What am I missing here?

**Comment by ohthehugemanatee** [comment]
Ah... the problem was that I included my settings.php in the repo. I guess I'm used to it being excluded by drupal's own .gitignore, but since Drupal itself is now excluded that isn't picked up?

What's the intended way to use Travis with drupal-project?

**Comment by webflo** [comment]
The Travis CI tests are working fine atm. Please update your fork.

I’m closing this issue because it has been inactive for a few weeks.  Please reopen if you still encounter this issue with the latest version.

Thanks!
