### ISSUE TITLE
support request: cmdline-only backup & restore procedure for Drupal8 sites installed & maintained with _this_ scaffold

### ISSUE THREAD

**Issue by ghost** [drupal-composer/drupal-composer-project#134]
I wasn't sure whether to post this at stackexchange or here.  I picked here cuz, for me, I'm only interested in the solution that works best with this sscaffold solution, since I've made a decision that it's what works best for me.

I'm trying to work out a cmd-line backup+destroy+restore procedure for a composer-installed Drupal8 instance

I know there are some modules (Backup & Migrate, Backup DB), but I prefer not to depend on something 'inside' of Drupal to backup/restore Drupal.  Especially since those modules look like they're still being developed, and have some history of getting completely fubar'd.

I create my project with composer

```
composer -vvv create-project --keep-vcs --stability dev drupal-composer/drupal-project:8.x-dev mysite
```

I've put the installed site under local git revision control; the wed root's a git repo.

The composer-install generated a .gitignore file

```
cat .gitignore
    # Ignore directories generated by Composer
    drush/contrib
    vendor
    web/core
    web/modules/contrib
    web/themes/contrib
    web/profiles/contrib

    # Ignore Drupal's file directory
    web/sites/default/files

    # Ignore files generated by PhpStorm
    .idea
```

Reading various posts I also see people use

```
web/sites/*/files
web/sites/*/private
web/sites/*/settings*.php
web/sites/*/services*.yml
```

I'm not sure whether they make sense in this scenario.

So what I want to do is 

```
(1) backup the site using whatever the current 'best practices' procedure is
(2) rm -rf the site directory
(3) drop the database
(4) restore it completely
```

all from the cmd-line.

One way of backing up the site is using drush

```
drush archive-dump
```

This creates a .tar.gz

```
<backup dir>/archive-dump/20160328171908/mysite.20160328_171908.tar.gz
```

If I expand that to take a look

```
cd <backup dir>/archive-dump/20160328171908
tar zxf mysite.20160328_171908.tar.gz
```

I get

```
tree 20160328171908
    20160328171908
    ├── mysite.20160328_171908.tar.gz
    ├── mysite.sql
    ├── MANIFEST.ini
    └── web
        └── sites
            └── default
                ├── default.services.yml
                ├── default.settings.php
                ├── files
                │   ├── config_oPphoM1aBIGGN2Egc6Z2jh1VTeUf3AO8COmrKcBrkukA1QNk4Ps3RD69qaV8DQNPaPqix5g3tw
                │   │   └── sync
                │   │       └── README.txt
                │   └── styles
                ├── services.yml
                └── settings.php
```

But that backs up only the /web dir, NOT any of the info in the webroot above it,

```
ls -al <webroot>
    total 300K
    drwxrwx---+  7 www www 4.0K Mar 28 09:04 ./
    drwxrwx---+  7 www www 4.0K Mar 28 10:09 ../
    -rw-rw----+  1 www www 3.0K Mar 28 09:11 composer.json
    -rw-rw----+  1 www www 225K Mar 28 09:15 composer.lock
    drwxrwx---+  2 www www 4.0K Mar 28 08:40 drush/
    drwxrwx---+  8 www www 4.0K Mar 28 08:40 .git/
    -rw-rw----+  1 www www  542 Mar 28 09:52 .gitignore
    -rw-rw----+  1 www www  18K Mar 28 08:40 LICENSE
    -rw-rw----+  1 www www  481 Mar 28 08:40 phpunit.xml.dist
    -rw-rw----+  1 www www 4.7K Mar 28 08:40 README.md
    drwxrwx---+  3 www www 4.0K Mar 28 08:40 scripts/
    -rw-rw----+  1 www www 1.1K Mar 28 08:40 .travis.yml
    drwxrwx---+ 40 www www 4.0K Mar 28 10:08 vendor/
    drwxrwx---+  7 www www 4.0K Mar 28 11:22 web/
```

What's the best way of getting "all" the info backed up?

Does it make sense to use drush at all?  Or is there a 'newer', more consistent way to backup/restore, now that I'm using git and this composer scaffold? Maybe using percona backup or automysqlbackup etc?

What I hope to get to is a reliable, recommended & documented procedure for cmd-line backup&restore of Drupal8 sites built with this scaffold and maintained with composer -- and that it gets posted to this wiki

**Comment by webflo** [comment]
We have a related issue in the drush issue queue, but the discussion has stalled a bit https://github.com/drush-ops/drush/issues/1779

**Comment by ghost** [comment]
Thanks for the reference.

To 'rewarm' & continue the discussion, where'd you prefer? here, or there?

**Comment by ghost** [comment]
It'd be useful to understand & document this backup / restore procedure without the dependency on drush.

drush can deal with it eventually in their own time, if the interest is there, for sure.

But this scaffold's going to be used whether or not drush supports it.  Before putting a site built on it into production, working backup & restore is pretty importantt, IMO.

UPDATE:
From that thread, sounds like using drush to backup/restore isn't going to happen anytime soon, from the maintainers anyway, and that using it isn't even considered the right approach.

So back in 'here', and asking for some docs on the right way to work with this scaffold.  If it's "git & database" that's great.  Just want to get to some procedure that's recommended.

**Comment by normanlolx** [comment]
Inactive. Please feel free to reopen the issue by posting a more concrete plan. Many thanks 🙂
