### ISSUE TITLE
'web' directory shouldn't be hard coded in ScriptHandler.php

### ISSUE THREAD

**Issue by generalredneck** [drupal-composer/drupal-composer-project#135]
On [scripts/composer/ScriptHandler.php#L16](https://github.com/drupal-composer/drupal-project/blob/04df731/scripts/composer/ScriptHandler.php#L16), there is a hard reference to web. It's easy enough to change the code, but shouldn't this look at the a property somewhere. In the case of using "docroot" or "drupal" as on Acquia and Pantheon?

**Comment by joestewart** [comment]
Related discussion in #64

**Comment by generalredneck** [comment]
My bad... missed the very [last comment](https://github.com/drupal-composer/drupal-project/issues/64#issuecomment-206455356) in that one...
