### ISSUE TITLE
Consider reducing dependencies

### ISSUE THREAD

**Issue by bartfeenstra** [drupal-composer/drupal-composer-project#137]
Does drupal-project use `cweagans/composer-patches`, `drush/drush`, and `drupal/console`? I'm wondering if we can remove those dependencies to reduce the site of the dependency tree, and the time that's needed to build codebases.

**Comment by webflo** [comment]
cweagans/composer-patches, drush/drush, and drupal/console are not required. You can safely remove it from your site. But i personally consider it as feature, because the project is self contained and functional on any server i deploy to.

**Comment by webflo** [comment]
Have your tried to cache the vendor folder in your ci setup?

**Comment by bartfeenstra** [comment]
I know why those were added, but it's unnecessary for a project that does not apply patches, nor uses either CLI tool itself. Pretending that those packages are requirements obscures the truth. I'd add them to personal/company templates, but not to a generically reusable library.

**Comment by bartfeenstra** [comment]
Also, I am aware this cannot be changed in 1.x.y, which is why this is an issue for later and not a PR for now.

**Comment by rodrigoaguilera** [comment]
I use this project as a template. I have no idea how it can be used as a reusable library.

**Comment by bartfeenstra** [comment]
`composer require drupal-composer/drupal-project:*` is how we do it. This means that we can pull in updates through Composer. The only other step one needs to take is add the two scripts (or none, or one of them) to your top-level `composer.json`.

**Comment by bartfeenstra** [comment]
However you use this package, it does not need those dependencies, and it adds obscurity and slows down Composer installation. There's no need for them.

**Comment by derhasi** [comment]
@bartfeenstra, this project is not meant to be used as a library. This is and shall only be a template for (some) best practices and possibilities with Composer in Drupal.

**Comment by weitzman** [comment]
Right. webflo has done the Drupal coimmunity  a big service with this project, showing up best practices for assembling a Drupal codebase and related tools. This project is about teaching, as much as it is about a starter package. In that spirit, I am quite happy that those tools are in the composer.json. If they were omitted, many folks would assume that Drush/Console dont belong in the project build. That would be wrong - Drush recommends a site-local Drush just as this project shows.

**Comment by bartfeenstra** [comment]
Is there a way in which we can split off the actual tools this package provides to a separate package, and have the template depend on them? That way the actual logic and the best practices are separated, communicating their intentions clearly, and projects can use the tools package without necessarily using the template package.

**Comment by derhasi** [comment]
Packing the "tools" in a tools package make things even more complicated. You will get an additional level of dependencies that have to work as a package. So everytime, you want to use a different tool version or a different tool at all, you might need to remove the tools package. I can only see downsides for that approach.

Projects always will be highly customized and dependent on the team working on it. Using _drupal-project_ should first and foremost be a starting point for the team - and a constant ressource for a team to update their project to new best practices later on. But as projects evolve, they will likely diverge from the original template.

@bartfeenstra, why do you want to use _drupal-project_ as a library in the first place?

**Comment by bartfeenstra** [comment]
1) I don't want to fork or copy the files, as we do not want to maintain the scaffolding code internally ourselves, and neither should we, because it's reusable for many other projects. Adding `drupal-project` as a dependency means we can pull in new versions of `drupal-project` and `drupal-scaffold` when they receive improvements through contributions.
2) Using `drupal-project` as a dependency works well in terms of not including its code in our repository, but it also pulls in more dependencies than we need (which is unnecessary, but not in any way a blocker at this moment), and it hardcodes a dependency on Drupal 8.0 (see https://github.com/drupal-composer/drupal-project/pull/139 to allow 8.1 as well).

`drupal-scaffold` is a great tool library that focuses on building a front controller based on `drupal/drupal`. The one tool that is 'missing' seems to be `\DrupalProject\composer\ScriptHandler` which belongs to `drupal-project`. I'm wondering if we can consolidate that into a single package, so there's one package to build a `drupal/drupal` front controller, and another to provide developers with default integration and best practices in the form of a `composer.json` template.

**Comment by jameswilson** [comment]
Sorry for spamming this issue with tangential info, but this could be helpful for some, regarding the earlier comments on this thread.

To reduce time to build with `composer install` tasks... give https://github.com/hirak/prestissimo a try.   If it speeds up downloads then in theory this will have a net positive effect in recalculating dependencies.

**Comment by bartfeenstra** [comment]
Especially after yesterday's release of `drupal-scaffold` 2, it is very easy to use the Composer tools without using `drupal-project`. The following `composer.json` template is enough to pull in and run the tools necessary to wrap `drupal/core` and Drupal extensions in `drupal/drupal`:

``` json
{
  "require": {
    "composer/installers": "~1.0.23",
    "drupal-composer/drupal-scaffold": "~2.0",
  },
  "scripts": {
    "post-install-cmd": [
      "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
    ],
    "post-update-cmd": [
      "DrupalComposer\\DrupalScaffold\\Plugin::scaffold"
    ]
  }
}
```

Moving from a dependency on `drupal-project` to a direct dependency on `drupal-scaffold`, combined with the performance improvements in version 2, sped up our build process significantly.
