### ISSUE TITLE
Parse error: syntax error, unexpected '[', expecting ')' 

### ISSUE THREAD

**Issue by com2** [drupal-composer/drupal-composer-project#142]
According to instructions I do: 

> composer update drupal/core

presently I get: 

> Parse error: syntax error, unexpected '[', expecting ')' in .... vendor/drupal-composer/drupal-scaffold/src/Handler.php on line 116

Can that be a php version issue? I'm working with an old Ubuntu 12.04 but aliased php to a self compiled 5.6.9.

**Comment by webflo** [comment]
Hmm sorry i don't know what happend. You are the only use with this strange error.

**Comment by derhasi** [comment]
This seems to be a problem with your PHP version. Composer may run with a PHP version < 5.4, as the short array syntax is not recognized. See https://github.com/drupal-composer/drupal-scaffold/blob/master/src/Handler.php#L116. Have you checked the version with `php --version`?

**Comment by webflo** [comment]
It is probably a issue in your local setup and we don't use robo anymore. Closing the issue because it does not apply anymore.
