### ISSUE TITLE
Major Drupal core update, can't update files with command provided in docs

### ISSUE THREAD

**Issue by Deele** [drupal-composer/drupal-composer-project#146]
There was a jump between 8.0.6 and 8.1.1 versions for Drupal and update of multiple Drupal projects was required.

I noticed that this project had some updates too, so I manually changed `composer.json` contents to fit [the one](/drupal-composer/drupal-project/blob/8.x/composer.json) in this repo (I do not know how to move changes done in this repo to my project).

After that, while trying to update it with command provided in docs:

`composer update drupal/core`

I got simple answer from composer:

`Nothing to install or update`

Forcibly changing version of drupal core from `~8.0` to `8.1.1` led to following errors:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/core 8.1.1 -> satisfiable by drupal/core[8 .1.1].
    - Conclusion: remove symfony/event-dispatcher v2.7.11
    - Conclusion: don't install symfony/event-dispatcher v2.7.11
    - drupal/core 8.1.1 requires symfony/event-dispatcher ~2.8 -> satisfiable by  symfony/event-dispatcher[2.8.x-dev, v2.8.0, v2.8.0-BETA1, v2.8.1, v2.8.2, v2.8. 3, v2.8.4, v2.8.5, v2.8.6].
    - Can only install one of: symfony/event-dispatcher[2.8.x-dev, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.0, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.0-BETA1, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.1, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.2, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.3, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.4, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.5, v2.7.11].
    - Can only install one of: symfony/event-dispatcher[v2.8.6, v2.7.11].
    - Installation request for symfony/event-dispatcher == 2.7.11.0 -> satisfiab le by symfony/event-dispatcher[v2.7.11].
```

**Comment by Deele** [comment]
After a talk with @webflo it turned out to be an issue with dependencies. With this major update, other components were updated too, and drupal core depends on those updated versions of components. When trying to update only drupal core via `composer update drupal/core` command, composer fails to find required updated versions of dependencies so it does not even offer an update and silently ends an update.

Instead, use `composer update drupal/core --with-dependencies` to do this major Drupal update, to update dependencies together with core.

I think, this information should be added in repo documentation, so I'm not closing this issue yet.

**Comment by Berdir** [comment]
See also the related drupal answers question: http://drupal.stackexchange.com/questions/198428/how-to-update-8-0-x-to-8-1-x-with-composer

**Comment by webflo** [comment]
Documentation has been updated in https://github.com/drupal-composer/drupal-project/pull/181
