### ISSUE TITLE
Switch ScriptHandler.php over to a RoboFile.php

### ISSUE THREAD

**Issue by RobLoach** [drupal-composer/drupal-composer-project#149]
[Robo](http://robo.li) could likely do all of https://github.com/drupal-composer/drupal-project/blob/8.x/scripts/composer/ScriptHandler.php .

Integrating with Composer's [`scripts`](https://getcomposer.org/doc/articles/scripts.md) will clean up that process a lot.

**Comment by webflo** [comment]
I close the issue, RoboFile.php is gone since scaffold v2.

**Comment by RobLoach** [comment]
It's still there:
https://github.com/drupal-composer/drupal-project/blob/8.x/scripts/composer/ScriptHandler.php

We're using Scaffold v2, but drupal-project still uses ScriptHandler.php.

**Comment by webflo** [comment]
But it means we introduce robo as dependency again.

**Comment by RobLoach** [comment]
Gotchya. Let's leave it closed for now. If I'm feeling so inclined, I'll open a PR to weigh the pros/cons.

**Comment by webflo** [comment]
Alright, thanks!
