### ISSUE TITLE
Unable to patch drupal itself

### ISSUE THREAD

**Issue by villette** [drupal-composer/drupal-composer-project#15]
Hi ! I'm using this method to manage my project and it have been working great until I had to apply a path to Drupal itself.
With drush make, I would have done something like that:

```
projects[drupal][patch][] = "https://www.drupal.org/files/911354-drupal-profile-85.patch"
```

So I have tried to use the method described in the **Patches** section but I couldn't get it to work, it keeps getting me this error:

```
  Failing patch detected - reverting already applied patches

  [Netresearch\Composer\Patches\PatchCommandException]
  Patch 0 would fail!
  Error executing command "patch -f -p1 --no-backup-if-mismatch -r - --dry-run":
  can't find file to patch at input line 5
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff --git a/includes/bootstrap.inc b/includes/bootstrap.inc
  |index 80563ef..80a7b5a 100644
  |--- a/includes/bootstrap.inc
  |+++ b/includes/bootstrap.inc
  --------------------------
  No file to patch.  Skipping patch.
  1 out of 1 hunk ignored
  can't find file to patch at input line 33
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff --git a/includes/common.inc b/includes/common.inc
  |index 31923f2..b722db2 100644
  |--- a/includes/common.inc
  |+++ b/includes/common.inc
  --------------------------
  No file to patch.  Skipping patch.
  1 out of 1 hunk ignored
  can't find file to patch at input line 46
  Perhaps you used the wrong -p or --strip option?
  The text leading up to this was:
  --------------------------
  |diff --git a/modules/simpletest/drupal_web_test_case.php b/modules/simpletest/drupal_web_test_case.php
  |index 0853c7d..74acb13 100644
  |--- a/modules/simpletest/drupal_web_test_case.php
  |+++ b/modules/simpletest/drupal_web_test_case.php
  --------------------------
  No file to patch.  Skipping patch.
  1 out of 1 hunk ignored
```

I am using these plugins in my project:
- azt3k/non-destructive-archive-installer
- netresearch/composer-patches-plugin
- composer/installers

Here is my composer.json file so you may tell me what's wrong with it (it's not the actual one but it illustrates the problem correctly):

```
{
  "name": "me/my-project",
  "minimum-stability": "beta",
  "prefer-stable": true,
  "repositories": [{
    "type": "package",
    "package": {
      "name": "drupal/drupal",
      "type": "non-destructive-archive-installer",
      "version": "7.35",
      "dist": {
        "url": "http://ftp.drupal.org/files/projects/drupal-7.35.zip",
        "type": "zip"
      },
      "require": {
        "azt3k/non-destructive-archive-installer": "*"
      },
      "extra": {
        "target-dir": ".",
        "omit-first-directory": "true",
        "patches": {
          "drupal/drupal": {
            "7.35": [
              {
                "title": "Tests in profiles/[name]/modules cannot be run and cannot use a different profile for running tests",
                "url": "https://www.drupal.org/files/911354-drupal-profile-85.patch"
              }
            ]
          }
        }
      }
    }
  }, {
    "type": "composer",
    "url": "http://packagist.drupal-composer.org/"
  }],
  "require": {
    "azt3k/non-destructive-archive-installer": "0.2.*",
    "netresearch/composer-patches-plugin": "~1.0",
    "composer/installers": "~1.0",

    "drupal/drupal": "7.35"
  },
  "config": {
    "vendor-dir": "sites/all/vendor"
  },
  "extra": {
    "installer-paths": {
      "sites/all/modules/contrib/{$name}/": ["type:drupal-module"],
      "sites/all/themes/contrib/{$name}/": ["type:drupal-theme"],
      "sites/all/libraries/{$name}/": ["type:drupal-library"],
      "sites/all/drush/{$name}/": ["type:drupal-drush"],
      "profiles/{$name}/": ["type:drupal-profile"]
    }
  }
}
```

My best guess would be that it's an incompatibility between the _non-destructive-archive-installer_ plugin and _composer-patches-plugin_ because the latter is not aware that the former changes the installation path of the package, but I'm not quite sure.

**Comment by derhasi** [comment]
I guess that is a problem of the _non-destructive-archive-installer_. Did you try the approach from https://github.com/drupal-composer/drupal-project/blob/7.x/composer.json using `drupal/drupal` form _Drupal Packagist_ and `derhasi/composer-preserve-paths`?

**Comment by yched** [comment]
Got bitten by this as well. 

As I wrote in #14, that is because netresearch/composer-patches-plugin tries to apply the patch from the web/core directory (since it's the installer-path defined for the drupal/core package by drupal-composer/drupal-project's composer.json), while they are typically rolled to be applied one directory up.

In short : netresearch/composer-patches-plugin doesn't work with drupal-composer/drupal-project for core patches :-)

**Comment by albertvolkman** [comment]
I haven't been able to upgrade to @cweagans' patch manager yet, so here's what I did-

```
            "drupal/drupal": [
              {
                "title": "Title",
                "url": "patch/the.patch",
                "args": "-p2"
              }
            ],
```

The "-p2" args was the trick.

**Comment by cweagans** [comment]
It doesn't take much to switch to my patches plugin, and patching core works out of the box. Might be worthwhile if anyone else runs into this problem.

**Comment by albertvolkman** [comment]
Unfortunately our current site is on PHP 5.3 :(

**Comment by cweagans** [comment]
You should **_really**_ fix that, but the main reason that my plugin requires 5.4 is that I don't test on anything lower than that. If you want, you can try the plugin on 5.3 and if it works, I'll lower the requirement in my repo for you.

**Comment by albertvolkman** [comment]
I appreciate the offer, but it won't be necessary. We have a new server build slated to go out in the next few weeks. Thanks @cweagans!

**Comment by webflo** [comment]
The composer patches plugin works great so far.
