### ISSUE TITLE
`buildScaffold` does not replace missing `web/core/assets` directory

### ISSUE THREAD

**Issue by mchelen** [drupal-composer/drupal-composer-project#150]
```
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction

cd some-dir

rm -r web/core/assets

composer up
```

This becomes an issue because the `.gitignore` causes `web/core/assets` not to be tracked, meaning a fresh checkout from git will be missing this directory even after `composer install`.

A workaround is to delete the `vendor` directory and then run `composer up`

**Comment by webflo** [comment]
Sorry i don't understand the issue. `web/core/assets` should be part of `drupal/core`.

**Comment by mchelen** [comment]
@webflo If you delete `web/core/assets` and then run `composer install` or `composer up` it doesn't trigger a reinstall of `drupal/core` so the `web/core/assets` directory will be still be missing.

**Comment by webflo** [comment]
Yeah, thats not the responsibility of the scaffold command. The scaffold puts some config files (.htaccess, autoload.php, default.settings.php, etc.) in the right place. The assets folder is part of the drupal/core package and managed by composer. composer install checks if the folder exists, thats it. You can restore the asset folder by deleting the web/core and run composer install.

**Comment by mchelen** [comment]
@webflo Right, the issue appears when working with git. Lets say you create a project with:
`composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`
Then check it into git:

```
cd some-dir
git init
git add .
git commit -m "first commit"
```

If someone else checks out this repo and does a `composer install` they will have a non-working site because the `web/core/assets` directory is missing.

**Comment by webflo** [comment]
Sorry, i can't follow. Composer should download `drupal/core`. `drupal/core` contains `assets`. see https://github.com/drupal-composer/drupal-core/tree/8.1.x/assets

**Comment by rodrigoaguilera** [comment]
When someone else checks out the project the should run `composer install`

**Comment by mchelen** [comment]
Oops, I was trying out both `drupal-composer/drupal-project` and `drupal/drupal` for creating a project, and it looks like I got them mixed up. This issue doesn't occur in `drupal-composer/drupal-project` sorry for the confusion!
