### ISSUE TITLE
WIndows

### ISSUE THREAD

**Issue by divined** [drupal-composer/drupal-composer-project#152]
[Remote\Rsync] Running rsync -a -v -z --no-group --no-owner --include "sites" --include "sites/default" --include "sites/default/default.settings.php" --include "sites/default/default.services.yml" --include "sites/development.services.yml" --include "sites/example.settings.local.php" --include "sites/example.sites.php" --exclude ".gitkeep" --exclude "autoload.php" --exclude "composer.json" --exclude "composer.lock" --exclude "core" --exclude "drush" --exclude "example.gitignore" --exclude "LICENSE.txt" --exclude "README.txt" --exclude "vendor" --exclude "themes" --exclude "profiles" --exclude "modules" --exclude "sites/_" --exclude "sites/default/_" "C:\OpenServer\cygwin64\tmp\drupal-scaffold-1464024156/drupal-8/" "C:\Users\Val_S\drupal\web"
The source and destination cannot both be remote.
rsync error: syntax or usage error (code 1) at main.c(1292) [Receiver=3.1.2]
 [Remote\Rsync]  Exit code 1  Time 0.204s
 [Robo\Result] Stopping on fail. Exiting....
 [Robo\Result] Exit Code: 1

**Comment by jameswilson** [comment]
I see you're using Cygwin.  

It's been many years since I've used Windows or Cygwin, but what happens if you specify paths using the alternate Cygdrive format? So instead of `"C:\Users\Val_S\..."`  you use `/cygdrive/c/Users/Val_s/...`

**Comment by divined** [comment]
It work. I temporary hardcoded scaffold module:

$tmpDirS = str_replace('C:', '/cygdrive/c', $tmpDir);
$tmpDirS = str_replace('\', '/', $tmpDirS);

And $webroot also.

**Comment by Jesmaster** [comment]
I use Git Bash on Windows 10 and I had to do a few special things to get a new project to be created correctly.

First of all this requires rsync to be installed as it is used in the composer scripts for drupal scaffolding.
By default Git Bash doesn't have rsync but I was able to install it by following this guide: https://alanbarber.com/2015/08/11/installing-rsync-on-windows/

The next step is to run the project creation script. It will eventually get to the part where it runs scripts and will crash when it tries to run the rsync command.  

I then went into the vendor/drupal-composer/drupal-scaffold/src/RoboFile.php file and added the lines 

```
$tmpDirS = str_replace('C:', '/c', $tmpDir);
$tmpDirS = str_replace('\\', '/', $tmpDirS);
$webrootS = str_replace('C:', '/c', $webroot);
$webrootS = str_replace('\\', '/', $webrootS);
```

Above the $this->taskRsync() line. (Note that if you use another windows bash shell you might need to do these replacements differently)

After that I modified the $this->taskRsync() call to pass in the modified variables. It should look like:

```
$this->taskRsync()
      ->fromPath("$tmpDirS/$fetchDirName/")
      ->toPath($webrootS)
      ->args('-a', '-v', '-z', '--no-group', '--no-owner')
      ->includeFilter($includes)
      ->exclude($excludes)
      ->run();
```

I then ran 

```
composer run-script drupal-scaffold
composer run-script post-install-cmd
```

in Git Bash to complete the installation

Hopefully this helps anyone trying to get this to run in windows.

**Comment by webflo** [comment]
Please use the Version 2 of drupal-composer/drupal-scaffold. It is much simpler and has no rsync dependency. https://github.com/drupal-composer/drupal-project/pull/154

**Comment by Jesmaster** [comment]
+1

I changed the drupal-scaffold version to 2.0.0 in composer.json and that version worked fine on Windows with no modifications needed.

**Comment by webflo** [comment]
@Jesmaster Thanks for the quick test. drupal-composer/drupal-scaffold v2 is the new default.
