### ISSUE TITLE
Failed to copy default.settings.php because file does not exist

### ISSUE THREAD

**Issue by nicrodgers** [drupal-composer/drupal-composer-project#153]
Steps to reproduce:
1. Run the create-project command as per the documentation:
   composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction

Actual result:

> Script DrupalProject\composer\ScriptHandler::createRequiredFiles handling the post-update-cmd event terminated with an exception  
>   [Symfony\Component\Filesystem\Exception\FileNotFoundException]  
>   Failed to copy "/Volumes/www/d8/some-dir/web/sites/default/default.settings  
>   .php" because file does not exist.            

Expected result:
No termination/exception

**Comment by nicrodgers** [comment]
I notice this error a few lines above:

> [FileSystem\CleanDir] Cleaned /private/var/folders/ly/4r5_6jhx1t37ybtnw4krqck00000gn/T/drupal-scaffold-1464170772
> ➜  Attempt to download https://ftp.drupal.org/files/projects/drupal-8.1.1.tar.gz to /private/var/folders/ly/4r5_6jhx1t37ybtnw4krqck00000gn/T/drupal-scaffold-1464170772/drupal-8.1.1.tar.gz
> ➜  
> ➜   Could not download https://ftp.drupal.org/files/projects/drupal-8.1.1.tar.gz 
> ➜  
>  [Archive\Extract] Extracting /private/var/folders/ly/4r5_6jhx1t37ybtnw4krqck00000gn/T/drupal-scaffold-1464170772/drupal-8.1.1.tar.gz
>  [Archive\Extract] /private/var/folders/ly/4r5_6jhx1t37ybtnw4krqck00000gn/T/drupal-scaffold-1464170772/drupal-8.1.1.tar.gz extracted

**Comment by webflo** [comment]
A few users report issues with the scaffolding-script. We build a simpler solution in https://github.com/drupal-composer/drupal-scaffold/pull/38

**Comment by webflo** [comment]
Please use drupal-composer/drupal-scaffold Version 2.

**Comment by nicrodgers** [comment]
Thanks. Might be a good idea to update the README, too?

**Comment by webflo** [comment]
v2 is the new default. https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L20

**Comment by itamair** [comment]
+1 ... still having the highlighted problems on this, on the actual release

**Comment by webflo** [comment]
The latest version does not use rsync anymore. Make sure you have the latest version of composer as well.

**Comment by itamair** [comment]
Yes thanks. The composer update seems solved the matter.
