### ISSUE TITLE
gitignore setting files

### ISSUE THREAD

**Issue by Jesmaster** [drupal-composer/drupal-composer-project#156]
Shouldn't the default gitignore also include 

web/sites/default/settings_.php
web/sites/default/services_.yml

**Comment by dsdeiz** [comment]
Also curious about this. I was wondering if maybe `drupal-scaffold` could include the `example.gitignore` file that comes d8.

**Comment by Jesmaster** [comment]
What I ended up doing was keeping those files in version control to store all settings that are on the site regardless of environment. I then used the settings.local.php file to store/override settings that are environment specific. The settings.local.php file is already included in the default gitignore so I think this workflow is fine.

**Comment by dsdeiz** [comment]
> The settings.local.php file is already included in the default gitignore so I think this workflow is fine.

Not sure. I'm not finding this in the recent changes. Not sure what I'm missing though. `git check-ignore web/sites/default/settings.local.php` returns nothing. Although the `example.gitignore` that came with d8 does ignore this.

**Comment by Jesmaster** [comment]
You're right, I just added it manually to the gitignore

**Comment by leymannx** [comment]
#178

**Comment by normanlolx** [comment]
Related issue #178 Ignore web/sites/*/settings.php

**Comment by madalinignisca** [comment]
I've checked and the current .gitignore is not allowing settings.local.php in any /sites/*/ to be added.

Only this get added by default:
```
	web/sites/default/default.services.yml
	web/sites/default/default.settings.php
	web/sites/development.services.yml
	web/sites/example.settings.local.php
	web/sites/example.sites.php
```
