### ISSUE TITLE
ScriptHandler is not autoloadable

### ISSUE THREAD

**Issue by dimmech** [drupal-composer/drupal-composer-project#157]
I get the following error when installing.

"Class DrupalProject\composer\ScriptHandler is not autoloadable, can not call post-install-cmd script".

Looking at json file it appears to be the wrong path to ScriptHandler.php located at DrupalProject\scripts\composer\ . However I am brand spankin new to composer so I could be wrong.

**Comment by webflo** [comment]
Please make sure that you use the latest of composer. Please verify it via `composer --version`

**Comment by dimmech** [comment]
I'm using Ubuntu 15.10 and originally installed composer using the built in package installer. When I ran composer --version I got the following msg:

`Composer version @package_branch_alias_version@ (@package_version@) @release_date@`

Which led me to these issues:
Ubuntu [bug report](https://bugs.launchpad.net/ubuntu/+source/composer/+bug/1530204)
Composer [Issue](https://github.com/composer/composer/issues/4725)

I uninstalled the package version and installed using

```
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer
```

Everything works fine now! Thanks!
