### ISSUE TITLE
Where to put custom modules and themes?

### ISSUE THREAD

**Issue by opdavies** [drupal-composer/drupal-composer-project#158]
Where should custom modules and themes be placed within this setup? I believe that earlier versions of this project had a `web` directory by default which had the standard structure.

I did try adding my own `web` directory with just my custom code in it, which seemed to work, but I wasn't sure if this was the correct approach or not.

**Comment by opdavies** [comment]
Or should they be kept in a separate repo and added as a requirement? I've done that approach before with Drush Make.

**Comment by derhasi** [comment]
You are supposed to put them in `web/modules/custom`. The `web/modules` directory should be created on `composer install`.
