### ISSUE TITLE
Fails with wikimedia/composer-merge-plugin

### ISSUE THREAD

**Issue by mickaelperrin** [drupal-composer/drupal-composer-project#163]
Hi,

I encounter a strange bug while using `wikimedia/composer-merge-plugin` in my composer.json file. 

Composer fails with the error:

```
  [merge-plugin] Already merged composer/drupal_common.json
> post-update-cmd: DrupalProject\composer\ScriptHandler::createRequiredFiles
Script DrupalProject\composer\ScriptHandler::createRequiredFiles handling the post-update-cmd event terminated with an exception


  [Symfony\Component\Filesystem\Exception\FileNotFoundException]
  Failed to copy "/src/web/sites/default/default.settings.php" because file does not exist.
```

It looks like `wikimedia/composer-merge-plugin` sends an `update` event which triggers `DrupalProject\composer\ScriptHandler::createRequiredFile` before `DrupalComposer\DrupalScaffold\Plugin::scaffold`.

I don't know if the `update` event is something expected after each merge of an additional `composer.json` files. But if yes, the `DrupalProject\composer\ScriptHandler::createRequiredFile` script should ensure that the scaffolding process ran correctly before trying to copy files.

Currently, I basically added something like in the createRequireFile :

```
if (!$fs->exists($root . '/sites/default/default.settings.php')) {
 \DrupalComposer\DrupalScaffold\Plugin::scaffold($event);
}
```

Did you already encounter  this bug ? Do you think, running the scaffolding process from the createRequireFile is a good way to resolve this ?

-- EDIT: Note that I don't use the `composer create-project` command but the `composer.json` file in a global scaffolding process through Yeoman.

**Comment by mickaelperrin** [comment]
In fact, just checking that files exists before trying to copy them is sufficient. See attached PR.

**Comment by mickaelperrin** [comment]
Note also, that the check should ensure that the `default.settings.php` and `default.settings.yml` files are not excluded in the composer configuration. But, currently the `getExcludes()` function is `protected`.

**Comment by Luukyb** [comment]
I am not sure if it's related to your problem, but I had the same error message, that default.settings.php was missing. And it was because drupal-scaffold did not run properly when composer install.
Runing the command manually for drupal-scaffold fixed it for me:
`composer run-script drupal-scaffold`

**Comment by webflo** [comment]
@Luukyb Which version of composer to you use?

**Comment by Luukyb** [comment]
@webflo Composer version 1.1.2, btw thanks for all your work on this project!
