### ISSUE TITLE
Remove replace workaround

### ISSUE THREAD

**Issue by derhasi** [drupal-composer/drupal-composer-project#17]
``` json
{
  "type": "composer",
  "url": "https://raw.githubusercontent.com/webflo/d8/master/packages.json"
},
```

Once the following issues are resolved we could remove that:
- https://www.drupal.org/node/2468499
- https://www.drupal.org/node/2456009

**Comment by webflo** [comment]
https://www.drupal.org/node/2456009 was committed today. I think we postpone this task until the next beta is out, because we install beta releases by default.
