### ISSUE TITLE
Clarify why `drupal/core` is the preferred approach

### ISSUE THREAD

**Issue by jhedstrom** [drupal-composer/drupal-composer-project#172]
In some manual testing of https://github.com/phase2/grunt-drupal-tasks/pull/293, I was accidentally using `drupal/drupal`, which actually worked as expected (in that it ended up in the right place, etc). Given that, I'm wondering why the `drupal/core` approach is preferred (since it then also requires `drupal-composer/drupal-scaffold`).

It would be nice to document this (apologies if it is already documented and I've overlooked it).

**Comment by fafnirical** [comment]
[drupal-composer/drupal-core's README](https://github.com/drupal-composer/drupal-core/blob/master/README.md) lists some advantages, but that document might be a bit outdated at this point (last update was in February 2015).

**Comment by webflo** [comment]
[drupal-composer/drupal-core's README](https://github.com/drupal-composer/drupal-core/blob/master/README.md) is still valid. But the list goes on:
- It is hard to install composer packages inside of other packages. Modules have to go under /modules. But /modules is part of drupal/drupal.
- Enhanced security, moving the autoloader above the web root

**Comment by jhedstrom** [comment]
Thanks @fafnirical and @webflo. I realized after thinking about it that the tests where `drupal/drupal` _appeared_ to work weren't complete. The autoloader was not re-written to utilize packages that were downloaded to the vendor outside of the web root.
