### ISSUE TITLE
Install older version

### ISSUE THREAD

**Issue by geek-andi** [drupal-composer/drupal-composer-project#173]
I tried to install drupal 8.0.6 but get this error: 

>   Could not find package drupal-composer/drupal-project with version 8.0.x-dev.

I tried it with:
`composer create-project drupal-composer/drupal-project:8.0.x-dev folder`
How can I install an older drual 8.0.x version?

**Comment by webflo** [comment]
Just clone the project and adjust the drupal/core version constraint in composer.json.

**Comment by geek-andi** [comment]
thanks!

**Comment by gitressa** [comment]
Thanks for the info @webflo. With these commands I got the older version `8.7.4` for testing the [Automatic Updates](https://www.drupal.org/project/automatic_updates) module:
```
git clone git@github.com:drupal-composer/drupal-project
cd drupal-project/
sed -i 's|\^8.7.0|8.7.4|g' composer.json

```
