### ISSUE TITLE
support for cmd-line installer support of Drupal.org beta repos, instead of packagist

### ISSUE THREAD

**Issue by ghost** [drupal-composer/drupal-composer-project#175]
drupal.org's repos are available in beta as a replacement for drupal.packagist

`https://www.drupal.org/node/2718229
`

> "Beta - Drupal.org's composer repositories are in Beta. We encourage you to begin transitioning your composer based workflows to use Drupal.org's composer facade."

Current drupal-composer/drupal-project 's composer.json is packagist specific.

At best, a drupal-site composer install uses packagist, and repo can be switched in composer.json AFTER the install.

It'd be useful to testing to have an alternative composer.json that uses the drupal.org repos exclusively, and can be selected on the install command line.

**Comment by ryanaslett** [comment]
Im pretty sure you mean 'drupal-packagist' specific, and not packagist specific. (packagist by itself generally refers packagist.org, not packagist.drupal-composer.org)

**Comment by webflo** [comment]
The default composer.json is not specific to Drupal-Packagist. It is only the url, everything else should work fine

**Comment by ryanaslett** [comment]
I think they're just trying to ask that https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L15  gets changed to http://packages.drupal.org/8

**Comment by ghost** [comment]
Okay, so currently

```
composer create-project --keep-vcs --stability dev drupal-composer/drupal-project:8.x-dev d8
```

seems to exec a procedure that downloads from

```
https://packagist.drupal-composer.org/...
```

Can that "only the URL" be selected from the command line?  I.e., optionally instructed to use the drupal.org URLs instead?

**Comment by webflo** [comment]
`--no-install` is a good start to speed things up.

`composer create-project --keep-vcs --stability dev --no-install drupal-composer/drupal-project:8.x-dev d8`

**Comment by webflo** [comment]
I think its not configurable via composer from cli only, but a simple php script should do it.

**Comment by webflo** [comment]
https://github.com/drupal-composer/drupal-project/pull/159 is related.

**Comment by ghost** [comment]
> I think its not configurable via composer from cli only, but a simple php script should do it.

Also I read

> When using Drupal Packagist - the semver shim format was: Platform(D7/D8).Major.Minor. So for example, the following code required Views 7.x 3.13 through Drupal Packagist:
> 
> {
>     "require": {
>         "drupal/views": "7.3.13"
>     }
> }
> 
> When using the official Drupal.org Composer Service, the Platform part of the version is already defined by whether you are using the Drupal 7 or Drupal 8 endpoint, therefore the rest of the translated format is as follows: Major.Minor.0

So it seems like more than just the command line is needed, like you say

> #159 is related.

Read it.  Is there a separate branch already usable?  I see only the 8.x & 7.x ...

Is it that it's just not ready for use yet?

**Comment by webflo** [comment]
Ahh you are looking for a script, that converts all version constraints in your existing composer.json?

**Comment by ryanaslett** [comment]
I think theres two, separate things getting confused here. One is how to _convert_ an existing drupal-project to use packages.drupal.org - the other is how to _create_ a new project using `composer create-project`, and have that use packages.drupal.org.

**Comment by ghost** [comment]
I'm "looking for" a cmd-line equivalent to the usual install cmd, that uses only drupal.org repos.

The idea being to install this project (drupal-composer/drupal-project) scaffold, but end up using only drupal.org -- so we can start testing those repos and providing the requested feedback there, as well as here in anticipation of the drupal-packagist repos going away.

**Comment by ghost** [comment]
> create a new project using composer create-project, and have that use packages.drupal.org

that^^ is my goal here

**Comment by ryanaslett** [comment]
Right now, the steps are 
`composer create-project --keep-vcs --stability dev drupal-composer/drupal-project:8.x-dev d8`
Then, edit the resulting composer.json file to point to packages.drupal.org/8.

The fix to eliminate the editing step is #159 .

**Comment by ghost** [comment]
Here's what I do

Do the 'no install' create-project

```
composer -vvv create-project --stability dev --no-interaction --no-install drupal-composer/drupal-project:8.x-dev d8
```

then edit the resulting composer.json

```
cd d8
perl -pi -e 's|"conflict":|"replace":|g' composer.json
composer config --unset repo.0
composer config repo.drupal composer https://packages.drupal.org/8
grep repositories composer.json -A5
    "repositories": {
        "drupal": {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    },
composer clear-cache
```

Now I'd expect to use only drupal.org repos, right?  No more *packagist repos?

Try this

```
composer -vvv update
```

and you see that's not the case.  It starts off using the drupal.org repos

```
Reading ./composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file ./composer.json
Executing command (/home/myProj/d8): git branch --no-color --no-abbrev -v
Executing command (/home/myProj/d8): git describe --exact-match --tags
Reading /root/.composer/composer.json
Loading config file /root/.composer/config.json
Loading config file /root/.composer/auth.json
Loading config file /root/.composer/composer.json
Loading config file /root/.composer/auth.json
Reading /root/.composer/vendor/composer/installed.json
Running 1.1.3 (2016-06-26 15:42:08) with PHP 7.0.10-dev on Linux / 4.6.3-1.gd4bcf2a-default
Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
> pre-update-cmd: DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Downloading https://packages.drupal.org/8/packages.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/packages.json into cache
```

then starts up with packagist again

```
Downloading https://packagist.org/packages.json
Writing /root/.composer/cache/repo/https---packagist.org/packages.json into cache
```

and after a bit of only drupal.org

```
Updating dependencies (including require-dev)
Downloading https://packages.drupal.org/8/drupal/provider-2016-2%2434333da94873d888f4b2495ce0728960643dadd604f640f0b1d70951a94eb6ba.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-2.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2016-1%24561a89fd882a5e37f7c03513f8c93a150332c266e9d88aa2ae1ba07244fccd90.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2016-1.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2015-4%245a33655bf2cefcbaf5802223b834678f40818e25ff9facda7f740357aaac241a.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-4.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2015-3%24f4443e4989f45814be46726ceac74f658f72b34b9b25a3c6e4907c8562016be6.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-3.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2015-2%24a9501aeb417f347627b8d7d7787ecae4212239bd8c8ed58d3100cddc301a6cb1.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-2.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2015-1%24fcf4cc5c0890c706467f6d93b1c69e253494a800301db49332489fb84c5afe60.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2015-1.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2014-4%24424910976792ce97c5770175d2d6dc53691313e68d320836b0d4c89b43938b36.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-4.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2014-3%24c7614e2c910efa62d94e0952fde719d21b80dff44154d2a3e0ebbd621213cd9d.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-3.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2014-2%24474872f7a8802291f8e4902bc2d16d23b45d6f7601faa55d9c6d5a24d2b87bea.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-2.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2014-1%24d407b6d560f68c2712153eb2c65733b3016e798b25b1c729ea3be8517036776c.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2014-1.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2013-4%24735c65b96d0fad144bbeea30655d65d53c05a9f5257a8023d0cc71e9c970c8f5.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-4.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2013-3%24c5a7c2c021b4ee305a54709a56e13a352ae6e03c4c1126e3fea338aebe3f6ca2.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-3.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2013-2%2431999dfe1f85dd5b75c8a6299e64c83f17e34965a6e0ec942701b728700db9a3.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-2.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2013-1%24cb7a70174372317443930b41725f90d39b2e50a5a0fd7960b34e9fb9eb51f63e.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2013-1.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2012-4%24e71b1c31e82b7275d90af922e561d1fde53759cfad0c3b96a030efc626837c51.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-4.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2012-3%24e0e21f9746f72e3b129f6db0c7a4ed56ebd3013191fcc05d14309d6b22ef1627.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-3.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2012-2%24beefe46d57d3ba4013f4d77b35f5d224f1d52a4758453a9f63b93239791b340f.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-2.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2012-1%24e0ab27cc661e9a1efe462e0c46224817f383d2d6e840bc5af4bbbdb4ff58d65d.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2012-1.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2011-4%247b4cbd6e2ec1724cefde42cb1f54dea6d0c5f3296c03403a3344ad67411894a6.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-4.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2011-3%2492db14769d8dd7a4bb174dc330286bfbfffe4e84949c4241d937f80364090879.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-3.json into cache
Downloading https://packages.drupal.org/8/drupal/provider-2011-2%24caa1bc44311a54b17d74d9966b1c4c95660148802844ea5462116baa9c4222d8.json
Writing /root/.composer/cache/repo/https---packages.drupal.org-8/drupal-provider-2011-2.json into cache
```

switches back to packagist

```
Downloading http://packagist.org/p/provider-2013%24aff1432148b18758e9fb73b19dc179a3d1cd221ffc6f1d6c19e4db1cb2a379cb.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2013.json into cache
Downloading http://packagist.org/p/provider-2014%24cf9cd320b5827334567cfc6a8513a8188002bc55921289971916343e19b19bc8.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2014.json into cache
Downloading http://packagist.org/p/provider-2015%24868fabb8f22f4f7149664ada19c25f6e6454a922d7c49926e1d26a4899d18968.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2015.json into cache
Downloading http://packagist.org/p/provider-2015-10%246710817f52e06ac3509f460e17f906825c5a2715f7990d9b2852b5220fd53002.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json into cache
Downloading http://packagist.org/p/provider-2016-01%243b09fc6dcd26ffbe609c037a3ad5221c336a4b5db59c92f076b9d965c1a39e94.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2016-01.json into cache
Downloading http://packagist.org/p/provider-2016-04%24299d165ccef32da5d1ced4bb4e7f36b6a5c9a6ceed109614efac00e744d79db5.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2016-04.json into cache
Downloading http://packagist.org/p/provider-2016-07%24817df9359fdbc9f44e4d65df014d8a90c9c3a0c54de1e6ebcb85d5129ef3920b.json
Writing /root/.composer/cache/repo/https---packagist.org/p-provider-2016-07.json into cache
Downloading http://packagist.org/p/provider-archived%249c80eab8f9d5e6a99f91e753e021b97df8bfa9f29299bc0bdafa46fe9221eb57.json
```

and continues from there

**Comment by ryanaslett** [comment]
#161 was an alternate way to add a command line method for changing the repositories, so that you could `composer create-project --keep-vcs --stability dev drupal-composer/drupal-project:8.x-dev d8` and then `composer config repositories.drupal composer https://packages.drupal.org/8` -> but since the current repo doesnt have a key, it gets assigned a key of 0.

For kicks I tried: `composer config repositories.0 composer https://packages.drupal.org/8` and it actually worked as expected.

**Comment by ryanaslett** [comment]
It is supposed to use the packagist.org repos.

There are three composer repositories, `packagist.drupal-composer.org`, and its replacement `packages.drupal.org/8`, and the original `packagist.org`.  `packages.drupal.org` only covers the metadata for drupal modules and themes.  All of the other dependencies of drupal core or contrib are hosted at `packagist.org`, so, thats exactly how its supposed to work.

**Comment by ghost** [comment]
what about the 'need' to exchange the "conflict" tag with a "replace" ?

**Comment by ryanaslett** [comment]
I erred when I said that, that actually isnt a need. It used to be but I forgot that I had already fixed that, because modules on packages.drupal.org/8 used to have drupal/drupal as a dependency, but now they rely on drupal/core. so, you can ignore that.  (also why webflo is saying we probably dont need to change it in https://github.com/drupal-composer/drupal-project/pull/159#issuecomment-232159891)

**Comment by ghost** [comment]
ok, great so it looks like this is the current 'simple' composer-install, that'll use drupal.org's repos

```
composer create-project --stability dev --no-interaction --no-install drupal-composer/drupal-project:8.x-dev d8
cd d8
composer config repositories.0 composer https://packages.drupal.org/8
composer clear-cache
composer update
```

**Comment by webflo** [comment]
I think we are past this phase, packages.drupal.org/8 is the new default. https://github.com/drupal-composer/drupal-project/commit/49184d678ff0de7f0cda0b597a7b170c6e5261e6#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780
