### ISSUE TITLE
Add option to move "core" directory above of web root.

### ISSUE THREAD

**Issue by stevector** [drupal-composer/drupal-composer-project#176]
Today's Drupal contrib security fixes reminded me of the inherent danger in keeping PHP files within the docroot. https://twitter.com/drupalsecurity/status/753263548458004480 This project already makes a big improvement by moving the vendor directory above the docroot. The modules, themes, profiles and even core could eventually be moved as well.

There is an old issue on Drupal.org on the topic: https://www.drupal.org/node/1672986 Without movement in that issue, not much can be done here but I at least wanted to open this issue here to gauge interest.

**Comment by fago** [comment]
Klausi documented a way of doing that, see https://www.drupal.org/node/2767907 and https://twitter.com/_klausi_/status/754740752295616513. Would be great if the composer setup could handle this by default?

**Comment by webflo** [comment]
👍 I think we can do it as a composer script.

**Comment by webflo** [comment]
Please review https://github.com/drupal-composer/drupal-project/pull/180.

**Comment by michaellenahan** [comment]
I want to review #180, but I would like to check I'm doing it the right way.

```
git clone git@github.com:webflo/drupal-project.git my-project
cd my-project
git checkout paranoia-mode
composer install
```
This seems to work - I get an ```app``` directory and the ```web``` directory has no php files - but I would like to check if that's the recommended way to test this PR. Thanks!

**Comment by webflo** [comment]
Yeah this is correct. I am currently rewriting it as a composer plugin to provide its as additional command.

**Comment by webflo** [comment]
Actually i am not sure if we should write it a full-blown composer plugin because, we have drush or console could act as task runner since they require a local installation anyway.

**Comment by michaellenahan** [comment]
(irrelevant question deleted)

**Comment by jkribeiro** [comment]
Please, see https://github.com/drupal-composer/drupal-project/pull/180#issuecomment-347977101

**Comment by jkribeiro** [comment]
I've created an experimental Composer plugin based on the PR https://github.com/drupal-composer/drupal-project/pull/335

https://github.com/jkribeiro/drupal-composer-paranoia

I think withe a Composer Plugin we can decouple the functionality from `drupal-project` turning the "paranoia mode" optional.
 
We can move the Plugin to `drupal-composer` org if necessary.

**Comment by normanlolx** [comment]
Seems https://github.com/drupal-composer/drupal-paranoia fixed it.
