### ISSUE TITLE
Update with dependencies

### ISSUE THREAD

**Issue by morenstrat** [drupal-composer/drupal-composer-project#179]
After updating from drupal-8.1.6 to 8.1.7 today by running `composer update drupal/core`, I noticed that guzzlehttp/guzzle was not updated to version 6.2.1. After running `composer update drupal/core --with-dependencies` guzzle was updated. Shouldn't this be the default?

**Comment by webflo** [comment]
I think we can't configure the default behavior of composer.

**Comment by morenstrat** [comment]
Okay, but shouldn't README.md then recommend updating Drupal `--with-dependencies`? If I understand the latest Drupal update correctly, the security issue was in guzzle, and not in Drupal itself. Upgrading Drupal without updating third party libraries can make users wrongly think they fixed the issue while they haven't...

**Comment by webflo** [comment]
Yes, please submit a PR. Thanks!

Markus Orenstrat notifications@github.com schrieb am Di., 19. Juli 2016,
00:32:

**Comment by morenstrat** [comment]
Here's the PR: #181

**Comment by webflo** [comment]
Thanks! 👍
