### ISSUE TITLE
drupal library dependency package in module

### ISSUE THREAD

**Issue by joville** [drupal-composer/drupal-composer-project#182]
I was trying to install the shariff module via composer and got errors because of the needed library package.

I could resolve this by adding drupal-library path to the extra in composer.json. does this make sense to be added there?

**Comment by webflo** [comment]
Yes, please submit a pull request. Thanks!

**Comment by joville** [comment]
Is already there, as I found it after by a hint from @criz: https://github.com/drupal-composer/drupal-project/pull/113/commits/f17f11240963259b27a4f5029e9d03e91f2f56bd

**Comment by webflo** [comment]
Alright, i added `web/libraries` as default.
