### ISSUE TITLE
PHP Parse error: unexpected '[' 

### ISSUE THREAD

**Issue by haxxxton** [drupal-composer/drupal-composer-project#187]
just tried to run `composer create-project drupal-composer/drupal-project --stability dev`

received the following log messages with errors:

```
Installing drupal-composer/drupal-project (8.x-dev 1b0065990c8c3e9a828f848eb90368131e9f0462)
  - Installing drupal-composer/drupal-project (8.x-dev 1b00659)
    Cloning 1b0065990c8c3e9a828f848eb90368131e9f0462 from cache

Created project in /path/to/site/drupal-project
PHP Parse error:  syntax error, unexpected '[' in /path/to/site/drupal-project/scripts/composer/ScriptHandler.php on line 24

Parse error: syntax error, unexpected '[' in /path/to/site/drupal-project/scripts/composer/ScriptHandler.php on line 24
```

have i done something wrong/pulled the wrong version or something?

**Comment by haxxxton** [comment]
solved using the following steps:

Using MAMP, so update environment settings to use MAMP's PHP bin files
http://stackoverflow.com/a/10653443/648350

Install drush as root
http://drupal.stackexchange.com/questions/201060/does-drush-need-to-be-installed-as-root

and its solution of running `drush core-status` from outside the install directory
http://drupal.stackexchange.com/a/201094

**Comment by haxxxton** [comment]
misclicked, apologies

**Comment by kgaut** [comment]
For those who get this kind of issue, it's time to upgrade to your PHP version ;) 

Drupal 8 require at least php 5.4

**Comment by webflo** [comment]
D8 requires 5.5.9+ https://www.drupal.org/docs/7/system-requirements/php#8
