### ISSUE TITLE
How to update a single module ?

### ISSUE THREAD

**Issue by albabosh** [drupal-composer/drupal-composer-project#188]
Can anyone tell me how to update a single module using composer ?

**Comment by fafnirical** [comment]
``` sh
composer update drupal/<module_name> --with-dependencies
```

For example, to update Search API (`search_api`):

``` sh
composer update drupal/search_api --with-dependencies
```

(Note that the `--with-dependencies` flag will also update the module's own dependencies, if it has any.)

**Comment by webflo** [comment]
The answer from @fafnirical is correct. Thanks!

**Comment by maxplus** [comment]
thanks!
