### ISSUE TITLE
Failed to detect composer version properly

### ISSUE THREAD

**Issue by rodrigoaguilera** [drupal-composer/drupal-composer-project#189]
I'm using the following composer version
Composer version 1.2-dev (f3af3ede40b42a7b8002b0b135c84b8135f4aa6d) 2016-08-29 17:38:18

I tried to do a "composer install" and I get the following error.

DrupalProject\composer\ScriptHandler::checkComposerVersion\nDrupal-project requires Composer version 1.0.0 or higher. Please update your Composer before continuing.

Changing composer to the 1.2 version solves the problem but I think there is a problem with the version checking

I did a quick PR on semver to check if the problem was there but the tests pass.

https://github.com/composer/semver/pull/44

I don't know what should be checked differently on this project to be able to use a development version of composer.

**Comment by webflo** [comment]
Could you paste the output of "composer --version" here? Thanks!

**Comment by rodrigoaguilera** [comment]
Is in my first post:
Composer version 1.2-dev (f3af3ede40b42a7b8002b0b135c84b8135f4aa6d) 2016-08-29 17:38:18

**Comment by alcohol** [comment]
The following branch in the code is unsafe:

``` php
if ($version === '@package_version@') {
```

The above is used to determine if a user is running a development version of Composer.

This is a false assumption though, because this only applies when running Composer from source. In binary (phar) development releases, `Composer::version` contains the commit SHA that the development version is based on.

**Comment by webflo** [comment]
Should we use Composer::BRANCH_ALIAS_VERSION instead?

**Comment by alcohol** [comment]
Depends. What do you want to achieve?

**Comment by alcohol** [comment]
How about..

``` php
public static function checkComposerVersion(Event $event) {
  $composer = $event->getComposer();
  $io = $event->getIO();
  $version = $composer::VERSION;

  if (self::isSourceVersion($version)) {
    // warning about using composer from source  
  } elseif (self::isDevelopmentVersion($version)) {
    // warning about keeping dev version up to date
  } elseif (Comparator::lessThan($version, '1.0.0'))
    // warning/error about incompatible version
  }
}

private static function isSourceVersion($version) {
  return $version === '@package_version@';
}

private static function isDevelopmentVersion($version) {
  return preg_match('{[a-z0-9]{40}}i', $version);
}
```

**Comment by webflo** [comment]
Thanks for your help @alcohol

**Comment by alcohol** [comment]
You're welcome.

**Comment by nigelwhite** [comment]
I'm getting the same issue. Composer can't see it already has the latest version. Won't allow composer install as it thinks it has an old version.

When I do $ composer install I get "Drupal-project requires Composer version 1.0.0 or higher. Please update your Composer before continuing." When I do $ sudo -H composer self-update I get "You are already using composer version 1.6.3 (stable channel)."

I am on a remote server, using a set of Drupal 8 stuff cloned there from a Github repo using $sudo git clone --branch master https://github.com/........git newsite_dev. The Github repo was pushed from a local install using composer create-project.

The remote is using LAMP with Ubuntu 16.04.

Seems like composer (at least as it operates inside of the D8 site config folder) cannot see that composer is already the latest version.

**Comment by jeromewiley** [comment]
Subscribe. Happening to me also.

**Comment by webflo** [comment]
@jeromewiley @nigelwhite whats the output of ```composer --version```? Thanks!

**Comment by nigelwhite** [comment]
composer --version gives Composer version 1.6.3 2018-01-31 16:28:17
which composer gives /usr/local/bin/composer
However, I've just tried it again (24 hrs later) and the problem has sorted itself! Sudo composer install ran OK.
Thanks @webflo
