### ISSUE TITLE
Why is require-dev present when  you could use the merge plugin?

### ISSUE THREAD

**Issue by pwolanin** [drupal-composer/drupal-composer-project#191]
Since Drupal core already requires the wikimedia composer merge plugin, why not require it in the top level composer.json file here and rely on the Drupal core dev dependencies being merged in instead of listing them again?

**Comment by webflo** [comment]
[drupal/core](https://packagist.org/packages/drupal/core) (the subtree split) does not have a dependency on the merge plugin. Composer does not require dev dependencies of dependencies. Require dev is a root only property.

Maybe we could build a "drupal dev tools" metapackage from our core repo.

**Comment by pwolanin** [comment]
So, testing locally, it seems as though using the merge plugin and requiring the core composer.json gets you the core dev packages.

Here's my diff:

```
diff --git a/composer.json b/composer.json
index 0d1f3a5..0d706d6 100644
--- a/composer.json
+++ b/composer.json
@@ -16,6 +16,7 @@
         }
     ],
     "require": {
+        "wikimedia/composer-merge-plugin": "~1.3",
         "composer/installers": "^1.0.20",
         "drupal-composer/drupal-scaffold": "^2.0.1",
         "cweagans/composer-patches": "~1.0",
@@ -24,13 +25,6 @@
         "drupal/console": "~1.0"
     },
     "require-dev": {
-        "behat/mink": "~1.7",
-        "behat/mink-goutte-driver": "~1.2",
-        "jcalderonzumba/gastonjs": "~1.0.2",
-        "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
-        "mikey179/vfsStream": "~1.2",
-        "phpunit/phpunit": "~4.8",
-        "symfony/css-selector": "~2.8"
     },
     "conflict": {
         "drupal/drupal": "*"
@@ -65,6 +59,10 @@
             "web/profiles/contrib/{$name}": ["type:drupal-profile"],
             "web/themes/contrib/{$name}": ["type:drupal-theme"],
             "drush/contrib/{$name}": ["type:drupal-drush"]
+        },
+        "merge-plugin": {
+            "include": [ "web/core/composer.json" ],
+            "recurse": false
         }
     }
 }
```

**Comment by rodrigoaguilera** [comment]
I think is worth it to give this a try.

Right now the dev-dependencies from core are out of sync with this project

**Comment by jlholmes** [comment]
Found this issue while looking for a reason that phpcs was not installed when it is listed as a drupal/core dependency since v 8.3. Do I also need to run composer update using the composer.json file provided by drupal/core? Is this what others using this project do to keep drupal/core up to date? At the very least, consider merging with the drupal/core composer.json.

**Comment by webflo** [comment]
I had some issue with the merge-plugin in the past. I build a new package for the dev dependencies similar to drupal-core-strict. 

Merged in https://github.com/drupal-composer/drupal-project/pull/348
