### ISSUE TITLE
How to run PHPunit tests 

### ISSUE THREAD

**Issue by amitaibu** [drupal-composer/drupal-composer-project#193]
I try to run from the root `./vendor/phpunit/phpunit/phpunit -c phpunit.xml.dist ./web/modules/custom` however I get a `PHP Fatal error:  Class 'Drupal\Tests\BrowserTestBase' not found` error (even-though it's properly declared).

I tried to execute it also from inside the `web`, but it doesn't work. What is the proper way to run those tests, so I could also add it to Travis?

**Comment by webflo** [comment]
`./vendor/bin/phpunit -c ./web/core ./web/modules/contrib/` should work. `phpunit.xml.dist` is to test the project template itself. Not Drupal core and modules.

**Comment by webflo** [comment]
Related issue https://github.com/drupal-composer/drupal-project/issues/123

**Comment by webflo** [comment]
`./vendor/bin/phpunit -c ./web/core ./web/modules/custom/` for custom modules.

**Comment by amitaibu** [comment]
oh yeah, I tried with that one as-well. I've probably done something wrong, I'll re-check. Closing for now. Thanks :)

**Comment by amitaibu** [comment]
Great, it's working

**Comment by ansergeyg** [comment]
Sorry to raise this issue again. But, to me, having phpunit.xml.dist in template folder is still confusing. May be there should be some comments on how to run phpunit tests and on what level? Or renaming the file would work probably. But by default no one will specify the configuration file which will be exactly the template level phpunit.xml file.

**Comment by poojasharma48** [comment]
I was also facing similar issue:

 Uncaught Error: Class "Drupal\Tests\BrowserTestBase" not found in /var/www/html/web/modules/contrib/metatag/metatag_views/tests/src/Functional/MetatagViewsTokenTest.php:13

when I start debugging I checked BrowserTestBase class already exist

**Earlier the command I followed:** 

 ../vendor/bin/phpunit modules/contrib/metatag/metatag_views/tests/src/Functional/MetatagViewsTokenTest.php


**Right command**: Solution (work for me)

../vendor/bin/phpunit -c core modules/contrib/metatag/metatag_views/tests/src/Functional/MetatagViewsTokenTest.php


**Steps: So I go to the right folder like:** 

cd web 

../vendor/bin/phpunit -c core modules/contrib/metatag/metatag_views/tests/src/Functional/MetatagViewsTokenTest.php

you can clearly see added parameter **-c core**  in the above command

Where the param -c points to the localization of the phpunit.xml file , so in my scenario it exist inside core fiolder
