### ISSUE TITLE
Could not delete web/core

### ISSUE THREAD

**Issue by ksicon** [drupal-composer/drupal-composer-project#197]
I tried several times to install Drupal with drupal-project in an empty directory:
`composer create-project drupal-composer/drupal-project:8.x-dev /var/www/drupal --stability dev --no-interaction`

The installation process started to install all the dependencies and stopped during installation of drupal/core:

```
- Installing drupal/core (8.2.0-rc2)
    Loading from cache
    Failed to download drupal/core from dist: Could not delete web/core: 
    Now trying to download from source
  - Installing drupal/core (8.2.0-rc2)
    Cloning 75804aa9c14dd96a5b2ab6a8cf9cf616d8ac828c                               
  [RuntimeException]           
  Could not delete web/core: 
```

In subdirectory web/code we find a download-file for core:
-rw-rw-r-- 1 vagrant www-data  16M Sep 24 12:30 .fuse_hidden00036aeb00000045

What ist the reason? And how can it be changed?

**Comment by webflo** [comment]
Do you have any open processes? Which uses the folder? Maybe an open Finder/File explorer? I never had the issue, a quick google search lead me to http://askubuntu.com/questions/493198/what-is-a-fuse-hidden-file-and-why-do-they-exist

**Comment by ksicon** [comment]
Thanks for you answer. I had only one other open process, a terminal window. Before starting the installation I deleted web directory completely.
The fuse file's content is (part of) Drupal core as far as I can see.

**Comment by ksicon** [comment]
There was some progress:

One reason seems to have been a timeout (but it doesn't explain to me why an error "couldn't delete web/core could occur) . Setting Composer timeout to 6000 helped.

But project initialization still wasn't posiible. Now I get this error:

```
The website encountered an unexpected error. Please try again later.
Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "access_check.db_update". in Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (line 819 of vendor/symfony/dependency-injection/ContainerBuilder.php).
```

**Comment by rukayaj** [comment]
I have the same error ksicon, if you managed to get round it please post what you did, if you still remember. I'm using IIS and I'm wondering if that has something to do with it. Thanks.

**Comment by MrPaulDriver** [comment]
I am having very similar problems.

- Installing drupal/core (8.4.5): Loading from cache
    Failed to download drupal/core from dist: Could not delete web/core/.nfs00000000006a2f5200000003:
    Now trying to download from source
  - Installing drupal/core (8.4.5):

  [RuntimeException]
  Could not delete web/core/.nfs00000000006a2f5200000003:

**Comment by ericchew87** [comment]
I kept getting 'could not delete web/core' when doing composer install. I had my project open in phpStorm and in Windows File Explorer.  I closed both of those programs, restarted windows explorer (via task manager), and tried again.  It worked.  Just posting in case it helps someone else who is using Windows.

**Comment by flyke** [comment]
I had the same issue. Setting the composer timeout did the trick for me:
`composer config --global process-timeout 6000`
after that, my ` composer install` finished without problem.

**Comment by dakruchko** [comment]
> I had the same issue. Setting the composer timeout did the trick for me:
> `composer config --global process-timeout 6000`
> after that, my ` composer install` finished without problem.

worked for me as well!

**Comment by Prabuela** [comment]
This may be a permission problem. I have fixed with the permission **sudo chmod -R 777 web/core**
