### ISSUE TITLE
Drush does not work invoking the local Drush (D8 Composer Installation)

### ISSUE THREAD

**Issue by ArtuGit** [drupal-composer/drupal-composer-project#201]
Hello.

I have installed new D8 on a remote server using this way https://github.com/drupal-composer/drupal-project .
I have pulled files from GitHub and I have run 'composer install' for getting the all vendor files include the local Drush (/vendor/drush/drush/)
When I run 'drush status' or 'drush core-status' on the root (or '/web') website directory I have:

```
vagrant@drupalvm8:/var/www/drupalvm/test8$ drush core-status
PHP Warning:  pcntl_exec(): Error has occurred: (errno 8) Exec format error in /usr/local/share/drush/includes/startup.inc on line 412

Warning: pcntl_exec(): Error has occurred: (errno 8) Exec format error in /usr/local/share/drush/includes/startup.inc on line 412
Error has occurred executing the Drush script found at /var/www/drupalvm/test8/vendor/bin/drush.launcher
(errno 8) Exec format error
```

**Comment by webflo** [comment]
What happens if you invoke drush directly? `../vendor/bin/drush core-status`

**Comment by ArtuGit** [comment]
It was some my error. The problem disappeared after repeating: 
'
git pull
composer install
'
from scratch.
