### ISSUE TITLE
Error when trying to patch core

### ISSUE THREAD

**Issue by amitaibu** [drupal-composer/drupal-composer-project#205]
I have added a drupal-core patch under the `extra`

``` json
  "extra": {
        "installer-paths": {
            "web/core": [
                "type:drupal-core"
            ],
            "web/libraries/{$name}": [
                "type:drupal-library"
            ],
            "web/modules/contrib/{$name}": [
                "type:drupal-module"
            ],
            "web/profiles/contrib/{$name}": [
                "type:drupal-profile"
            ],
            "web/themes/contrib/{$name}": [
                "type:drupal-theme"
            ],
            "drush/contrib/{$name}": [
                "type:drupal-drush"
            ]
        },
        "patches": {
            "drupal/core": {
                "2637690": "https://www.drupal.org/files/issues/users_doesn_t_define-2637690-2.patch"
            }
        }
    }
```

However upon `composer install` I get:

![idealist-d8_ _amitai_amitais-macbook-pro_ _zsh_ _118x28](https://cloud.githubusercontent.com/assets/125707/19247552/66b60442-8f34-11e6-8f01-ab83d194dfa0.jpg)

Should core patches be declared differently?

**Comment by amitaibu** [comment]
hmm ,running this for the second time seems to work. I'll close for now, and open if I'm able to reproduce.

**Comment by amitaibu** [comment]
I see the error repeat on Travis.

**Comment by webflo** [comment]
The two error messages are expected, because the composer patches plugin tries multiple paths for the patch (-p0, -p1, and -p2). drupal/core contains only the core path and patches from d.o would not apply otherwise. The last patch command (git apply -p2) succeeded without errors.

**Comment by amitaibu** [comment]
Sorry for the noise :)

**Comment by webflo** [comment]
I think you should set COMPOSER_EXIT_ON_PATCH_FAILURE to true in CI environments to catch the true failures. https://github.com/cweagans/composer-patches/blob/master/src/Patches.php#L296
