### ISSUE TITLE
Composer installers version

### ISSUE THREAD

**Issue by Frando** [drupal-composer/drupal-composer-project#212]
I keep getting the following warning on a new project created from drupal-project:

`The "composer/installers" plugin was skipped because it requires a Plugin API version ("1.0.0") that does not match your Composer installation ("1.1.0"). You may need to run composer update with the "--no-plugins" option.
`

Is there a reason composer/installers is locked to 1.0?

**Comment by kasperg** [comment]
This problem seems to be related to old releases of `composer/installers`. It was fixed in release 1.0.23  with composer/installers@6213d900e92647831f7a406d5c530ea1f3d4360e. drupal-composer/drupal-project allows 1.0.20 and up.

We should bump our minimum requirements accordingly.

**Comment by hussainweb** [comment]
It seems this was only a problem with `1.0.22`. Lower versions didn't require the dependency at all and it was fixed in `1.0.24`.

If we want to be very strict, we can just use `^1.0.20 !=1.0.22`. To keep it simple, we can change it to `^1.0.23` or even `~1.1`.

**Comment by webflo** [comment]
Updated the minimal requirements in https://github.com/drupal-composer/drupal-project/commit/7e329fa6a815a77cfd41194110154fb0305a76f0
