### ISSUE TITLE
Permission denied when requiring dev modules

### ISSUE THREAD

**Issue by batigolix** [drupal-composer/drupal-composer-project#219]
I am experiencing permission denied errors when running composer update when I require specific drupal contrib modules that seem to have no stable release.

This occurs on the production environment only not on my local dev environment.

This happens for example when i include backup_migrate in the list of required modules in composer.json:

````
"drupal/backup_migrate": "*@dev",
`````

When running composer update on the production environment I get the error:

````
[RuntimeException]                                                       
Failed to execute git clone --no-checkout 'https://git.drupal.org/proje  
ct/backup_migrate' 'web/modules/contrib/backup_migrate' && cd 'web/modu
les/contrib/backup_migrate' && git remote add composer 'https://git.dru  
pal.org/project/backup_migrate' && git fetch composer                    
fatal: cannot exec 'git-remote-https': Permission denied                 
````

When running composer update on the dev environment the module is being downloaded normally.

The same problem occurs when trying to require the module "redirect" and "migrate_source_json". Those contrib modules like backup_migrate do not have a  stable release.

I am trying to figure out why this error occurs.

**Comment by webflo** [comment]
Looks like a project with your local git installation. I think its not directly related to composer or this project.

**Comment by batigolix** [comment]
Ill have a look at that and post an update here. Thanks
