### ISSUE TITLE
Symlink .editorconfig and .gitattributesscaffolding from web/ to project root

### ISSUE THREAD

**Issue by ak5** [drupal-composer/drupal-composer-project#220]
Hi,

First off, nice project - thanks!

I was wondering if the files below have to be in `web/` - it seems to me like they should be in the project root.

```
web/.csslintrc
web/.editorconfig
web/.eslintignore
web/.eslintrc
web/.gitattributes
```

For example, `web/.editorconfg` has some settings for `composer.json` which wouldn't be applied afaik.

**Comment by webflo** [comment]
It makes sense for a few files but not all of them. http://cgit.drupalcode.org/drupal/tree/.eslintignore contains from paths which will be invalid if we move the file around.

**Comment by ak5** [comment]
Although that could be remedied by prefixing each line with `web/`? Maybe I am being pedantic hah

**Comment by mfernea** [comment]
As custom code should go under /web folder, css & js lint can stay where they are, and I guess only .editorconfig and .gitattributes should be moved (symlinked) in root.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
