### ISSUE TITLE
Projects composer

### ISSUE THREAD

**Issue by woprrr** [drupal-composer/drupal-composer-project#221]
Hii, i like your idea of Composer Template !!

During 1 year I've maintain an similar template based on composer too. Actually i seen these project and i think we can (DO) found an solution to merge the better of two template into one more big !. That big template is this project and I purpose to you merge the "major" functionalities of Drupal8_composer into that project.

project : "https://github.com/woprrr/drupal8_composer"

Actually I am on other project in media ecosystem but I'm glad to participate & help you on the efforts.

Actually my main focus in my project is to migrate all BASH scripts onto full php scripts by process component LIKE symfony projects (http://symfony.com/doc/current/components/process.html) in post-install (by example).

What dit you thing about ? @floretan

**Comment by PatrickBauer** [comment]
Your post is very hard to read. I don't think I understand your question/issue, could you describe it in another way?

**Comment by woprrr** [comment]
I just explain my actual project is simillar to this project (https://github.com/woprrr/drupal8_composer) and need say if we can be insterested to 'merge' functionalities of drupal8_composer  onto this project more followed. To purpose an better template more maintenable and more robust.

Actually i work on new version of my template to add pre-install / post-install in composer to migrate all bash script in full php (by process component).

**Comment by woprrr** [comment]
I think we can add an additional functionality provide by my project in that projet. 
That functionality is the ability to install / update completely drupal in post-install (by example).

Actually in my project that is in custom composer command 'composer site-install' to totally re-install drupal LIKE drush site-install. Why use that in composer ? That is just an helper to manage more easily your project.

I am very open to discuss about that and close my project to merge usefull onto that wonderfull project :)

**Comment by madalinignisca** [comment]
I believe that our project should be kept as minimal as possible without many custom extensions that are not desired by the majority.

Your "composer site-install" can be made as a package and installed anytime and would become available. It is not needed to be hard coded in the skeleton and become another thing to maintain without the major interest of the community.

**Comment by webflo** [comment]
I close the issue because its not actionable atm. Please open smaller issues if you want to change something in this project. Thanks!
