### ISSUE TITLE
Could not find package drupal-composer/drupal-project with stability stable.

### ISSUE THREAD

**Issue by benstallings** [drupal-composer/drupal-composer-project#225]
The quick installation instructions at the top of the GitHub page for this project say to use "composer create-project drupal-composer/drupal-project", but doing so results in the error above. Only --stability dev seems to work. Since this project is being recommended far and wide to clueless Drupal 7 aficionados like myself who are having trouble getting Drupal 8 to do the most basic things like update itself, it would be really helpful to support stable versions of the software. Thank you.

**Comment by webflo** [comment]
``--stability dev`` relates to the version of the template itself, no to Drupal core. The template will install the latest stable release of Drupal core. Maybe we should add something to the README or tag/version the template itself. But maybe that causes more confusion than it helps.

**Comment by benstallings** [comment]
Thank you for clarifying, webflo!
