### ISSUE TITLE
Create web/libraries directory

### ISSUE THREAD

**Issue by SOMERSOFTAndrewCrook** [drupal-composer/drupal-composer-project#228]
In composer.json it specifies 
`"web/libraries/{$name}": ["type:drupal-library"],`
but `'libraries',` is missing at line 28 in  drupal-project/scripts/composer/ScriptHandler.php

**Comment by webflo** [comment]
I thought composer creates it automatically, it that wrong?

**Comment by SOMERSOFTAndrewCrook** [comment]
When composer runs the script, it creates the following directories, if not present,
```
'web/modules',
'web/profiles',
'web/themes',
```
but not the directory web/libraries, so currently for that directory no.

May I suggest that README.md is also updated to indicate that packages of type drupal-library are placed in web/libraries.

Further investigation indicates that if composer (v1.2.1) is directed to download a package into that directory then the directory is created, hence your question in the comment. It is a little unclear why the function creates the directories as they are not needed or why the libraries directory is not made if trying to present a consistent starting point.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
