### ISSUE TITLE
Composer running in "web" dir.

### ISSUE THREAD

**Issue by Tahiche** [drupal-composer/drupal-composer-project#229]
I´m new at Drupal8 and the composer workflow.
During my first test I found that Drush must run in the "web" directory (where drupal enviroment resides) but composer needs to run in the app´s root directory (where composer.json lives and from where the "installer-paths" point to).
Thus, if i´m not wrong, you have to "composer require drupal/module"  from root and then cd to web to enable module via Drush. I find this going back and forth pretty confusing. In part because Composer´s  error message when running from the worn dir points to:
```
[InvalidArgumentException]
  Could not find package drupal/paragraphs at any version for your minimum-stability (stable). Check the package spelling or your minimum-
  stability
```
To get around this i´ve created symlinks in "web" directory:

```
> ln -s /var/www/drupal8/composer.json  composer.json
> ln -s /var/www/drupal8/scripts scripts
> ln -s /var/www/drupal8/vendor vendor
> ln -s /var/www/drupal8/web web
> ln -s /var/www/drupal8/drush drush
```
![image](https://cloud.githubusercontent.com/assets/491834/21313087/fd0fc0da-c5ef-11e6-9d30-4592d615bbd9.png)

And now i can run both composer and Drush from the same web dir, require with composer and enable with drush...

Is this approach correct or are there security or other implications that i´m missing?.

**Comment by PatrickBauer** [comment]
Using symlinks like that, you're bypassing the reason why there is a web directory in the first place.

**Comment by Tahiche** [comment]
Right... so i´m "unprotecting" scripts, vendor, and so on. You´re absolutely right, should have thought of that.
Do you know of a way to run Composer and Drush from the same dir?. 
Thanks in advance

**Comment by weitzman** [comment]
Try out the proposed `drush` script for this project in #98.

**Comment by Tahiche** [comment]
Thanks for your answer weitzman,
After a few tries i think it´s working. In my case i had to put the "drush.wrapper" file under the root directory instead of "/web"  and change it to:
```
cd "`dirname $0`"
./vendor/bin/drush.launcher --root=/var/www/drupal8/web "$@"
```
So it calls drush with the "--root" set to drupal´s web dir. 
That way I can use composer and drush from root dir. Is that right?

Thanks!!

PS: I´m guessing the "cd dirname..." instruction is just an example. I can´t see why it´d be necessary.
