### ISSUE TITLE
Managing custom modules and themes

### ISSUE THREAD

**Issue by Manikandan85** [drupal-composer/drupal-composer-project#230]
Hi,

I used this command `create-project drupal-composer/drupal-project:7.x-dev d7 --stability dev --no-interaction` to install drupal.

So I added composer.json file to my git repo. Now I needed to added my custom modules to the same repository.

So my repository contains only composer json file and my custom modules.

If I run `composer install` in another server, where do the custom modules go in sites/all/custom or in root folder?

How to obtain my custom modules in sites/all/custom folder during composer install?

**Comment by thomascys** [comment]
You should have a look at https://github.com/derhasi/composer-preserve-paths

**Comment by madalinignisca** [comment]
Trying to understand. Are you removing the generated structure?
The gitignore file is well done (latest) and it will keep the minimal needed and all your custom modules and themes.

If you want to manage also your custom modules and themes as from separate repos using composer, that will be possible also soon, as of the new types added.

**Comment by jcnventura** [comment]
A bit late, but for reference, you should add your custom modules directly to d7/web/sites/all/modules/custom. The .gitignore and composer.json files are set to both not ignore changes to this directory and to preserve the contents after composer update/install.
