### ISSUE TITLE
How to use drush.wrapper for local site aliases

### ISSUE THREAD

**Issue by iainhouston** [drupal-composer/drupal-composer-project#234]
It's not clear to me how, using `drupal-project`,  to use `drush.wrapper` for locally-stored site alias files (i.e. VC'd separately from those in `~/.drush` ).

*  I see that `drush/README.md` says that the `drush` directory is where to place local site aliases  
   So I have moved the site alias files there

*  I see that there is a `vendor/drush/drush/examples/drush.wrapper`  which I can use to add `../vendor/bin/drush.launcher --local --alias-path="$PROJECT_ROOT/drush" "$@"`  
  Where to copy this file to so that it comes into effect when invoking drush commands from the project root (rather than web root)?

**Comment by iainhouston** [comment]
OK ... sorted. 
Actually comments in `vendor/drush/drush/examples/drush.wrapper` are accurate except that, in the context of `drupal-project`, the path to  `drush.launcher` is `./vendor/bin/drush.launcher` as the modified `drush.wrapper` gets put in the project root (per comments).

FOLLOW UP: I plan to  

1.  Add some instructions to  `drush/README.md` to say how to use local alias files
2. Add comments to `vendor/drush/drush/examples/drush.wrapper` to be `drupal-project`-specific re both launcher and alias paths

**Comment by webflo** [comment]
There is a ``drush.wrapper`` example. Just put it into the root of the project and it should work.

```
#!/usr/bin/env sh
#
# DRUSH WRAPPER
#
# A wrapper script which launches the Drush that is in your project's /vendor
# directory.
#
# Docs: https://github.com/drush-ops/drush/blob/master/examples/drush.wrapper
cd "`dirname $0`"
./vendor/bin/drush.launcher --root=./web "$@"
```

**Comment by webflo** [comment]
https://github.com/drupal-composer/drupal-project/pull/98 is related. I think we should move forward with [drush-shim](https://github.com/webflo/drush-shim) because it works fine on all platforms. The drush.wrapper works only on Linux and macOS.

**Comment by iainhouston** [comment]
@webflo a) the `drupal-project/drush/README.md` needs narrative to that effect - it takes too long to discover the simple solution and  b) the `drush.wrapper` installed in `vendor/drush/drush/examples` has the incorrect path. One too many dots :-)

**Comment by gergelypap** [comment]
Or simply we could rename `drush` folder in the root to something like `tools/drush`, so then `drush.wrapper` will work. 

This way also add these `--root="web" --config="tools/drush" --include="tools/drush"` in drush.wrapper.

Also we should check if this naming conflict is fixed/changed in Drush 9.

**Comment by webflo** [comment]
@weitzman mentioned in https://github.com/webflo/drush-shim/issues/4#issuecomment-308432583 that Drush 9 does not container drush wrapper/launcher anymore. I think its not worth to add it for 8.3.x?

@weitzman Could you clarity the current situation? Thanks!

**Comment by weitzman** [comment]
I agree. We can close this issue IMO.

**Comment by webflo** [comment]
Ok, thanks
