### ISSUE TITLE
Current testsuite in phpunit.xml.dist is confusing

### ISSUE THREAD

**Issue by cristinallamas** [drupal-composer/drupal-composer-project#235]
Current testsuite in phpunit.xml.dist is confusing as it points to a non-existent folder. In order to make the example clear and actually useful it would be beneficial to update it to point to modules folder.

**Comment by cristinallamas** [comment]
Adding a pull request. I need permissions I think

**Comment by cristinallamas** [comment]
https://github.com/drupal-composer/drupal-project/pull/236 Pull Request

**Comment by Rudokus** [comment]
The path is correct but is doesn't work with the phpunit from the vendor folder.
vendor/bin/phpunit -c phpunit.xml

**Comment by normanlolx** [comment]
Inactive.
