### ISSUE TITLE
No stable version of drupal-project

### ISSUE THREAD

**Issue by chanster** [drupal-composer/drupal-composer-project#237]
unable to create a drupal-project with stabel version of Drupal Core.

> composer create-project drupal-composer/drupal-project test --no-interaction 
>
> [InvalidArgumentException]                                                  
> Could not find package drupal-composer/drupal-project with stability stable.

**Comment by chanster** [comment]
Apologies, it seems drupal-composer/drupal-project:8.x-dev does download the current stable version of Drupal Core.

**Comment by webflo** [comment]
8.x-dev relates to the version on the template, not the core version. maybe we should explain it in the readme.

**Comment by steve65140** [comment]
+1 for amending the documentation as I also assumed that "8.x-dev" referred to Drupal not the template and I wanted the current stable version of Drupal. The current readme.md isn't very clear.

**Comment by steve65140** [comment]
It would also be helpful to document acceptable values for --stability as "stable" doesn't seem to be valid e.g. "composer create-project drupal-composer/drupal-project:8.x-dev sowebco800 --stability stable" fails with "[InvalidArgumentException] Could not find package drupal-composer/drupal-project with version 8.x-dev."

**Comment by PatrickBauer** [comment]
@steve65140 Thats already documented, see https://getcomposer.org/doc/04-schema.md#minimum-stability

It has nothing to do with the drupal-composer project itself.
