### ISSUE TITLE
Removing deprecated files that come from drupal/drupal

### ISSUE THREAD

**Issue by rodrigoaguilera** [drupal-composer/drupal-composer-project#248]
I found myself in the situation of updating to drupal 8.3.x and having a .eslinrc file in my /web dir that points to a nonexistent /web/core/.eslintrc file (changed to .eslintrc.json). This created a bit of a headache for me so I open an issue here.

I actually don't have any idea on how to solve it except for checking the drupal core version on composer.lock and removing this file if it is equal or greater than 8.3.0

**Comment by webflo** [comment]
Its a issue for https://github.com/drupal-composer/drupal-scaffold
