### ISSUE TITLE
Add preAutoloadDump script

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-composer-project#253]
Lets add https://www.drupal.org/node/2764267 to the composer.json by default once its fixed in core.

**Comment by andypost** [comment]
The same time makes sense to adopt vendor tests clean-up https://github.com/drupal-composer/drupal-project/issues/323

**Comment by normanlolx** [comment]
@webflo – Is this still active/relevant? I don't understand what needs to done for this issue. Can you maybe open a PR? 🙂

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
