### ISSUE TITLE
What's the recommended way of using dev versions of modules?

### ISSUE THREAD

**Issue by hanoii** [drupal-composer/drupal-composer-project#254]
So, if you have a dev module, I you do something like:

```json
"drupal/module": "1.x-dev"
```

Would this always update to the latest commit/dev release on `composer update`?

How would you reference a specific commit hash, can I do that without adding a VCS repository?

**Comment by webflo** [comment]
Please read http://stackoverflow.com/questions/14256563/how-to-make-composer-to-use-an-exact-sha1-value
