### ISSUE TITLE
Deploy to FTP hosting without shell access and make website accessible from webroot.

### ISSUE THREAD

**Issue by finex** [drupal-composer/drupal-composer-project#257]
Hi, this project creates a vendor directory ("vendor") outside the Drupal webroot (ex: "web"). If you upload the project to a standard hosting using FTP access, the website will be located on "www.example.com/web". 

Would be possible to provide an easy system to make the website accessible directly from "www.example.com"?

On Drupal 6/7 a simple .htaccess on the webroot was enough to fix the issue, unfortunatly the workaround doesn't work anymore on D8.

Thanks for the support.

**Comment by finex** [comment]
Currently you can use the following workaround to solve this issue:

1) Create an .htaccess file on the webroot:

```
Options -Indexes
RewriteEngine on
Options +FollowSymLinks
ReWriteCond %{HTTP_HOST} ^www.example\.dev$ [NC]
ReWriteRule !^subdirectory/   - [C]
ReWriteRule ^(.*)  subdirectory/$1  [L]
```

2) Change the default .htaccess adding the subdirectory using RewriteBase directive:

```
RewriteBase /subdirectory
```

3) Apply the following patch to Core:
 [https://www.drupal.org/files/issues/0001-Switching-Local-to-Trusted.patch.txt](url)

**Comment by derhasi** [comment]
You could build the drupal site in the root of your project, so you would not have a `web` folder to put stuff (core, modules, themes) in. Your setup then might look similar to `drupal/drupal`.

For that you would need to change some paths in `composer.json`, `.gitignore` and `scripts/composer/ScriptHandler.php` and remove the `web/` prefix there.
See https://github.com/drupal-composer/drupal-project/issues/64#issuecomment-283427586 for a similar issue.

I did not test that approach, as we always put our site in a docroot.

**Comment by finex** [comment]
Thanks Derhasi 👍 
I know I can change paths in composer and other files to start the project using the default path, my question was about keeping a custom structure like the one proposed by this project but allowing to browse the website from the webroot when Drupal is inside a subdirectory. See my previous comment for a possible workaround  :-)

**Comment by webflo** [comment]
Alright, i think all questions have been answered.
