### ISSUE TITLE
Is .gitignore correct?  Initial commit wants to commit too much I think?

### ISSUE THREAD

**Issue by rick02840** [drupal-composer/drupal-composer-project#260]
When I do an initial commit, it is adding everything in /web, even settings.php files.  My git repo is in the same folder as .gitignore (see **site** folder below) which is the same folder that /web is located in.  Is this correct? 

composer create-project drupal-composer/drupal-project:8.x-dev **site** --stability dev --no-interaction  

 It is not adding /.idea/ though, which is also in site ...seems strange.  Seems like / is working for .idea but not for /web.   

Before the initial commit, this is what git wants to add:
.gitignore
.travis.yml
LICENSE
README.md
composer.json
composer.lock
config/
drush/
phpunit.xml.dist
scripts/
web/

**Comment by madalinignisca** [comment]
It is not adding any settings.php by default.
there are lots of generated files and folders in web/ that need to be kept in git.
it works really similar to how other frameworks do (symfony, laravel, cakephp).

by default it will not put in git: the core, contrib modules, themes, libraries, profiles and any settings.php (including multisites). nor public files in any site.

will take strictly the minimum required.

**Comment by webflo** [comment]
Thanks for your support @madalinignisca
