### ISSUE TITLE
Drupal console doesn't seem to work

### ISSUE THREAD

**Issue by bailey86** [drupal-composer/drupal-composer-project#263]
Code was downloaded to ~/sites/kb-d8-3 - then tried to run:

kbailey@asdasd:~/sites/kb-d8-3/web$ ../vendor/bin/drupal site:status

 [ERROR] Command "site:status", is not a valid command name.                                                            

kbailey@asdasd:~/sites/kb-d8-3/web$

Seems a bit basic - so sorry if I'm missing something - but after downloading the files it seems that console doesn't want to run a basic site:status command.

Apologies in advance if I've missed something obvious.

**Comment by jmolivas** [comment]
@bailey86 is your site installed ? 

Try `../vendor/bin/drupal site:install` and answer the interactive questions.

NOTE: There is no need to be located at `web` to execute DrupalConsole. You can execute from project root as `vendor/bin/drupal`.

**Comment by webflo** [comment]
``site:status `` works after initial site install on my machine.

**Comment by madalinignisca** [comment]
confirming. that happens only when the website has not been yet installed.
@bailey86 after you do the composer install, either you install drupal or if it's an already started project, you import your database.

**Comment by webflo** [comment]
This is not a drupal-project specific project.
