### ISSUE TITLE
Set minimum-stability to "stable"

### ISSUE THREAD

**Issue by rodrigoaguilera** [drupal-composer/drupal-composer-project#266]
Currently minimum-stability is set to "dev".
I think we should rely on composer defaults and have the minimum stability set to "stable" just by removing that line.
https://getcomposer.org/doc/04-schema.md#minimum-stability

Then we will need to add dev, alpha, beta, RC suffixes to the specific dependencies that need it like for example devel or drupal console. 
https://getcomposer.org/doc/04-schema.md#package-links
The composer.json get also more semantic.

This way we don't hide dependencies on modules, libraries, etc that are not so mature.

This all started for me because there is a contrib module with a broken HEAD
https://www.drupal.org/node/2872222

What do you think?

**Comment by webflo** [comment]
This should not happen we use ``"minimum-stability": "dev"`` **and** ``"prefer-stable": true`` for this reason. Are you sure you have both in your composer.json?

**Comment by rodrigoaguilera** [comment]
I think they fixed superfish module now but I will try to publish a dummy library to reproduce this.

Anyway that problem is not the main reason for this change. Is about making dev,beta, alpha and rc dependencies more explicit instead of saying pick any stability but prefer stable.

I feel we also get a speed improvement since less releases are scanned.

**Comment by slootjes** [comment]
+1 on this. It's safer and faster to specify the stability on a per package level.

**Comment by rodrigoaguilera** [comment]
With drupal console stable now the template doesn't even has to specify any stability.

We can add devel as an example that is going to need a @RC tag if `"minimum-stability": "dev"` is removed

**Comment by joelpittet** [comment]
Seems like core is grappling with this at the moment too:
https://www.drupal.org/project/drupal/issues/3135247

**Comment by normanlolx** [comment]
Core indeed moved to [stable now (9.1.0)](https://github.com/drupal/recommended-project/blob/9.1.0/composer.json#L26). The [change record](https://www.drupal.org/node/3174472) contains a lot of good arguments to do the same. Then the README needs to be updated to explain how to properly require unstable releases.

**Comment by joelpittet** [comment]
I'm on board with this too now, you can be explicit about your @dev if you need the unstable.

**Comment by AlexSkrypnyk** [comment]
As per D9 change record:

> This (`"minimum-stability": "dev"`) allowed any development version to be installed with the template; however, it occasionally produced unexpected results, such as upgrading to newer unstable releases rather than remaining on a current stable release. The Composer "prefer stable" setting is considered to be advisory only, and does not guarantee that a stable release will be chosen even when one is available.

Having `dev` as default is not what consumer projects most likely would use - stable versions are usually preferable to unstable ones. Any unstable versions can be manually resolved by a consumer site developer on per-need basis.

I suggest we do 2 things:
1. Change `minimum-stability` to `stable` in this project.
2. Add a readme entry explaining how to switch to use non-stable versions.

**Comment by normanlolx** [comment]
+1 on both points.

**Comment by joelpittet** [comment]
I moved to `minimum-stability: stable` for everything as we just need to be explicit in non-stable versions, which is a net benefit. +1 to this change
