### ISSUE TITLE
Dupal console does not support same composer dependencies as Drupal 8.4.x

### ISSUE THREAD

**Issue by yanniboi** [drupal-composer/drupal-composer-project#273]
Drupal console requires symfony/http-foundation <3.0. 

Drupal 8.4.x comes with symfony/http-foundation v3.2.6 causing composer install issues.

Drush is also impacted by the update, however version 9 of drush works with Drupal 8.4.x

This issue is being worked on here https://github.com/drupal-composer/drupal-project/pull/272

**Comment by webflo** [comment]
I did some work in https://github.com/drupal-composer/drupal-project/pull/270

**Comment by yanniboi** [comment]
Cool I was just about to suggest that :P
