### ISSUE TITLE
Explain correct autoloaded setup

### ISSUE THREAD

**Issue by tarjei** [drupal-composer/drupal-composer-project#28]
Hi, I'm trying to get drupal/console installed on a newly minted drupal 8 project, but it keeps getting the dependencies wrong.

drupal/console tries to load the autoload file it finds in `web/core/vendor/autoload.php` but I see there is also one in $root/vendor/autoload.php. How should this work?

I also seem to have a full vendors dir in $root/vendors and in $root/web/core/vendors , why?

I do not think I did anything wrong in the project setup, but I would love to get rid of the web/core/vendors file and keep my tree clean. Is that possible?

**Comment by webflo** [comment]
I think we have to fix drupal/console first because imo console should load autoload.php from the drupal root directory.

**Comment by webflo** [comment]
Maybe @jmolivas could help?

**Comment by jmolivas** [comment]
@tarjei you can install drupal/console globally using the provided installer:

```
$ curl -LSs http://drupalconsole.com/installer | php
```

Or using composer: 

```
$ composer global require drupal/console:@stable
```

I have not tried installing `drupal/console` using `drupal-composer` but I can take a look at this.

**Comment by webflo** [comment]
@tarjei Got it working in one single composer.json

```
{
    "name": "drupal-composer/drupal-project",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "MIT",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "support": {},
    "repositories": [
        {
            "type": "composer",
            "url": "https://raw.githubusercontent.com/webflo/d8/master/packages.json"
        },
        {
            "type": "vcs",
            "url": "https://github.com/webflo/DrupalConsole.git"
        },
        {
            "type": "composer",
            "url": "https://packagist.drupal-composer.org"
        }
    ],
    "require": {
        "composer/installers": "^1.0.20",
        "drupal/core": "8.0.x-dev",
        "drush/drush": "8.*",

        "drupal/devel": "8.1.*@dev",
        "drupal/token": "8.1.*@dev",
        "drupal/console": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-install-cmd": "scripts/composer/post-install.sh"
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "web/drush/commands/{$name}": ["type:drupal-drush"]
        }
    }
}
```

**Comment by webflo** [comment]
Created https://github.com/hechoendrupal/DrupalConsole/pull/652

**Comment by webflo** [comment]
@tarjei Here my the updated composer.json. Works like a charm.

```
{
    "name": "drupal-composer/drupal-project",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "MIT",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "support": {},
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.drupal-composer.org"
        }
    ],
    "require": {
        "composer/installers": "^1.0.20",
        "drupal/core": "8.0.x-dev",
        "drush/drush": "8.*",

        "drupal/devel": "8.1.*@dev",
        "drupal/token": "8.1.*@dev",
        "drupal/console": "dev-master"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-install-cmd": "scripts/composer/post-install.sh"
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "web/drush/commands/{$name}": ["type:drupal-drush"]
        }
    }
}
```

**Comment by webflo** [comment]
Feel free to open a new issue if you have any problems ...

**Comment by jmolivas** [comment]
This looks awesome, thanks for all of the work and the PR at DrupalConsole project @webflo and feel free to add a new issue if theres anything we can help with @tarjei

**Comment by tarjei** [comment]
Will do! Thanks!

2015-07-02 20:42 GMT+02:00 Jesus Manuel Olivas notifications@github.com:

> This looks awesome, thanks for all of the work and the PR at DrupalConsole
> project @webflo https://github.com/webflo and feel free to add a new
> issue if theres anything we can help with @tarjei
> https://github.com/tarjei
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/drupal-composer/drupal-project/issues/28#issuecomment-118121528
> .

## 

---

Tarjei Huse
Mobil: 920 63 413
