### ISSUE TITLE
Should this be used to add composer to a Drupal 7 project

### ISSUE THREAD

**Issue by frob** [drupal-composer/drupal-composer-project#280]
The answer to this question would be good for the FAQ on the 7.x branch readme.md

Should I be moving my drupal 7 projects to a composer workflow with this project? As in, not starting new projects but taking existing non-composer projects and moving them to composer with this project as a basis?

**Comment by jcnventura** [comment]
I'd say yes.. Just be careful with adding all your custom stuff to preserve-paths
