### ISSUE TITLE
Add code sniffer by default

### ISSUE THREAD

**Issue by Saphyel** [drupal-composer/drupal-composer-project#281]
I think will be great to add code sniffer (and maybe a command to run it) because the drupal community has been always an example of good quality code so in this way we can keep encouraging people to write better code and avoid to report every time the same mistakes.

**Comment by gergelypap** [comment]
Duplicate #227

**Comment by rodrigoaguilera** [comment]
Isn't coder module now a drupal core dev dependency?

**Comment by Saphyel** [comment]
@rodrigoaguilera you are right: https://github.com/drupal/drupal/blob/8.3.x/core/composer.json#L43 seems like it was added in the 8.3.x
