### ISSUE TITLE
Missing folders and files.

### ISSUE THREAD

**Issue by Mediasaur** [drupal-composer/drupal-composer-project#282]
Composer does not download several files and folders (It does not throw any error messages.). These are all it downloads: http://imgur.com/a/e0qYx

**Comment by apeofbase** [comment]
Experiencing this exact issue. 

- Clone private repo that only has composer.json and composer.lock file tracked
- Run `composer install`
- All *.php files missing in `web/`

Running `composer update` instead of `composer install` on fresh git clone, and all PHP files are added as expected.

**Comment by apeofbase** [comment]
Just a follow-up: running `composer drupal-scaffold` after `composer install` fixed our issue. Still not sure why this is not executed when running `composer install`.

**Comment by apeofbase** [comment]
From the FAQ:

> You can achieve that by registering @drupal-scaffold as post-install and post-update command in your composer.json

https://github.com/drupal-composer/drupal-project#should-i-commit-the-scaffolding-files

**Comment by Mediasaur** [comment]
Justin, thanks for great help.

I could make it load missing files using 2 different methods you provided:

1) After creating project with default command (`composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`), by running this command:

`composer drupal-scaffold`

2) After creating project with default command (`composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`) and updating composer.json according to https://github.com/drupal-composer/drupal-project#should-i-commit-the-scaffolding-files, then by running this command:

`composer update`

I asked some colleagues and they told that they did not need above methods and composer downloaded all files only using default create command. Anyway, you replies solved my problem; thanks again.

**Comment by adamfchs** [comment]
Running to the same problem.  Was able to install new projects last week with no issue. This week I get no core files.

Neither the composer drupal-scaffold method or updating the composer.json worked for me.  drupal-scaffold ran with no change to files and updating the comsposer.json returned:
Script ... handling the post-update-cmd event returned with error code 127

When updating the composer.json, I tried adding this to the end of the scripts section:
"post-install-cmd": [
            "@drupal-scaffold",
            "..."
        ],
        "post-update-cmd": [
            "@drupal-scaffold",
            "..."
        ]

and also replacing all the existing pre-and post-install commands with the above lines.  Was either the correct way to do the update?

**Comment by jonathanchris** [comment]
I'm also running into this issue, running
`composer create-project drupal-composer/drupal-project newProject --stability dev`
Then running
`composer drupal-scaffold`

This runs w/o errors and I see messages `Downloading: 100%` repeating, but still no core files or files in web directory.

**Comment by dustinleblanc** [comment]
I am also having an issue with a fresh site I spun up with https://github.com/pantheon-systems/example-drops-8-composer which is a close fork of this project

**Comment by jensschulze** [comment]
Self-updating composer fixed the problem for me.
Run `composer selfupdate`, then try `composer create-project …` again!

**Comment by jonathanchris** [comment]
Thanks @jensschulze that did the trick for me!

**Comment by adamfchs** [comment]
Composer self-update then the create project also worked for me!  Thanks!!

**Comment by webflo** [comment]
Thanks for the support @jensschulze.

**Comment by aiglesiasn** [comment]
@jensschulze solution worked!

**Comment by aanjaneyam** [comment]
I am seeing this issue with the latest composer version 1.8.5. I have to run

composer create-project drupal-composer/drupal-project some-dir --no-dev --no-interaction

and then run composer drupal-scaffold after the composer create-project command finishes to get the scaffold files (like index.php, update.php etc).

It is the same problem even if you give a version to create-project command like 8.7.1. I have tried it with varbase too. However, somehow it works when I use composer create-project vardot/varbase-project:8.6.x-dev ... but not with stable version like 8.6.11 or 8.6.10 or using composer create-project command without any version in order to get the latest stable version.
