### ISSUE TITLE
Dead link to Drupal Make

### ISSUE THREAD

**Issue by stephanvierkant** [drupal-composer/drupal-composer-project#287]
Disclaimer: I'm completely new to Drupal.

I've just started looking into the project a I start with finding a dead link to Drupal Make (https://github.com/drush-ops/drush/blob/master/docs/make.md) on `readme.md`.

The same dead link exist in the official documentation: https://www.drupal.org/node/2471553

**Comment by webflo** [comment]
Drush 9 (master) dropped support for Drush Make. The docs are available on https://github.com/drush-ops/drush/blob/8.x/docs/make.md

**Comment by webflo** [comment]
Thx @stephanvierkant

**Comment by webflo** [comment]
Fixed the dead link on drupal.org as well.
