### ISSUE TITLE
some kind of ipv6 ipv4 error?

### ISSUE THREAD

**Issue by edlington** [drupal-composer/drupal-composer-project#289]
[Composer\Downloader\TransportException]
  The "http://packagist.org/p/masterminds/html5%244f740a085ca6828a742867a08e8935714c0c7c37260588822860fcc4c551cce8.json" file could not be downloaded: failed to op
  en stream: HTTP request failed!

**Comment by edlington** [comment]
Tried many things. Disabling ipv6, resetting ipv6 priority, installing cert... hours and hours then days

**Comment by webflo** [comment]
Sorry, i think this is a problem specific to your environment and composer in general. Its not directly related to this project. You should look in composers issue queue for help. Maybe https://github.com/composer/composer/issues/4388 is related?
