### ISSUE TITLE
How to use autoload files from other projects?

### ISSUE THREAD

**Issue by helderco** [drupal-composer/drupal-composer-project#29]
I'm trying to install [drupal/webprofiler](https://www.drupal.org/project/webprofiler), which has the following composer.json:

``` json
{
    "name": "drupal/webprofiler",
    "description": "",
    "type": "drupal-webprofiler",
    "license": "GPL-2.0+",
    "require": {
        "symfony/stopwatch": "2.4.*"
    },
    "autoload": {
        "files": [
            "vendor/symfony/stopwatch/Symfony/Component/Stopwatch/Stopwatch.php"
        ]
    }
}
```

This gives me a fatal error, because composer is trying to find that file in a vendor folder inside that module. How should this be fixed, so that files is looking for files in the root vendor folder?

**Comment by webflo** [comment]
The fix should be in `drupal/webprofiler` itself. Because its not allowed to require files from other libraries via composers autoload feature.

**Comment by webflo** [comment]
We had a similar issue in core and resolved it in https://www.drupal.org/node/2468499.

**Comment by helderco** [comment]
Yeah, I don't even understand why they're requiring that file when it should be autoloaded already.

I'll work it out on their issue queue, thanks.

**Comment by webflo** [comment]
Thanks!
