### ISSUE TITLE
Hardcoded public files dir

### ISSUE THREAD

**Issue by dillix** [drupal-composer/drupal-composer-project#295]
I changed public files dir in settings.php to /uploads, but when I try to install new module thought composer I get following error:
```
[Symfony\Component\Filesystem\Exception\IOException]                                    
  Failed to create "/Users/maxpro/Sites/site.dev/htdocs/web/sites/default/files"  
```
After investigation I found problem in /scripts/composer/ScriptHandler.php
Why public files dir hardcoded here?

**Comment by webflo** [comment]
Your use case makes sense, it is there to prepare the site for initial installation.

**Comment by webflo** [comment]
(Starting a project from scratch via composer create-project)

**Comment by dillix** [comment]
@webflo I started project from scratch, then I changed files public dir in drupal settings.php, but then I run composer require drupal/[module name], I get errors, after investigation I've found that files public dir hardcoded in ScriptHandler.php. I think this is a bug. Can we read files public dir from drupal settings.php?

**Comment by normanlolx** [comment]
Inactive.
