### ISSUE TITLE
Should drush updb work?

### ISSUE THREAD

**Issue by tarjei** [drupal-composer/drupal-composer-project#30]
Hi, should drush updb work with the latest version of drupal-composer?

**Comment by webflo** [comment]
Yeah it should work if you use the bundled drush command. Could you provide more information about the error message or exception?

**Comment by tarjei** [comment]
I'll see what I can do. I ended up nuking the installation, but it happened after I tried upgrading from b10 to b11 using composer.

**Comment by webflo** [comment]
Maybe something changed from beta10 to beta11? I close the issue because we can´t to anything right now.

**Comment by tarjei** [comment]
Ok. It seemed to me at the time that the error was that a serviceefinition had changed between b10 and b11 and that this stopped drush from resetting the services.
