### ISSUE TITLE
Remove .idea folder from .htaccess

### ISSUE THREAD

**Issue by heartdriven** [drupal-composer/drupal-composer-project#302]
As I opened the default .htaccess I noticed this line:

`# Ignore files generated by PhpStorm`
`/.idea/`

I think it's up to the developer to [ignore phpstorm directories globally](https://stackoverflow.com/questions/7335420/global-git-ignore).  It's not a big issue but the point is that this line just doesn't belong here.  If you take the same perspective you may also have to ignore other editors or systems unwanted files (e.g. macos: .DS_Store) and that is something you don't want to support.

**Comment by webflo** [comment]
@heartdriven I am with you in general. But this was a trade-off. No time to educate every user ;)
