### ISSUE TITLE
Trying to install Release Candidate or 8.4 Dev

### ISSUE THREAD

**Issue by criley** [drupal-composer/drupal-composer-project#305]
I like the convience that composer allows for however it would be really nice if it was more clear as to how to use this to install a release candidate (8.4RC at this time) or even to use this on a testing/development server. With the change to Drush 9 and the differences with required libraries etc its a confusing mess and or I have missed some stuff

Thanks in advance

**Comment by garnett2125** [comment]
Changing composer.json to:
"drupal/core": "~8.4",
"drush/drush": "~9.0"
and running composer update --with-dependencies
did the work for me.

**Comment by joemewes** [comment]
8.4 should be working fine with `update to Drush 8.1.12 or higher` but fails re: https://github.com/drush-ops/drush/issues/3033

reason I mention is requiring Drush ^9.0 will mean a lot of Drush commands refactoring in core and contrib modules, like libraries downloads and config-import commands etc.

Not sure if Im on the correct issue here... but seems relevant...

**Comment by pcambra** [comment]
Related https://www.drupal.org/node/2913970

**Comment by fafnirical** [comment]
[Drush 8.1.15](https://github.com/drush-ops/drush/releases/tag/8.1.15) was released, which should allow Drupal 8.4.0 to work with a site-local Drush 8.

**Comment by lithiumlab** [comment]
This worked for me:
`composer update drush/drush`
cleaned up site cache just in case, then...
`composer update drupal/core --with-dependencies`

**Comment by webflo** [comment]
Drush 9 has been released today. Drush 8 and 9 is compatible with Drupal 8.4.x.
