### ISSUE TITLE
drush/policy.drush.inc incompatible with drush 9

### ISSUE THREAD

**Issue by zaporylie** [drupal-composer/drupal-composer-project#306]
This is a story of the future but with Drush 9 pm-* policy (drush/policy.drush.inc) won't work anymore (no more drush hooks). I know I'm repeating myself but I still believe _policy_ should become a [standalone project](github.com/zaporylie/drupal-composer-drush-policy) configurable via composer.json. That way we could release another iteration at some point, compatible with Drush 9.

**Comment by weitzman** [comment]
As of right now, Drush9 still reads legacy commandfiles and many hooks fire. Do you have a particular hook in mind?

**Comment by zaporylie** [comment]
Didn't know that. Anyways - if hooks will become deprecated in favour of annotated plugins in one of the following Drush major versions we would have solve policy issue one way or another. I believe standalone drush policy package is the way to go.

Hook implementations I'm referring to:
```
function drush_policy_pm_updatecode_validate() {
  return _deny_message();
}
function drush_policy_pm_update_validate() {
  return _deny_message();
}
function drush_policy_pm_download_validate() {
  return _deny_message();
}
```

**Comment by zaporylie** [comment]
From: https://github.com/drupal-composer/drupal-project/blob/8.x/drush/policy.drush.inc

**Comment by weitzman** [comment]
none of that code matters anymore - pm-updatecode is removed in drush9. the file serves as documentation by example.

**Comment by weitzman** [comment]
See #350
