### ISSUE TITLE
Error when doing 'create-project'

### ISSUE THREAD

**Issue by paulcanning** [drupal-composer/drupal-composer-project#314]
I get the following error in the terminal when running `composer create-project drupal-composer/drupal-project:8.x-dev test-project --prefer-dist --stability dev --no-interaction`

> PHP Fatal error:  Cannot declare class Drupal\Console\Composer\Plugin\ExtenderManager, because the name is already in use in /Users/paul.canning/Sites/snow/visit-snowdonia/test/vendor/drupal/console-extend-plugin/src/ExtenderManager.php on line 8

**Comment by tebb** [comment]
Related to this perhaps?

https://github.com/hechoendrupal/drupal-console/issues/3475

**Comment by jmolivas** [comment]
@tebb @paulcanning the issue on the DrupalConsole repo was resolved. It was related to missing absolute path when calling the command.
https://github.com/hechoendrupal/drupal-console/issues/3475#issuecomment-320717181

**Comment by webflo** [comment]
Thanks @jmolivas
