### ISSUE TITLE
Site broken after update to 8.4.0

### ISSUE THREAD

**Issue by cristinallamas** [drupal-composer/drupal-composer-project#318]
updating to Drupal 8.4.0 has broken my site. I don't know what to do to recover it, I am using drupal-project

my error log is

```PHP Parse error: parse error, expecting `';'' or `'{'' in mysite/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php on line 50```

Drush Version : 8.1.15
PHP 7.1.3

**Comment by junowilderness** [comment]
This is also reported in https://www.drupal.org/node/2916251
