### ISSUE TITLE
drush commands get put in the wrong place

### ISSUE THREAD

**Issue by joachim-n** [drupal-composer/drupal-composer-project#320]
I did:

```
composer require drupal-code-builder/drupal-code-builder-drush
```

It got put into drush/contrib rather than web/drush/contrib.

**Comment by weitzman** [comment]
You can configure the installers dependency to put vendor code where you need it. This isn't drush's responsibility.

**Comment by joachim-n** [comment]
> This isn't drush's responsibility.

I didn't say it was. This is filed in the repo for drupal-composer, which is respnsible for where it gets put.

Could you reopen this please?

**Comment by weitzman** [comment]
Woops, sorry about that. I get similar email notifications for both projects. 

I actually think this is by design.Drush will pickup commandfiles in either place, and we have been recommending the top level drush folder for a long time.

**Comment by joachim-n** [comment]
Ah fair enough.

(My comandfile wasn't being picked up in either location, but I think I need to wait for the next beta of Drush before trying again.)

**Comment by webflo** [comment]
@joachim-n @weitzman I think this has been fixed, right?
