### ISSUE TITLE
Allow to exclude vendor tests

### ISSUE THREAD

**Issue by andypost** [drupal-composer/drupal-composer-project#323]
Core using extension to clean-up tests from vendor dirs
```
    "post-package-install": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup",
    "post-package-update": "Drupal\\Core\\Composer\\Composer::vendorTestCodeCleanup"
```
It makes sense to provide same option for `install --no-dev` to minimize payload

**Comment by andypost** [comment]
- https://github.com/barryvdh/composer-cleanup-plugin
- https://github.com/dg/composer-cleaner

**Comment by Chi-teck** [comment]
I suppose this script will not be called in this case because it's not available when vendor packages are being installed.

**Comment by andypost** [comment]
It will come from core https://www.drupal.org/node/3059717

**Comment by normanlolx** [comment]
Inactive.
