### ISSUE TITLE
Composer does not update drupal 8.3.7 to 8.4.0

### ISSUE THREAD

**Issue by nlighteneddesign** [drupal-composer/drupal-composer-project#330]
I've been running composer update drupal/core --with-dependencies -vvv as well as trying to clear composer cache and even deleting the vendor folders and reinstalling.

`composer outdated`shows drupal/core needing an update
`drupal/core                           8.3.7   8.4.0   Drupal is an open source content management platform powering millions of websites and applications.`

`composer update drupal/core --with-dependencies` says nothing needs to be updated

```Resolving dependencies through SAT
Dependency resolution completed in 46.404 seconds
Analyzed 12663 packages to resolve dependencies
Analyzed 680455 rules to resolve dependencies
Nothing to install or update
Resolving dependencies through SAT
Dependency resolution completed in 0.002 seconds
Reading /var/www/development/internal/vendor/composer/installed.json
Generating autoload files
Removing packages services cache file:
```

**Comment by nlighteneddesign** [comment]
I got it to work by using the following steps:

update composer.json to use drupal/core ^8.0 instead of ~8.0
update composer.json to use drush/drush ~9.0 instead of ~8.0

Delete vendor, core, and composer.lock

run composer install again

**Comment by webflo** [comment]
You can debug the dependency with ```composer why-not drupal/core 8.4.0```. This command shows which dependency prohibits the update.
