### ISSUE TITLE
How to set up a project as a sub directory in the root?

### ISSUE THREAD

**Issue by donsanjeewaeranga** [drupal-composer/drupal-composer-project#331]
I need to set up a project as a sub directory.
If the project is myproject, it will be http://[mydomain].com/myproject
With the current folder structure, we need to have a directory called "myproject" in side the web directory. When I do so and change urls accordingly in composer.json and .gitignore files, the site gives an error like "Warning: require(.../../vendor/autoload.php): failed to open stream: No such file or directory in ...\autoload.php on line 17"

Can you help to resolve this?

**Comment by donsanjeewaeranga** [comment]
I found the issue. I updated the autoload.php file in the drupal root as below.
return require __DIR__ . '/../vendor/autoload.php'; =>
return require __DIR__ . '/../../vendor/autoload.php';
It fixed the issue.

**Comment by webflo** [comment]
👍
