### ISSUE TITLE
How do I update to Drupal 8.4.2?

### ISSUE THREAD

**Issue by KoinBanks** [drupal-composer/drupal-composer-project#332]
Hey,

I'm using this project to manage drupal installation and I'm trying to update from 8.3.7 to 8.4.2.

When I try `composer update drupal/core --with-dependencies` It won't do anything.

What do I have to do?

**Comment by webflo** [comment]
Please follow the instructions on https://github.com/drupal-composer/drupal-project/issues/330 or https://www.previousnext.com.au/blog/update-drupal-core-84-step-by-step-guide / https://www.previousnext.com.au/blog/using-composer-debug-issues-updating-drupal-core

**Comment by KoinBanks** [comment]
It worked, thanks!
