### ISSUE TITLE
What happened to the "paranoid-mode"?

### ISSUE THREAD

**Issue by medienverbinder** [drupal-composer/drupal-composer-project#333]
Has the paranoia mode been outsourced to a plugin or can someone tell me if this approach still exists? In an earlier version, this option existed in the composer.json file:

`...
"drupal-paranoia": "DrupalProject\\composer\\AssetInstaller::install",
...`

**Comment by webflo** [comment]
Its WIP, but i did not made much progress. https://github.com/drupal-composer/drupal-project/pull/180

**Comment by webflo** [comment]
Lets discuss it in #180
