### ISSUE TITLE
how to run drupal console and drush?

### ISSUE THREAD

**Issue by luckyaffer** [drupal-composer/drupal-composer-project#336]
I used "composer create-project" to download the drupal 8 and install it on the browser.
The read me said drupal console and drush were also installed.
But when I typed drupal, it says: command not found, and drush:   The program 'drush' is currently not installed.
sorry, I just don't know how to deal with it. How can I run them?
I will be very appreciated if you can give me the steps.
I have tried to run ./vendor/bin/drupal, I got a Permission denied.

**Comment by javaskater** [comment]
run them locally...
go to the web subdirectory of your drupal root and then pass the commands
**php ../vendor/drush/drush/drush.php** _(for drush)_
**php ../vendor/drupal/console/bin/drupal.php** _(for the drupal console)_

passing the scripts above without any arguments give you the list of available comands

**Comment by luckyaffer** [comment]
@javaskater Thanks very much, I see the command list. But I still can't run command drupal or drush.
I'm a novice. I'm sorry if it's troubling you

**Comment by derhasi** [comment]
@javaskater composer even makes that easier for you, so all defined commands are refernced in the ./vendor/bin folder.

So you easily can run ./vendor/drush or ./vendor/drupal ftom your project root.

**Comment by derhasi** [comment]
Oh sorry, I just saw @luckyaffer already tried this approach. Hm, did you really try to execute the commands from the project root? Did you check if the commands in vendor/bin are marked executable? (See https://stackoverflow.com/a/22122663)

**Comment by javaskater** [comment]
Which command do you want to run and what is the output of your command. By
the way which OS do you work with?

**Comment by luckyaffer** [comment]
@derhasi  yes, I  have executed the commands from the project root. The commands in vendor/bin are  marked executable, but I found drush in vendor/drush/drush and drupal in vendor/drupal/console/bin/ are not excutable, so I add +x to them and I can run the commands through ./vendor/bin/drupal or ./vendor/bin/drush now. But I want to execute the commands drupal or drush directly from the project root or web subdirectory, not through  ./vendor/bin/drupal or  ./vendor/bin/drush. Any suggestions? I see drupal console launcher,do i have to install it?. If the composer project didn't install drupal console and drush, I will install them myself. But it includes them, if I install them again, I'm afraid there will be conflicts. I don't know how drupal console and drush work in this composer project and there are very few instructions. Thanks very much for your help.

**Comment by luckyaffer** [comment]
@javaskater I work on Ubuntu 16.04.3 LTS. I just want to try if drupal console or drush can run, so I executed commands just like drupal or drush to test.

**Comment by fafnirical** [comment]
For Drush, you can install the [Drush Launcher](https://github.com/drush-ops/drush-launcher).
For Drupal Console, you can install the [Drupal Console Launcher](https://hechoendrupal.gitbooks.io/drupal-console/content/en/getting/launcher.html).

**Comment by luckyaffer** [comment]
@fafnirical Thanks. Yes! I made it. It's ok now.
