### ISSUE TITLE
Post install issues

### ISSUE THREAD

**Issue by dougouverson** [drupal-composer/drupal-composer-project#339]
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
alchemy/zippy suggests installing guzzle/guzzle (To use the GuzzleTeleporter with Guzzle 3)
zendframework/zend-feed suggests installing zendframework/zend-cache (Zend\Cache component, for optionally caching feeds between requests)
zendframework/zend-feed suggests installing zendframework/zend-db (Zend\Db component, for use with PubSubHubbub)
zendframework/zend-feed suggests installing zendframework/zend-http (Zend\Http for PubSubHubbub, and optionally for use with Zend\Feed\Reader)
zendframework/zend-feed suggests installing zendframework/zend-servicemanager (Zend\ServiceManager component, for easily extending ExtensionManager implementations)
zendframework/zend-feed suggests installing zendframework/zend-validator (Zend\Validator component, for validating email addresses used in Atom feeds and entries when using the Writer subcomponent)
symfony/validator suggests installing symfony/intl ()
symfony/serializer suggests installing symfony/property-info (To deserialize relations.)
symfony/serializer suggests installing symfony/property-access (For using the ObjectNormalizer.)
symfony/class-loader suggests installing symfony/polyfill-apcu (For using ApcClassLoader on HHVM)
easyrdf/easyrdf suggests installing ml/json-ld (~1.0)
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
phpdocumentor/reflection-docblock suggests installing dflydev/markdown (~1.0)
phpdocumentor/reflection-docblock suggests installing erusev/parsedown (~1.0)
pear/console_table suggests installing pear/Console_Color2 (>=0.1.2)
drush/drush suggests installing drush/config-extra (Provides configuration workflow commands, such as config-merge.)
behat/mink suggests installing behat/mink-selenium2-driver (slow, but JS-enabled driver for any app (requires Selenium2))
behat/mink suggests installing behat/mink-zombie-driver (fast and JS-enabled headless driver for any app (requires node.js))
sebastian/global-state suggests installing ext-uopz (*)
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)

**Comment by dougouverson** [comment]
Also:

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

**Comment by rodrigoaguilera** [comment]
From the first me message I can only see suggestions to install other packages. nothing to worry about. 

The second message can happen because the network is unstable. If you can reproduce it consistently then I think a bit more info is needed to troubleshoot like the exact commando you are using.

**Comment by dougouverson** [comment]
I'm curious: why suggest installation of additional packages when there's nothing to worry about? I'm not questioning your statement, just curious.

Regarding the network performance issue: I'm using a 2GB box at DigitalOcan connected to ServerPilot for basic server configuration (LAMP + NGINX etc) so I'm not sure I keep getting this.

**Comment by FatherShawn** [comment]
[Suggestions](https://getcomposer.org/doc/04-schema.md#suggest) are a part of the `composer.json` schema.  Package developers may suggest other packages and you will see such any time you install a package with Composer that contains such suggestions.

**Comment by dougouverson** [comment]
Hmmm. I can understand the value of a suggestion, but not sure how to evaluate and make a judgement call.

**Comment by webflo** [comment]
You don't have to install any of the suggested packages. Its a feature of composer. Nothing to do here.
