### ISSUE TITLE
Failed to decode response: zlib_decode(): data error

### ISSUE THREAD

**Issue by dougouverson** [drupal-composer/drupal-composer-project#341]
3 times out of 10 I get this error message when installing Drupal 8 or Drupal 8 modules

Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

Commands I use to produce error:

composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction
and
composer require drupal/[modulename]

Not sure where to report. Both DigitalOcean and ServerPilot indicate its a "remote server(s)" issue.

**Comment by scottsawyer** [comment]
I am fairly certain this is an issue with DigitalOcean's IPv6, I am currently working a ticket with them about the same issue.  Is your droplet in NY3 by chance?

The link provided by composer indicates that it could be IPv6 and suggests disabling to confirm.  You can test by running:
`sudo sysctl net.ipv6.conf.all.disable_ipv6=1`
This works well for me.

**Comment by dougouverson** [comment]
Yes, it is in NY3

I reopened my ticket with DO and shared your message. Hopefully, we can get issues solved asap.

I won't do anything until I hear from them.

Thanks for getting right on this.

Best,

**Comment by dougouverson** [comment]
I ran the command to no effect?

Would I need to restart any service or reboot server?

**Comment by dougouverson** [comment]
Never could get DigitalOceal to own this issue - FYI. Not sure what system is causing this error; I would think that many would be having issue?

**Comment by scottsawyer** [comment]
I am not getting the issue any longer, I had to explicitly set up IPv6 on my droplet.  

https://www.digitalocean.com/community/tutorials/how-to-enable-ipv6-for-digitalocean-droplets

It seems really strange to me that I had never received that message, then suddenly at least 2 droplets got the same error.  But since this tutorial fixes the error, I would say it's not a composer / drupal-project issue.

**Comment by webflo** [comment]
I agree with @scottsawyer. This issue is composer/packagist.com issue. Please open issue against composer if the problems persists.
