### ISSUE TITLE
How to lock a module to prevent it from being updated ?

### ISSUE THREAD

**Issue by tostinni** [drupal-composer/drupal-composer-project#342]
When using drush you can lock a module to prevent it being updated using a `.drush-lock-update` file.
Is it possible to have something similar using composer ?

**Comment by NielsSluijs** [comment]
In your composer.json the specific version you want can be set for a package, for instance use `composer require drupal/devel:1.2` (this will keep the version of the Devel module at 8.x-1.2).

For more information see https://getcomposer.org/doc/articles/versions.md#exact-version-constraint

Kind regards,

Niels

**Comment by webflo** [comment]
@NielsSluijs Thanks for helping out.

Composer has no such feature, but using an exact-version-constraint is a good way to lock down a dependency.
