### ISSUE TITLE
Drush not installed?

### ISSUE THREAD

**Issue by dougouverson** [drupal-composer/drupal-composer-project#346]
I installed a new instance this morning and got this message:

`The program 'drush' is currently not installed. To run 'drush' please ask your administrator to install the package 'drush'`

https://www.screencast.com/t/dxlUDNbGt1

I thought drush came along with this package?

**Comment by rodrigoaguilera** [comment]
with this template drush ends being installed to vendor/bin/drush

either you add that to the $PATH of the user that wants to execute drush or prefix it every time you use it with vendor/bin/

Or any other solution but this project does not install drush globally. Depends on the underlying infrastructure.

**Comment by NielsSluijs** [comment]
I can recommend using [Drush Launcher](https://github.com/drush-ops/drush-launcher) as it provides a clean solution (wrapper) to using Drush

**Comment by dougouverson** [comment]
Thank you, both for the prompt reply.

I ended up running following command as root:

`wget -O /usr/local/bin/drush http://files.drush.org/drush.phar && chmod 755 /usr/local/bin/drush`
