### ISSUE TITLE
Add all scaffolded files to .gitignore

### ISSUE THREAD

**Issue by geek-merlin** [drupal-composer/drupal-composer-project#349]
As scaffolding files is part of the build process, i wonder if we should add those files to .gitignore. I suppose these are:
```
/web/.csslintrc
/web/.editorconfig
/web/.eslintignore
/web/.eslintrc.json
/web/.gitattributes
/web/.htaccess
/web/robots.txt
/web/web.config
```

**Comment by webflo** [comment]
Not every build triggers the scaffold plugin. It runs only on package updates of ``drupal/core`` or if autoload.php is not present. We have some information about it in our FAQ. https://github.com/drupal-composer/drupal-project#should-i-commit-the-scaffolding-files

**Comment by geek-merlin** [comment]
Ah thanks! Facepalm: In fact i did read the whole .gitignore commit history for hints but not the FAQ. If more people ask like me we might add a hint in .gitignore...
