### ISSUE TITLE
what version of drupal will be installed and how do i alter it?

### ISSUE THREAD

**Issue by laurencefass** [drupal-composer/drupal-composer-project#354]
`composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction
`

what version of drupal will be installed and how do i alter it?

thanks

**Comment by weitzman** [comment]
The one thats specified in composer.json (currently 8.4). See https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L23. In order to change the version, clone this repo, change that line in composer.json, and run composer install. There are other ways as well.

**Comment by andriokha** [comment]
See also #368
