### ISSUE TITLE
drupal-composer/drupal-project is forcing drush 9.1

### ISSUE THREAD

**Issue by laurencefass** [drupal-composer/drupal-composer-project#355]
latest drupal-composer/drupal-project is forcing drush 9.1 which means no more drush dl, which still works in a lot of cases. how can i change this composer installation to work with drush 8?

thanks

**Comment by weitzman** [comment]
See my prior response. You need to edit composer.json and change the Constraint for drupal/core.

**Comment by weitzman** [comment]
I should add that there is a policy in this project that prevents `dl` usage. You'd have to remove that. Note that it doesn't make sense to use this project is you are going to use `drush dl`.
