### ISSUE TITLE
how do i enable modules from the command line using drush 9+

### ISSUE THREAD

**Issue by laurencefass** [drupal-composer/drupal-composer-project#356]
this project no longer offers drush en functionality. how do i enable modules from the command line without going through the UI.

**Comment by FatherShawn** [comment]
`composer require drupal/module_name` at the simplest.  You can follow the module name with a version if you don't want the latest.

**Comment by rodrigoaguilera** [comment]
@laurencefass You are opening a lot of issues in this project that just require some reading of the composer docs.

This project will install drush into vendor/bin/drush.

Drush never stopped supporting the "en" command.

**Comment by laurencefass** [comment]
sure which composer docs. there's a lot of changes being made and i thank you for your patience.
