### ISSUE TITLE
Should we enforce PHP 5.5/5.6 as a minimum ?

### ISSUE THREAD

**Issue by tostinni** [drupal-composer/drupal-composer-project#359]
Drupal 8 supports PHP 5.5.9 as a minimum version (see [Drupal 8 PHP requirements](https://www.drupal.org/docs/8/system-requirements/drupal-8-php-requirements)), however in `composer.json` there is no PHP version which can led to conflicts when you upgrade some packages.

For example this issue [Doctrine/Common 2.8 requires PHP ~7.1](https://www.drupal.org/project/drupal/issues/2898119) expose this problem when working in a PHP 5.5/5.6 environment.
One solution proposed there is to add `"platform": {"php": "5.6"}` to `composer.json`.

Should we consider doing the same for drupal-composer ?

**Comment by pfrenssen** [comment]
I think adding the platform version this is a good idea. It can be confusing to people that are new to composer that it will use the PHP version _of the machine that runs the update command_ as a minimum in the `composer.lock` file. If we put it in we will achieve two goals:

* Our users will end up with a build that actually works on an environment that meets the minimum requirements.
* We demonstrate the proper way to change the minimum PHP version in a way that best matches people's expectations.

**Comment by tostinni** [comment]
Sorry for the multiple commits, I was making some tests and fixing some typos.

I was thinking adding this directly to `composer.json` but it could be too restrictive to target PHP 5.5.9, so I added a FAQ section to `README.md`.

**Comment by webflo** [comment]
Thanks @tostinni
