### ISSUE TITLE
Is GIT command line download broken?

### ISSUE THREAD

**Issue by pkosenko** [drupal-composer/drupal-composer-project#364]
$ git clone https://github.com/drupal-composer/drupal-project.git
Cloning into 'drupal-project'...
error: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version while accessing https://github.com/drupal-composer/drupal-project.git/info/refs?service=git-upload-pack
fatal: HTTP request failed

**Comment by fafnirical** [comment]
Looks like it might be related to this? https://githubengineering.com/crypto-deprecation-notice/

**Comment by webflo** [comment]
@pkosenko I think @fafnirical is right, this issue is related to github infrastructure and your local system. You should have this issues with any other git repo from github.

@fafnirical Thanks for helping out :)

**Comment by pkosenko** [comment]
The problem resolved itself when I updated to
bash, version 4.4.19(1)-release (x86_64-pc-msys)
