### ISSUE TITLE
Installing specific core version

### ISSUE THREAD

**Issue by Jose3212** [drupal-composer/drupal-composer-project#368]
Hi!
I was using composer to install drupal as you put in the readme, but I see it install 8.5-beta01 there is no way to configure it in order to install for example drupal-core 8.4.5?
Regards,
Jose

**Comment by FatherShawn** [comment]
Yes.  Have a look at [composer.json](https://github.com/drupal-composer/drupal-project/blob/56936005b3ab8d13d05302e28559a353475e11dd/composer.json#L23)  and change the version requirement for `drupal/core` and `webflo/drupal-core-require-dev` to "8.4.5".  You will need to delete the `composer.lock` and probably the vendor directory and then `composer install again`.

**Comment by webflo** [comment]
@FatherShawn Thanks! Thats the correct answer.

**Comment by FatherShawn** [comment]
@webflo Thank you for your work on this project.  It makes my life easier everyday and inspired the docker based local dev setup (https://github.com/digitalpulp/ballast) we are using at Digital Pulp.

**Comment by andriokha** [comment]
This works for me to create a new project with a specific version (eg. `^8.5`) of Drupal from the command line, hth.
```bash
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction --no-install
cd some-dir
composer require --no-update drupal/core:^8.5
composer require --no-update --dev webflo/drupal-core-require-dev:^8.5
composer install [--no-dev]
```
