### ISSUE TITLE
running composer update drupal/core --with-dependencies only updates modules and vendor files.

### ISSUE THREAD

**Issue by dougmorin** [drupal-composer/drupal-composer-project#369]

**Comment by dougmorin** [comment]
I manually changed the version of drupal from within the composer file to ~8.5, that told me that symfony/yaml had a conflict with symfony/console, and symfony/console had a conflict with symfony/process.  updating process, then console, then yaml seemed to fix it.  Why doesn't this just happen automatically?

**Comment by FatherShawn** [comment]
It's my understanding that is what the `--with-dependencies` flag is for.  It looks like the update command for this round is `composer update drupal/core drupal/console webflo/drupal-core-require-dev --with-dependencies`

See [composer why/why not](https://getcomposer.org/doc/03-cli.md#depends-why-) [synonyms of `composer depends` and `composer prohibits`] these are your tools for finding the package that's blocking your upgrade.

**Comment by geerlingguy** [comment]
See also:

  - [composer fail to upgrade from 8.4.4 to 8.5.0-alpha1](https://www.drupal.org/project/drupal/issues/2943546) (good info throughout that issue)
  - [Updating packages with composer and knowing what to update](https://drupal.stackexchange.com/a/258281/26)

But basically, what @FatherShawn said—though see the [Updating Drupal Core](https://github.com/drupal-composer/drupal-project#updating-drupal-core) docs in this project's README. It mentions the command:

    composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies

**Comment by ghost** [comment]
When I run `composer outdated` I get this list of Symfony packages that need updating:

```
ymfony-cmf/routing                   1.4.1              2.0.3              Extends the Symfony2 routing component for dynamic routes and chaining sever...
symfony/browser-kit                   v3.4.6             v4.0.6             Symfony BrowserKit Component
symfony/config                        v3.4.6             v4.0.6             Symfony Config Component
symfony/console                       v3.4.6             v4.0.6             Symfony Console Component
symfony/css-selector                  v3.4.6             v4.0.6             Symfony CssSelector Component
symfony/debug                         v3.4.6             v4.0.6             Symfony Debug Component
symfony/dependency-injection          v3.4.6             v4.0.6             Symfony DependencyInjection Component
symfony/dom-crawler                   v3.4.6             v4.0.6             Symfony DomCrawler Component
symfony/event-dispatcher              v3.4.6             v4.0.6             Symfony EventDispatcher Component
symfony/filesystem                    v3.4.6             v4.0.6             Symfony Filesystem Component
symfony/finder                        v3.4.6             v4.0.6             Symfony Finder Component
symfony/http-foundation               v3.4.6             v4.0.6             Symfony HttpFoundation Component
symfony/http-kernel                   v3.4.6             v4.0.6             Symfony HttpKernel Component
symfony/phpunit-bridge                v3.4.6             v4.0.6             Symfony PHPUnit Bridge
symfony/process                       v3.4.6             v4.0.6             Symfony Process Component
symfony/routing                       v3.4.6             v4.0.6             Symfony Routing Component
symfony/serializer                    v3.4.6             v4.0.6             Symfony Serializer Component
symfony/translation                   v3.4.6             v4.0.6             Symfony Translation Component
symfony/validator                     v3.4.6             v4.0.6             Symfony Validator Component
symfony/var-dumper                    v3.4.6             v4.0.6             Symfony mechanism for exploring and dumping PHP variables
symfony/yaml                          v3.4.6             v4.0.6             Symfony Yaml Component
```

I'm seeing this message when trying to update using this command:

`composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies`

```
Package "symfony/*" listed for update is not installed. Ignoring.
```

Is there something wrong with my setup?

**Comment by TipiT** [comment]
I was thinking about asking almost the same thing and then I found https://www.jeffgeerling.com/blog/2018/updating-drupalcore-composer-drupal-core-doesnt-update and from the bottom the links to previous discussions. Now I understand why-not (alias prohibits). :)

**Comment by webflo** [comment]
We updated the docs around core updates a while ago. https://github.com/drupal-composer/drupal-project#updating-drupal-core

Please try again and open an new issue if its still an issue.
