### ISSUE TITLE
Deployment guide?

### ISSUE THREAD

**Issue by fallenturtle** [drupal-composer/drupal-composer-project#373]
Is there a guide that can be used for deploying a Drupal 8 dev site built locally using this project to a production server?

**Comment by FatherShawn** [comment]
@fallenturtle You could look over the methods we use for deployment in [Ballast](https://packagist.org/packages/digitalpulp/ballast), which is uses this project for a starting point: https://github.com/digitalpulp/ballast/blob/0d655411b9375a561eb9073afc76d95c07109689/scripts/robo/RoboFile.php#L719

Along with https://github.com/digitalpulp/ballast/blob/master/codeship-steps.yml

We are using those methods to deploy regularly on several projects.

**Comment by normanlolx** [comment]
Inactive.
