### ISSUE TITLE
PolicyCommands not picked up

### ISSUE THREAD

**Issue by morenstrat** [drupal-composer/drupal-composer-project#377]
The validation hooks in drush/Commands/PolicyCommands are not picked up. I'm not sure if this is an issue with drupal-composer/drupal-project or Drush itself. I tested the policy commands by moving drush/Commands/PolicyCommands.php to vendor/drush/drush/src/Commands and there they work (with the proposed changes from #376).

**Comment by webflo** [comment]
ping @weitzman @greg-1-anderson 

It works if the namespace in PolicyCommands is just "Drush". Should we change it. Or is this a bug CommandFileDiscovery? Thanks!

```patch
diff --git a/drush/Commands/PolicyCommands.php b/drush/Commands/PolicyCommands.php
index b5bdec6..6eabaa1 100644
--- a/drush/Commands/PolicyCommands.php
+++ b/drush/Commands/PolicyCommands.php
@@ -1,6 +1,6 @@
 <?php
 
-namespace Drush\Commands;
+namespace Drush;
 
 use Consolidation\AnnotatedCommand\CommandData;
 use Drush\Commands\DrushCommands;
```

**Comment by greg-1-anderson** [comment]
This is an unfortunate inconsistency in Drush. The namespace for the file `src/Commands/core/CoreCommands.php` is `Drush\Commands\core`, so for consistency, the namespace of the file `drush/Commands/PolicyCommands` should be `Drush\Commands`, but Drush expects it to simply be `Drush`.

I think this was a mistake.

Anyway, not sure about the best fix. I'm not sure if it would be easy (or advisable) to accept both. We'd break working commandfiles if we just changed it to `Drush\Commands`.

**Comment by weitzman** [comment]
I think _both_ is a good answer here.

**Comment by weitzman** [comment]
Our docs say that Drush\Commands is right - https://github.com/drush-ops/drush/pull/3367/files

**Comment by weitzman** [comment]
[Now fixed in Drush](https://github.com/drush-ops/drush/pull/3518) - use Drush/Commands namespace. We may provide backward compat for folks that used \Drush. TBD.
