### ISSUE TITLE
D7:  Attempting to patch Drupal Core blows away the web directory

### ISSUE THREAD

**Issue by lhridley** [drupal-composer/drupal-composer-project#378]
We have a D7 project that is managed with Composer, and has been for some time.  We recently switched this project to the drupal-project composer files, and implemented some changes to a custom composer management process to solve some issues we were encountering, one of which was applying patches to Drupal projects.  The patch process for contrib modules has been working flawlessly.

We just encountered an unexpected issue when we attempted to patch Drupal Core recently by backporting the recent security update to the version of Drupal for this project (we're currently refactoring functionality that is impacted by a previous core update).  

The patch process deleted the web directory, including all files in the sites directory
- Everything in the sites/default directory was deleted, including the files directory, and the settings.php file
- All module, library and theme code in the sites/all directory was deleted

That was most unexpected.

This is in spite of having these directories specified in "preserve-paths" (see snippet below, note this project uses "www" instead of "web" for the web root):

```
"preserve-paths": [
            "www/sites/all/libraries",
            "www/sites/all/modules/custom",
            "www/sites/all/modules/features",
            "www/sites/all/themes/custom",
            "www/sites/all/translations",
            "www/sites/default",
            "www"
        ],
```

I searched through the issue queue, and located this issue, that appears to be related, that was closed because the initiator could not provide details to reproduce the issue.
#299 

I'm currently looking at a workaround to apply patches to core through post-install-cmd script, but applying core patches in this manner defeats the purpose of using composer to manage patches and us the composer.json file to track the patches applied for a project.

Any insight would be appreciated.

**Comment by lhridley** [comment]
Update:  This appears to be related to:  https://github.com/cweagans/composer-patches/issues/42

After reading through the issue, I tried replacing cweagans/composr-patces with Seb Corbin's fork:

https://github.com/SebCorbin/composer-patches

This unfortunately did not work as the core patch was not applied.

**Comment by lhridley** [comment]
I'm doing a bit of a brain dump here, because I'm trying to figure out how to maintain the integrity of the composer extra patches area as the source of all applied patches, and preserve the application of the patches.

It seems to me that the process of removing the library that is the subject of patching so that any new patches can be applied cleanly is fundamentally flawed, which is what cweagans/composer-patches does.  That library uses both git and patch to systematically apply patches that are included in the composer.json file.  Part of the patch process is to create a PATCHES.txt file with information about the applied patches for each subject library, and place that PATCHES.txt file in the root directory of the library being patched.

It seems to me that, for an existing project, a more reasonable, less destructive approach would be to gather the PATCHES.txt files that were generated when patches were previously applied, read the source information for each patch from those files, and systematically revert the previously applied patches before attempting to apply the newly gathered patches from the composer.lock file.  Better yet, when you gather the previously applied patches from the PATCHES.txt file, compare the source to the patches gathered from composer.json -- if they match, remove the patch from the gathered patches and move on; if they don't, revert the patch from the PATCHES.txt file.  Once all previously applied patches have been evaluated and either removed from the gathered patches list or reverted, then the patches remaining in the gathered patches list would be applied, and any PATCHES.txt files updated and/or created.

This would eliminate the need to "destroy" the existing library which, for Drupal 7 core patching purposes, would preserve the sites directory.

**Comment by jcnventura** [comment]
@lhridley Can you try to update your composer.json with ALL the changes in https://github.com/drupal-composer/drupal-project/blob/7.x/composer.json

You should add the "patches": "cweagans/composer-patches" section, and also the contrib modules to "preserve-paths".

My D7 site includes patches to core and to contrib modules, and the update to 7.58 went fine.

**Comment by jcnventura** [comment]
Closing the issue due to lack of reply.
