### ISSUE TITLE
Composer installation hangs at 'Installing drupal/core (8.5.1):'

### ISSUE THREAD

**Issue by MrPaulDriver** [drupal-composer/drupal-composer-project#381]
Ubuntu 18.04
Drupal VM

Using the recommended method of 'composer create-project', but finding that installation hangs at 'Installing drupal/core (8.5.1):'

What am I doing wrong?

After timing out the following error message is displayed in the terminal:

> The process "unzip -qq  'web/core/04ff643aed033a3fcba27fe4b31b14e0' -d '/var/www/drupalvm-8/sites/drupalproject/vendor/composer/19b087bf'" exceeded the timeout of 300 seconds. The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems) Unzip with unzip command failed, falling back to ZipArchive class

After a long delay, another error is printed:

> Failed to download drupal/core from dist: Could not delete /var/www/drupalvm-8/sites/drupalproject/web/core/.nfs00000000018609f000000001: Now trying to download from source

After another long delay, composer appear to resume but does not complete the process completely.

**Comment by webflo** [comment]
@geerlingguy Hi, could you help to troubleshoot this issue?

**Comment by geerlingguy** [comment]
It looks like an NFS issue. I know Ubuntu 17.04 and 18.04 have been flaky with NFS, you might need to destroy the VM, reinstall the NFS system packages, and try again. And maybe stick to Ubuntu 16.04 or something like Fedora on the host :)

**Comment by webflo** [comment]
Thx for the quick response

Jeff Geerling <notifications@github.com> schrieb am Sa., 7. Apr. 2018,
18:37:

**Comment by MrPaulDriver** [comment]
Thank you both for the quick replies. Great support.

**Comment by jcnventura** [comment]
I just had this also, but I don't believe it's related to the project. In my case it was a pair of NFS files inside the thunder profile.

**Comment by usmanjutt841** [comment]
> It looks like an NFS issue. I know Ubuntu 17.04 and 18.04 have been flaky with NFS, you might need to destroy the VM, reinstall the NFS system packages, and try again. And maybe stick to Ubuntu 16.04 or something like Fedora on the host :)

I'm using the 16.04 but still facing the same issue

`- Installing drupal/core (8.6.7): Loading from cache
^[[D    The process "unzip -qq  'html/core/88bb02c02ef80da71d9f3999cd643899' -d '/var/www/drupalvm/social/vendor/composer/17378066'" exceeded the timeout of 300 seconds.
    The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems)
    Unzip with unzip command failed, falling back to ZipArchive class`
