### ISSUE TITLE
Add Drupal console and Drush in Composer scripts

### ISSUE THREAD

**Issue by ankitjain28may** [drupal-composer/drupal-composer-project#387]
Drupal-project itself downloads drupal console and drush locally on the system which is in the `vendor/bin/ directory` and we need to access this file through `vendor\bin\drupal`, So, It will be better if we add these in composer scripts in composer.json like-
```
"scripts": {
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "drupal": "drupal"
    },
```
and provide `composer drupal` command for end user to directly access drupal without going through vendor directory.

**Comment by davereid** [comment]
Are you aware of the ability to do `composer exec [command to run from inside /vendor/bin]`? For example `composer exec drupal`.

**Comment by ankitjain28may** [comment]
@davereid Thanks for letting me know that, i dont know about this. But i am not getting any output when i am running with exec.

**Comment by weitzman** [comment]
I dont see much value here. whats wrong with running `vendor/bin/drush` , `vendor/bin/phpunit`, etc? your suggestion isnt any fewer chars.

**Comment by webflo** [comment]
I could help in some situations, but its nothing i would like to add to the project as a default.

Thanks @ankitjain28may

**Comment by cmutunga** [comment]
What could be the issue here, please help
Executing 
_`composer require drupal/console`_
Runs fine but this message showed
_```
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
```_

Then Executing 
`C:\Users\charl\Sites\devdesktop\Sandbox> vendor\bin\drupal`

I get this error 
_`PHP Fatal error:  Uncaught RuntimeException: Your environment or operation system isn't supported in C:\Users\charl\Sites\devdesktop\Sandbox\vendor\webmozart\path-util\src\Path.php:257_`
