### ISSUE TITLE
Script DrupalProject\composer\ScriptHandler::createRequiredFiles handling the post-install-cmd event terminated with an exception

### ISSUE THREAD

**Issue by dougouverson** [drupal-composer/drupal-composer-project#391]
https://www.screencast.com/t/Xy9fCK4PX

New `composer install` a few minutes ago produced a couple errors. Not sure if they are related.

Ran `composer create-project drupal-composer/drupal-project:8.x-dev drupal --stability dev --no-interaction`

Errors:

> Script DrupalProject\composer\ScriptHandler::createRequiredFiles handling the post-install-cmd event terminated with an exception

> [ErrorException]
> Zend OPcache API is restricted by “restrict_api” configuration directive

**Comment by dougouverson** [comment]
I checked with ServerPilot who manages LAMP stack to see if the issue might be related to composer version. My server is running 1.6.4. Their input was that this issue was not related to composer.

Here's their response:

> Hi Doug,

> That doesn't appear to be related to Composer. Instead, it's due to the PHP setting opcache.restrict_api > that is enabled on your server for PHP 7.2+.

> To disable opcache.restrict_api, SSH into your server as "root" and edit the file:

> /etc/php7.2-sp/conf.d/opcache.ini

> and add a "#" before the line:

> opcache.restrict_api=/restricted

> and the restart PHP with:

> sudo service php7.2-fpm-sp restart

> You may also want to track down the developer of the code that isn't properly checking that setting so that they can fix the bug on their side (properly written PHP code checks that setting before relying on the opcache API functions). It's unlikely it's in core Drupal but instead in some of the other code that you have being installed with Composer.

> Best,
> Justin

I was not planning on messing with PHP settigns - fyi.

**Comment by dougouverson** [comment]
Changed PHP version to 7.1 - same result.

**Comment by dougouverson** [comment]
Doesn't seem to affect the site, as I was able to run install.php without issue. I'll watch this closely and share what I can.

**Comment by webflo** [comment]
```Zend OPcache API is restricted by “restrict_api” configuration directive``` blocks calls to various ```opcache_* ``` functions. 

 ```
opcache_compile_file()
opcache_get_configuration()
opcache_get_status()
opcache_invalidate()
opcache_reset()
```

``::createRequiredFiles`` calls ``drupal_rewrite_settings`` to prepare settings.php for installation. ``drupal_rewrite_settings`` calls ``\Drupal\Component\Utility\OpCodeCache::invalidate``.

You could file a core bug for this. This is out of scope for this project imo.
