### ISSUE TITLE
How to install require-dev packages in core (ie, phpunit)?

### ISSUE THREAD

**Issue by mikestefanello** [drupal-composer/drupal-composer-project#395]
I cannot get any of the require-dev packages listed in web/core/composer.json to install (ie, phpunit). What is the trick there?

**Comment by weitzman** [comment]
You have to `composer require` them manually since composer ignores dev packages from a project's dependencies.

**Comment by webflo** [comment]
Or you require https://packagist.org/packages/webflo/drupal-core-require-dev. It is a metapackage and contains all dev dependencies from drupal core.

**Comment by webflo** [comment]
```webflo/drupal-core-require-dev``` has been added as a default.
