### ISSUE TITLE
composer create-project dead on downloading phpunit/dbunit 

### ISSUE THREAD

**Issue by huaweichen** [drupal-composer/drupal-composer-project#396]
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction

AWS, PHP set 1G memory.

**Comment by webflo** [comment]
1 GB of memory could be the limiting factor. I had to increase the memory limit in Travis CI recently because 1.5 GB was not enough in conjunction with PHP 5.6.

Please read https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors
