### ISSUE TITLE
Cant update to 8.5.4

### ISSUE THREAD

**Issue by FNGR2911** [drupal-composer/drupal-composer-project#399]
I don't know why, but composer is telling me there is nothing to update or install in drupal/core. But composer outdated is showing me the update. 

```bash
mattis-mbp:
→ composer outdated drupal/*
drupal/core 8.5.3 8.5.4 Drupal is an open source content management platform powering millions of websites and applications.

mattis-mbp:
→ composer update drupal/core --with-dependencies
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
> DrupalProject\composer\ScriptHandler::createRequiredFiles
```
Whats wrong?

**Comment by FatherShawn** [comment]
Can you also post your `composer.json`?

**Comment by webflo** [comment]
@FNGR2911 Please read the docs about updating core at https://github.com/drupal-composer/drupal-project#updating-drupal-core

**Comment by FNGR2911** [comment]
Okay, thank you, didn't noticed you changed the command to update in the last months!
