### ISSUE TITLE
Updating drupal-project itself

### ISSUE THREAD

**Issue by hanoii** [drupal-composer/drupal-composer-project#400]
Although this was never an issue, I like to come back at this project and keep my project up to date with the changes here, however, that's all very manual. Is there a recommended approach on doing it? Would it make sense to think of a better way of updating itself or the like.

Just wondering what your thoughts on this are and how important keeping the related files up to date you think it is.

**Comment by FatherShawn** [comment]
If this project is _upstream_ to yours in essence, one approach is to use github's [built in patch](https://blog.github.com/2011-10-21-github-secrets/#diff-patch) building process on commits to this project and then apply the patch to yours:

Use the compare url to diff the last commit you updated to current HEAD, such as:
https://github.com/drupal-composer/drupal-project/compare/6be94f447e67009a385959ef57f58163d651e052...8.x

When you have what you like, add `.patch` to the end of the url:

https://github.com/drupal-composer/drupal-project/compare/6be94f447e67009a385959ef57f58163d651e052...8.x.patch

**Comment by webflo** [comment]
@FatherShawn Thanks for your support!
