### ISSUE TITLE
Composer can not install on PHP 5.5.x (tested 5.5.13)

### ISSUE THREAD

**Issue by joshua-graham-adelphi** [drupal-composer/drupal-composer-project#403]
Drupal 8 supports PHP version 5.5.9+  so not sure why failing. error seems cryptic.

Output:
`joshua.graham@JoshG-PC MSYS /c/temp
$ php -v
PHP 5.5.38 (cli) (built: Jul 20 2016 11:16:06)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

joshua.graham@JoshG-PC MSYS /c/temp
$ composer create-project drupal-composer/drupal-project:8.x-dev build --stability dev --no-interaction
    1/3:        http://packagist.org/p/provider-latest$43a2f7fafbde6ad0f0dbae48d700fbd8e8335fcad7743483f204bd035b3c1141.json
    2/3:        http://packagist.org/p/provider-2018-01$d946b6b2a4543c7090e787add01e13141e21835faa302c4ddeaf7b31d2075286.json
    3/3:        http://packagist.org/p/provider-2018-04$d90f1bb6b051f4a025a0fa4c72b091331255cb98884c3c69a58434a218852a82.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Installing drupal-composer/drupal-project (8.x-dev 04138e374bdeeb838020c2a1c4b0591118686d45)
  - Installing drupal-composer/drupal-project (8.x-dev 04138e3): Cloning 04138e374b from cache
Created project in build
    1/1:        http://packagist.org/p/provider-latest$52a779c1040bbb4c55042040582cf72c79bfe8b62b7cc4a04cee176a87e9906f.json
    Finished: success: 1, skipped: 0, failure: 0, total: 1
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drupal/core 8.5.4
    - Conclusion: don't install drupal/core 8.5.3
    - Conclusion: don't install symfony/dependency-injection v3.4.11
    - Conclusion: don't install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.7|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.8|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.9|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.10|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.6
    - Conclusion: don't install symfony/dependency-injection 3.4.x-dev
    - Conclusion: don't install symfony/dependency-injection v3.4.4
    - Conclusion: don't install symfony/dependency-injection v3.4.3
    - Conclusion: don't install symfony/config v2.8.40
    - Conclusion: don't install symfony/dependency-injection v3.4.5|install symfony/config v2.8.40|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.2
    - Conclusion: don't install symfony/dependency-injection v3.4.1
    - Conclusion: don't install symfony/config v2.8.39
    - Conclusion: don't install symfony/dependency-injection v3.4.0
    - Conclusion: don't install symfony/config v2.8.37|install symfony/dependency-injection v3.4.0|install symfony/dependency-injection v3.4.1|install symfony/dependency-injection v3.4.2|install symfony/dependency-injection v3.4.3|install symfony/dependency-injection v3.4.4|install symfony/dependency-injection v3.4.5
    - Conclusion: don't install symfony/config v2.8.38
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA3|install symfony/config v2.8.38
    - Conclusion: don't install symfony/dependency-injection v3.4.0-RC2|install symfony/config v2.8.37|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.0-RC1|install symfony/config v2.8.37|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA4
    - Conclusion: don't install symfony/config v2.8.36|install symfony/dependency-injection v3.4.0-BETA3|install symfony/dependency-injection v3.4.0-BETA4|install symfony/dependency-injection v3.4.0-RC1|install symfony/dependency-injection v3.4.0-RC2
    - Installation request for drupal/core ~8.5.3 -> satisfiable by drupal/core[8.5.3, 8.5.4, 8.5.x-dev].
    - Installation request for drush/drush ^9.0.0 -> satisfiable by drush/drush[9.0.0, 9.0.0-alpha1, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-beta4, 9.0.0-beta5, 9.0.0-beta6, 9.0.0-beta7, 9.0.0-beta8, 9.0.0-beta9, 9.0.0-rc1, 9.0.0-rc2, 9.1.0, 9.2.0, 9.2.1, 9.2.2, 9.2.3, 9.3.0, 9.x-dev].
    - drupal/core 8.5.x-dev requires symfony/dependency-injection ~3.4.0 -> satisfiable by symfony/dependency-injection[3.4.x-dev, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA1
    - symfony/dependency-injection v3.4.0-BETA2 conflicts with symfony/config[v2.8.35].
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA2|install symfony/config v2.8.35|install symfony/config v2.8.36|install symfony/config v2.8.37|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41

joshua.graham@JoshG-PC MSYS /c/temp
$
`

**Comment by webflo** [comment]
Please check your php-extensions with "composer check-platform-reqs". Clone the git repo and run "composer check-platform-reqs" in the cloned directory.

**Comment by webflo** [comment]
Related to https://github.com/drupal-composer/drupal-project/issues/338

**Comment by joshua-graham-adelphi** [comment]
Coming back to this issue...

"composer check-platform-reqs" appears to not give any output. Doesn't appear to be same issue linked.

<details>
  <summary>Commandline</summary>
joshua.graham@JoshG-PC MSYS /c/Projects
$ cd /c/temp

joshua.graham@JoshG-PC MSYS /c/temp
$ mkdir drupal-composerphp5

joshua.graham@JoshG-PC MSYS /c/temp
$ git clone git@github.com:drupal-composer/drupal-project.git drupal-composerphp5
Cloning into 'drupal-composerphp5'...
remote: Counting objects: 975, done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 975 (delta 4), reused 14 (delta 4), pack-reused 959
Receiving objects: 100% (975/975), 253.95 KiB | 252.00 KiB/s, done.
Resolving deltas: 100% (435/435), done.

joshua.graham@JoshG-PC MSYS /c/temp
$ cd drupal-composerphp5/

joshua.graham@JoshG-PC MSYS /c/temp/drupal-composerphp5 (8.x)
$ php -v
PHP 5.5.38 (cli) (built: Jul 20 2016 11:16:06)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

joshua.graham@JoshG-PC MSYS /c/temp/drupal-composerphp5 (8.x)
$ composer check-platform-reqs

joshua.graham@JoshG-PC MSYS /c/temp/drupal-composerphp5 (8.x)
$ composer install
    1/9:        https://packages.drupal.org/8/drupal/provider-2017-2$601dfcfc2e6b5e0bd3d8ec264c5f05f12805f7e53feb2ba495603f8db9ea8761.json
    2/9:        https://packages.drupal.org/8/drupal/provider-2018-2$917354a7c97ae1785592da1bb86561bb5f4c674ba45312912577e73de248d928.json
    3/9:        https://packages.drupal.org/8/drupal/provider-2017-4$d2397a6675ba2bff38ce5f04f84cb22c62227ac6bf398476d68ba6e1a7232ae5.json
    4/9:        https://packages.drupal.org/8/drupal/provider-2015-3$84d8c556a8f01336dc4264cc4557466a11c808d237ef9e8d427befa16f1af84d.json
    5/9:        https://packages.drupal.org/8/drupal/provider-2016-2$af04b1ed153ab3c869a90878768e59ae62532349f2ec751cabdc5379f17b32d3.json
    6/9:        https://packages.drupal.org/8/drupal/provider-2017-1$d3a86a9d564e7fa5facc74973819fbcf362748555775563b3c504ce9fbb9d53f.json
    7/9:        https://packages.drupal.org/8/drupal/provider-2016-3$6adb2f66db28383a504de4ce9ee491cadaad6a7fe2d672807c51ca6d2c0080e7.json
    8/9:        https://packages.drupal.org/8/drupal/provider-2017-3$1af840ea1c99c54339b8d14a72613d2af8a55c1148e1b65cd21a12d58a17ace6.json
    9/9:        https://packages.drupal.org/8/drupal/provider-2018-1$a59db387a7a796357f89f944d8c5150718b84c15c2eb767f646e88bfba9e383e.json
    Finished: success: 9, skipped: 0, failure: 0, total: 9
    1/11:       http://packagist.org/p/provider-2018-07$cf8e95b7e87569d5ed1b197fa22a96df422ee5e0b527dbc89d6bd6508d890ce7.json
    2/11:       http://packagist.org/p/provider-archived$216205c00b7bfcb4d972a5a24f4aa8124a2f92a8135a4a00b794dbc35e4a56e6.json
    3/11:       http://packagist.org/p/provider-latest$e5103f260b5a312816724681f943d19477e119883e4f251ac930d9eddee29f62.json
    4/11:       http://packagist.org/p/provider-2013$498f1c8be86f3118f4725d6546c25e95c0e7d5441115f29ba97e728c4a36edee.json
    5/11:       http://packagist.org/p/provider-2018-01$2607e01f8cfab4cd6993048497b4a71f5c86ea411ede1c96079f72a8a5f48576.json
    6/11:       http://packagist.org/p/provider-2018-04$8b3fae9d469756c8d28fadc635aff98e741f42cc03b1010d95a5dcb1680fb8ff.json
    7/11:       http://packagist.org/p/provider-2014$f03d4875dae9bae9715a6dbf2696aafd6ff3deb10807f1ad66927d1a4a5b839f.json
    8/11:       http://packagist.org/p/provider-2017-10$b951e93200f036174349ec2fa8b2f2378e8b78c70f20486ef375ce34ac249903.json
    9/11:       http://packagist.org/p/provider-2015$f00435bafef1e2643ebd1c6a3208b8af3d17048df0857b527754a5073a726d84.json
    10/11:      http://packagist.org/p/provider-2016$da7ccee228205bda8f26d8943283178802bd6e685ae646c9f4a1e5c1078b3d60.json
    11/11:      http://packagist.org/p/provider-2017$739e2102e4c3d91675a11a825d133f91ee2a76b7e367bd977d290bc422ac0f0c.json
    Finished: success: 11, skipped: 0, failure: 0, total: 11
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install symfony/dependency-injection v3.4.12
    - Conclusion: don't install drupal/core 8.5.5
    - Conclusion: don't install drupal/core 8.5.4
    - Conclusion: don't install drupal/core 8.5.3
    - Conclusion: don't install symfony/config v2.8.42|don't install drupal/core 8.5.x-dev
    - Conclusion: don't install symfony/dependency-injection v3.4.5|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.7|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.9|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.10|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.11|install symfony/config v2.8.42
    - Conclusion: don't install symfony/config v2.8.41|don't install drupal/core 8.5.x-dev|install symfony/dependency-injection v3.4.10|install symfony/dependency-injection v3.4.11|install symfony/dependency-injection v3.4.5|install symfony/dependency-injection v3.4.7|install symfony/dependency-injection v3.4.9
    - Conclusion: don't install symfony/dependency-injection v3.4.4|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.3|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.6|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.8|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/config v2.8.40|don't install drupal/core 8.5.x-dev|install symfony/dependency-injection v3.4.10|install symfony/dependency-injection v3.4.11|install symfony/dependency-injection v3.4.3|install symfony/dependency-injection v3.4.4|install symfony/dependency-injection v3.4.5|install symfony/dependency-injection v3.4.6|install symfony/dependency-injection v3.4.7|install symfony/dependency-injection v3.4.8|install symfony/dependency-injection v3.4.9
    - Conclusion: don't install symfony/dependency-injection v3.4.2|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.0-RC2|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.1|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/config v2.8.39|don't install drupal/core 8.5.x-dev|install symfony/dependency-injection v3.4.0-RC2|install symfony/dependency-injection v3.4.1|install symfony/dependency-injection v3.4.10|install symfony/dependency-injection v3.4.11|install symfony/dependency-injection v3.4.2|install symfony/dependency-injection v3.4.3|install symfony/dependency-injection v3.4.4|install symfony/dependency-injection v3.4.5|install symfony/dependency-injection v3.4.6|install symfony/dependency-injection v3.4.7|install symfony/dependency-injection v3.4.8|install symfony/dependency-injection v3.4.9
    - Conclusion: don't install symfony/dependency-injection 3.4.x-dev|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.0|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/config v2.8.38
    - Conclusion: don't install symfony/dependency-injection v3.4.0-RC1|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Installation request for drupal/core ~8.5.3 -> satisfiable by drupal/core[8.5.3, 8.5.4, 8.5.5, 8.5.x-dev].
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA4
    - Conclusion: don't install symfony/config v2.8.36|don't install drupal/core 8.5.x-dev|install symfony/dependency-injection 3.4.x-dev|install symfony/dependency-injection v3.4.0|install symfony/dependency-injection v3.4.0-BETA4|install symfony/dependency-injection v3.4.0-RC1|install symfony/dependency-injection v3.4.0-RC2|install symfony/dependency-injection v3.4.1|install symfony/dependency-injection v3.4.10|install symfony/dependency-injection v3.4.11|install symfony/dependency-injection v3.4.2|install symfony/dependency-injection v3.4.3|install symfony/dependency-injection v3.4.4|install symfony/dependency-injection v3.4.5|install symfony/dependency-injection v3.4.6|install symfony/dependency-injection v3.4.7|install symfony/dependency-injection v3.4.8|install symfony/dependency-injection v3.4.9
    - Conclusion: don't install symfony/config v2.8.37|don't install drupal/core 8.5.x-dev|install symfony/dependency-injection 3.4.x-dev|install symfony/dependency-injection v3.4.0|install symfony/dependency-injection v3.4.0-BETA4|install symfony/dependency-injection v3.4.0-RC1|install symfony/dependency-injection v3.4.0-RC2|install symfony/dependency-injection v3.4.1|install symfony/dependency-injection v3.4.10|install symfony/dependency-injection v3.4.11|install symfony/dependency-injection v3.4.2|install symfony/dependency-injection v3.4.3|install symfony/dependency-injection v3.4.4|install symfony/dependency-injection v3.4.5|install symfony/dependency-injection v3.4.6|install symfony/dependency-injection v3.4.7|install symfony/dependency-injection v3.4.8|install symfony/dependency-injection v3.4.9
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA3|install symfony/config v2.8.36|install symfony/config v2.8.37|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Installation request for drush/drush ^9.0.0 -> satisfiable by drush/drush[9.0.0, 9.0.0-alpha1, 9.0.0-beta1, 9.0.0-beta2, 9.0.0-beta3, 9.0.0-beta4, 9.0.0-beta5, 9.0.0-beta6, 9.0.0-beta7, 9.0.0-beta8, 9.0.0-beta9, 9.0.0-rc1, 9.0.0-rc2, 9.1.0, 9.2.0, 9.2.1, 9.2.2, 9.2.3, 9.3.0, 9.x-dev].
    - symfony/dependency-injection v3.4.0-BETA1 conflicts with symfony/config[v2.8.30].
    - symfony/dependency-injection v3.4.0-BETA1 conflicts with symfony/config[v2.8.31].
    - symfony/dependency-injection v3.4.0-BETA1 conflicts with symfony/config[v2.8.32].
    - symfony/dependency-injection v3.4.0-BETA1 conflicts with symfony/config[v2.8.33].
    - symfony/dependency-injection v3.4.0-BETA1 conflicts with symfony/config[v2.8.34].
    - symfony/dependency-injection v3.4.0-BETA1 conflicts with symfony/config[v2.8.35].
    - drupal/core 8.5.x-dev requires symfony/dependency-injection ~3.4.0 -> satisfiable by symfony/dependency-injection[3.4.x-dev, v3.4.0, v3.4.0-BETA1, v3.4.0-BETA2, v3.4.0-BETA3, v3.4.0-BETA4, v3.4.0-RC1, v3.4.0-RC2, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9].
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA2|install symfony/config v2.8.36|install symfony/config v2.8.37|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42
    - Conclusion: don't install symfony/dependency-injection v3.4.0-BETA1|install symfony/config v2.8.30|install symfony/config v2.8.31|install symfony/config v2.8.32|install symfony/config v2.8.33|install symfony/config v2.8.34|install symfony/config v2.8.35|install symfony/config v2.8.36|install symfony/config v2.8.37|install symfony/config v2.8.38|install symfony/config v2.8.39|install symfony/config v2.8.40|install symfony/config v2.8.41|install symfony/config v2.8.42

joshua.graham@JoshG-PC MSYS /c/temp/drupal-composerphp5 (8.x)
$ composer
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.6.5 2018-05-04 11:44:59
[...]

joshua.graham@JoshG-PC MSYS /c/temp/drupal-composerphp5 (8.x)
$ php -m
[PHP Modules]
apc
apcu
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
json
libxml
mbstring
mcrypt
memcache
mhash
mongo
mysql
mysqli
mysqlnd
OAuth
odbc
openssl
pcre
PDO
pdo_mysql
Phar
Reflection
session
SimpleXML
soap
sockets
SPL
sqlite3
standard
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

</details>

**Comment by leymannx** [comment]
I must apologize upfront for the following heretical question:

Why on earth would you try to install Drupal 8 on a PHP version that reached end-of-life more than two years ago?

> A release that is no longer supported. Users of this release should upgrade as soon as possible, as they may be exposed to unpatched security vulnerabilities.

* [PHP Supported Versions](https://secure.php.net/supported-versions.php)
* [PHP Unsupported Branches](https://secure.php.net/eol.php)

While Drupal 8 still may support an outdated PHP version some dependencies listed in this Composer project may already have dropped it. I guess your best bet is to download the mere Zip on https://www.drupal.org/project/drupal and start your project from there (not recommended) or to upgrade your PHP version (recommended).
