### ISSUE TITLE
Attempting to update from 8.5.3 to 3.5.4 fails

### ISSUE THREAD

**Issue by MrPaulDriver** [drupal-composer/drupal-composer-project#407]
After running `composer update drupal/core webflo/drupal-core-require-dev symfony/* --with-dependencies` I am finding that the update fails, with the message below

- Updating behat/mink-selenium2-driver dev-master (93474c6 => d8adafd):     The package has modified files: M src/Selenium2Driver.php

I am not an expert and do not know what to try next. Any suggestions?

**Comment by bramvandenbulcke** [comment]
I had a similar error when updating to Drupal 8.5.6: 

`
Updating behat/mink-selenium2-driver dev-master (93474c6 => f4efaf5): The package has modified files: M src/Selenium2Driver.php
`

I choose yes on the prompt to Discard the changes. I'm wondering what is causing the error too.

**Comment by webflo** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if this is still an issue.
