### ISSUE TITLE
Feature suggestion: Support a way to relocate packages to $drupalRoot/libraries/

### ISSUE THREAD

**Issue by cburschka** [drupal-composer/drupal-composer-project#409]
Some Drupal modules have front-end dependencies that need to be installed to `web/libraries` - but as these are often third-party packages, we can't directly set a package type like `drupal-library` or an installation path for them.

One example is file_browser, which uses some JS packages. A suggested workaround for these is currently https://gist.github.com/mortenson/a5390d99013b5b8c0254081e89bb4d47, using a locally defined package instead of using the regular one. But that stops them from updating automatically.

Maybe it would be possible to solve this with an extra composer.json key like

```
        "drupal-libraries": {
            "imagesloaded": "desandro/imagesloaded",
            "masonry": "desandro/masonry",
            "dropzone": "enyo/dropzone"
        }
```

And some extra code in ScriptHandler::createRequiredFiles() to symlink these?

**Comment by normanlolx** [comment]
Inactive.
