### ISSUE TITLE
Can I use my own composer.json?

### ISSUE THREAD

**Issue by maniac0s** [drupal-composer/drupal-composer-project#411]
Hello, I am new to this process. I just wonder how composer knows where to get the composer.json from when using 

composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction

Reason is: I'd like to use my own composer.json with some default modules of mine to be installed along with a new project to save me some time. Is this even possible?

What if I had my own git repository (like a fork from this one) and can somehow point composer to pull the composer.json and everything from there?

EDIT: Just found out that I can git clone the fork of drupal-project and run composer create-project in there. Unfortunately I seem not to be able to use "composer create-project --repository-url ssh://git@..." via ssh, because it tells me that it requires http or json, is this true?

**Comment by sovainfo** [comment]
Composer doesn't know which composer.json to use, it uses the one provided in the template or created by the template. To use your own composer.json use --no-install on create-project, replace/modify the composer.json and run composer install.

As alternative create your own template containing the composer.json you need. A fork from this one would work. The create-project would download your template and issue composer install using the composer.json you provided in your template.

**Comment by webflo** [comment]
@sovainfo Thanks for answering the question.
