### ISSUE TITLE
Adjust core -p2 patch level

### ISSUE THREAD

**Issue by geek-merlin** [drupal-composer/drupal-composer-project#412]
Now that cweagans/composer-patches [allows](https://github.com/cweagans/composer-patches/pull/189) it, we should [adjust](https://github.com/cweagans/composer-patches/pull/101) the core patch level by default.

**Comment by milkovsky** [comment]
Will the core patches be always applied wrong(with b, core assets) without this setting?

**Comment by milkovsky** [comment]
Ok, the answer on my question is -"yes". We definitely need to add this default.

**Comment by webflo** [comment]
Done in #418
