### ISSUE TITLE
composer create-project drupal-composer/drupal-project:8.x-dev html - ends with killed message

### ISSUE THREAD

**Issue by neps-in** [drupal-composer/drupal-composer-project#414]
Hey, 

I am trying to setup drupal on my ubuntu i am getting the following message

```
composer create-project drupal-composer/drupal-project:8.x-dev html
Installing drupal-composer/drupal-project (8.x-dev 24f29be11ebcb2c2e610dcfd348b61e15f0d6d91)
  - Installing drupal-composer/drupal-project (8.x-dev 24f29be): Cloning 24f29be11e
Created project in html
> DrupalProject\composer\ScriptHandler::checkComposerVersion
Loading composer repositories with package information
Updating dependencies (including require-dev)
Killed
```

Please help / advice what should i do

**Comment by twalcari** [comment]
I am experiencing the same problem. I tried to get more verbose output from composer, but that didn't produce any additional output

**Comment by targoo** [comment]
Same here...

**Comment by webflo** [comment]
This mighty be related to the system memory. How much memory has your base system and do you have any limits in your php config?

**Comment by webflo** [comment]
You could try https://github.com/zaporylie/composer-drupal-optimizations to reduce the memory footprint required by composer.

**Comment by Igsu-Bravo** [comment]
You can also add a temporary swapfile to increase the available memory and the script should run.

**Comment by colans** [comment]
@webflo Can that library be added as a dependency to this project?

**Comment by vijaycs85** [comment]
+1 here and #442
