### ISSUE TITLE
Drush is not working in Windows

### ISSUE THREAD

**Issue by waseem312** [drupal-composer/drupal-composer-project#421]
$ drush status
'"C:\\xampp\\htdocs\\drupalDrush\\vendor\\bin\\drush.php.bat"' is not recognized as an internal or external command,
operable program or batch file.

Getting this error while using drush in windows.

**Comment by cooldrupal** [comment]
Try to copy C:\xampp\htdocs\drupalDrush\vendor\bin\drush.bat -> C:\xampp\htdocs\drupalDrush\vendor\bin\drush.php.bat

**Comment by agrozyme** [comment]
I write a batch file to fix this problem:

composer-create-project.cmd
```
@echo off
call composer global remove hirak/prestissimo
call composer -n create-project %*
call composer global require hirak/prestissimo
```

**Comment by webflo** [comment]
Please open a issue in drushs issue queue. This is not related to this project. Thanks!

**Comment by owenwolf** [comment]
Perfect worked thanks for the solution
