### ISSUE TITLE
Drupal 8.6 update

### ISSUE THREAD

**Issue by dillix** [drupal-composer/drupal-composer-project#426]
When will be drupal-project updated to support Drupal 8.6?

**Comment by webflo** [comment]
We are working on it in https://github.com/drupal-composer/drupal-project/pull/424
 
It will be related later today.

**Comment by webflo** [comment]
Merged!

**Comment by AppLEaDaY** [comment]
Hi. Just noticed this update has been released. But I don't know what I am supposed to do in order to benefit from it. I'm new to composer and the coupling drupal-composer. Would you please help me? I'm stuck at what is following.

composer prohibits drupal/core:8.6.1

drupal-composer/drupal-project  -      requires  drupal/core (~8.5.3)  
webflo/drupal-core-require-dev  8.5.7  requires  drupal/core (8.5.7)

**Comment by mikaelmeulle** [comment]
to update your drupal core, you can proceed like this : 

1.  update your composer.json file according to https://github.com/drupal-composer/drupal-project/pull/424   (requirement of package drupal/core and  dev requirement of package webflo/drupal-core-require-dev)

2. (optionnal) run the following command to see what will happen: 

`composer update drupal/core "symfony/*" webflo/drupal-core-require-dev --with-dependencies -v --dry-run`

3. run the following command to actually download the new package versions (option "-v" is optionnal)

`composer update drupal/core "symfony/*" webflo/drupal-core-require-dev --with-dependencies -v`

**Comment by AppLEaDaY** [comment]
Many thanks, @mikaelmeulle! It worked nicely. I still wonder, though, what will it happen when version 8.6.2, supposing I should modify again composer.json - is it correct? ;-)

Andrea

**Comment by gitressa** [comment]
It seems like the `symfony/*` package doesn't need to be included, when updating from 8.6.5 to 8.6.7 ... it actually gives an error. Should the [recommended update command](https://github.com/drupal-composer/drupal-project#updating-drupal-core) be updated to this?

`composer update drupal/core webflo/drupal-core-require-dev --with-dependencies`

I didn't have to edit `composer.json` or anything, and the update went very smoothly, running `drush updb` and `drush cr` to finish the update process.
