### ISSUE TITLE
can't update to 8.6.0 

### ISSUE THREAD

**Issue by kroawen** [drupal-composer/drupal-composer-project#427]
I used " composer update drupal/core webflo/drupal-core-require-dev --with-dependencies " only 
 updated  8.5.7

**Comment by webflo** [comment]
Please check your composer.json file and adjust the constraints for drupal/core and webflo/drupal-core-require. Similar to this change in https://github.com/drupal-composer/drupal-project/commit/c1e2b6e6b32d51e75321d76c503714d8515e2420

The previous constraints where a more strict to prevent accidentally updates to the next minor version.
