### ISSUE TITLE
Update scaffolding to include container, settings file, and behat.

### ISSUE THREAD

**Issue by allgood2386** [drupal-composer/drupal-composer-project#429]
This is mostly likely out of scope for what the maintainer goals for the project are. I just wanted to start a discussion/confirm that none of these features are desirable.

In short, we're contemplating creating/maintaining an opinionated fork of this project which adds a few features and dockerized environment.

It's a WIP at the moment, and I'll need to either create our own project to maintain the downloading the wodby files (similar to what you all do with files like .editorconfig).

In short this is what our project aims to do.

* Maintain 95% of drupal-project scaffolding.
* Includes the following from the https://github.com/wodby/docker4drupal
   * .env.example
   * docker-compose.yml (and testing compose)
   * traefix configuration as well.
* A settings.php file with the same configuration as drupal-project + a stanza with the database connection, trusted hosts, etc.
* drupal-extension and behat configuration for our dockerized environment.
* A Makefile for common commands and docker learning.

It was my understanding from other discussions I've seen that the intent of this project is to be very minimal and lightweight, and clearly I'm adding a lot here so I'm guessing most of this is a no. However, if there is any of this that the maintainers find value in, I'm happy to set up some pr's and figure out how to best work adding the desirable pieces of functionality. Here is the fork we're working with currently https://github.com/bixal/drupal-project

**Comment by weitzman** [comment]
I agree with your assumption that those are best handled outside of this project. Thanks for sharing your project.
