### ISSUE TITLE
Document how to use forks

### ISSUE THREAD

**Issue by rodrigoaguilera** [drupal-composer/drupal-composer-project#43]
I was trying to use https://github.com/md-systems/pathauto for pathauto in my composer.json since the drupal packagist version is outdated.

I was using 

```
"repositories": [
    {
        "type": "composer",
        "url": "https://packagist.drupal-composer.org"
    },
    {
        "type": "vcs",
        "url": "https://github.com/md-systems/pathauto"
    }
],
```

Then

```
     composer require "drupal/pathauto": "dev-8.x-1.x"
```

But the packagist repo takes priority over the md-systems fork. You just have to change the order in the repositories section.

I spent some hours on this so I think is worth it document it somehow. 
Where can I put it?

**Comment by webflo** [comment]
I think we could collect some common example on a wiki page add this page to our README. The official composer docs are quite good as well.

> Note: Order is significant here. When looking for a package, Composer will look from the first to the last repository, and pick the first match. By default Packagist is added last which means that custom repositories can override packages from it.

https://getcomposer.org/doc/04-schema.md#repositories

**Comment by webflo** [comment]
Here is another example from stackoverflow. http://stackoverflow.com/questions/29400088/how-do-i-use-a-package-in-composer-that-has-the-same-name-as-another-package/29401760#29401760
