### ISSUE TITLE
need drupal core 8.6.1 for correcting the update issue

### ISSUE THREAD

**Issue by sealionking** [drupal-composer/drupal-composer-project#430]
https://www.drupal.org/project/drupal/issues/2997960

I am not sure how to edit the composer.json to get the right core package

Though I update via composer to 8.6.x-dev 6ceab95f1a, when update datebase, still lose the taxonomy hierarchy items.

**Comment by jcnventura** [comment]
You run ```composer update``` and you should have 8.6.1.

**Comment by sealionking** [comment]
fine,now can update correctly
