### ISSUE TITLE
Drush update not working

### ISSUE THREAD

**Issue by AnnoyedDeveloper** [drupal-composer/drupal-composer-project#436]
Hello there

for my Drupal project, I could not update drush for some reason. Running `composer require drush/drush` caused me this error:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install drush/drush 9.5.2
    - Conclusion: don't install drush/drush 9.5.1
    - Conclusion: don't install drush/drush 9.5.0
    - Conclusion: don't install drush/drush 9.6.0-alpha1
    - Conclusion: don't install drush/drush 9.x-dev
    - Conclusion: remove chi-teck/drupal-code-generator 1.25.1
    - Installation request for drush/drush ^9.5 -> satisfiable by drush/drush[9.5.0, 9.5.1, 9.5.2, 9.5.x-dev, 9.6.0-alpha1, 9.x-dev].
    - Conclusion: don't install chi-teck/drupal-code-generator 1.25.1
    - drush/drush 9.5.x-dev requires chi-teck/drupal-code-generator ^1.27.0 -> satisfiable by chi-teck/drupal-code-generator[1.27.0, 1.x-dev].
    - Can only install one of: chi-teck/drupal-code-generator[1.27.0, 1.25.1].
    - Can only install one of: chi-teck/drupal-code-generator[1.x-dev, 1.25.1].
    - Installation request for chi-teck/drupal-code-generator (locked at 1.25.1) -> satisfiable by chi-teck/drupal-code-generator[1.25.1].

Installation failed, reverting ./composer.json to its original content.

**Comment by AnnoyedDeveloper** [comment]
Never mind, was a user problem

**Comment by normanlolx** [comment]
Could you elaborate that a bit please?
