### ISSUE TITLE
composer installation "cannot find specified file"?

### ISSUE THREAD

**Issue by bhvonkorff** [drupal-composer/drupal-composer-project#439]
Trying to install drupal via composer.
1) downloaded the zip file from github, extracted to c:\composer, and tried running two commands from this folder via command prompt:

composer update 
result: (cannot find specified file error)

composer create-project drupal-composer/drupal-project:8.x-dev mydrupal --stability dev --no-interaction 
result: (cannot find specified file error)

**Comment by webflo** [comment]
I have no idea what is causing the problem. Does it still exist?

**Comment by zaporylie** [comment]
@bhvonkorff Can you provide more details regarding the issue you're having? I fail to see how #452 can fix it but I also fail to reproduce it locally. Seems to be Windows related? Would be very helpful if you could either provide a screenshot or copy the exact output from the command prompt.

**Comment by normanlolx** [comment]
In https://github.com/composer/windows-setup/issues/60 they finally found some Windows anti virus app causing a similar bug.

**Comment by normanlolx** [comment]
Inactive.
