### ISSUE TITLE
Discuss using GPL instead of MIT

### ISSUE THREAD

**Issue by pfrenssen** [drupal-composer/drupal-composer-project#44]
Can we have a discussion about the license for this project? I am in favour of using GPL instead of MIT because it is copyleft and better protects the interests of the project, end-users as well as clients that are ultimately paying for the work that is being done.

**Comment by rodrigoaguilera** [comment]
I also prefer GPL but I don't feel is very relevant for a small project like this one. The main question for me being: How can you use this to release a closed source derivative? Is mainly a tool for developers.

**Comment by webflo** [comment]
I don't mind to change the license to GPL, but i am not sure if can change it right away ...

**Comment by cweagans** [comment]
FWIW: I think you might _have_ to change the license to GPL2+, since the web directory contains code taken directly from core. Since all the PHP code is running in the same memory sandbox, it's considered a derivative work and is therefore subject to Drupal's license.

**Comment by webflo** [comment]
@cweagans Good point. I´ll change it to `GPL-2.0+`.

**Comment by cweagans** [comment]
Don't forget https://github.com/drupal-composer/drupal-project/blob/8.x/LICENSE ! :)

**Comment by webflo** [comment]
@cweagans Thanks for the heads up.

**Comment by pfrenssen** [comment]
Thanks! This can be closed now.
