### ISSUE TITLE
composer require drupal/address installs phpunit and other dev/test code

### ISSUE THREAD

**Issue by melato** [drupal-composer/drupal-composer-project#443]
I installed drupal + drupal/address like this:
```
composer create-project drupal-composer/drupal-project:8.x-dev --no-dev --stability dev --no-interaction d8
cd d8
# verify that vendor/phpunit does not exist
composer require drupal/address

```
and got several libraries that are development/test related and should not be installed on a production machine:
vendor/bin/phpunit
vendor/bin/simple-phpunit
vendor/drupal/coder/
vendor/phpdocumentor/
vendor/phpspec/
vendor/phpunit/
vendor/symfony/phpunit-bridge/

(I may have missed some. These are the ones that seem obvious).

If I then do "composer update --no-dev" these packages are removed.
Is there a way to not install them in the first place?

I followed the installation instructions from here:
https://www.drupal.org/docs/user_guide/en/install-composer.html

**Comment by melato** [comment]
This happens with other modules too (probably all).  I tried it with drupal/leaflet.
composer require seems to install all require-dev packages in the project.
"composer update --no-dev" removes them.

**Comment by gitressa** [comment]
`composer require --update-no-dev 'drupal/leaflet'` should get you just the module, without the dev-packages.

In my opinion, not downloading dev-packages should be the default for both Drupal core and modules, when downloading using Composer, so the user don't have to remember to add  `--no-dev` or `--update-no-dev`. Those who need the dev-packages should be able to do so with a parameter like `--use-dev`.

**Comment by melato** [comment]
I forwarded this to drupal.org/project/user_guide:
https://www.drupal.org/project/user_guide/issues/3024030

In my opinion, composer is a development tool, so it should include dev-packages (but it should have consistent --no-dev option).  Users should use a different tool (an installer).

p.s. This is the third time I enter this issue.  It seems inefficient to have to rewrite the bug report each time it is sent to a different component of drupal, but then again, github does the same -- each project/repository is independent.

**Comment by melato** [comment]
Actually, composer could remember the --no-dev option from create-project and use it in subsequent require or update commands.  It could store the option in composer.json.

**Comment by jensschulze** [comment]
You could use the `--no-dev` option of the `composer create-project` command.

**Comment by melato** [comment]
> You could use the `--no-dev` option of the `composer create-project` command.

I did.

**Comment by fafnirical** [comment]
As far as I know, `composer create-project` still downloads the same `composer.json` file from the project, no matter if the `--no-dev` flag is passed or not. The `--no-dev` flag passed to `composer create-project` only applies to the initial `composer install` command that runs after the project is downloaded, but doesn't modify `composer.json`.

These dev dependencies are getting installed because they're still declared in your `composer.json` file.

If you wanted to remove the dev dependencies, you might run:
```sh
composer create-project drupal-composer/drupal-project:8.x-dev --no-install --stability dev --no-interaction d8
cd d8
composer remove --dev webflo/drupal-core-require-dev
composer install
```

**Comment by melato** [comment]
> composer remove --dev webflo/drupal-core-require-dev

This is too cryptic for me.  "composer require --update-no-dev" seems more straightforward.

Is drupal-composer/drupal-project meant to be used by PHP developers setting up an environment to work with Drupal, or by someone who installs a Drupal website, without necessarily needing to or knowing how to write any PHP code?  These are two different use cases, so perhaps they should use two different composer.json files.

I used composer to install Drupal, so I could install some modules that are installable only with composer.  So I use composer as a Drupal installer.

Would it be possible to have a separate drupal-composer/drupal-installer project that is meant for production installation of Drupal, and therefore would not have the -dev dependencies?

**Comment by hansfn** [comment]
@melato I don't think you should close this issue. Just change the title so it matches your latest comment (and possibly update your initial post).

There should be a Composer template for people that just want to install Drupal without doing development, production or not,  for example site builders. Maybe there needs to be same changes to the Drupal composer.json file too, but I guess we could start with the Composer template ...

**Comment by melato** [comment]
@hansfn I created a new issue:  https://github.com/drupal-composer/drupal-project/issues/446
