### ISSUE TITLE
Error with Drush and composer

### ISSUE THREAD

**Issue by clefournis** [drupal-composer/drupal-composer-project#448]
Drush was unable to create site archive.
StdErr:PHP Parse error:  syntax error, unexpected 'function' (T_FUNCTION), expecting identifier (T_STRING) or \\ (T_NS_SEPARATOR) in /Sites/acquiasites/lightning-8.x-3.203/vendor/myclabs/deep-copy/src/DeepCopy/deep_copy.php on line 5

**Comment by weitzman** [comment]
deep_copy is not part of Drush.

**Comment by webflo** [comment]
Probably a problem with the PHP version you are using (PHP 5 vs. 7.x)
