### ISSUE TITLE
Better readme for new project

### ISSUE THREAD

**Issue by gagarine** [drupal-composer/drupal-composer-project#455]
When you create a new project, the readme of this repository is added.

Yet, I don't think is useful for people joining a project. Of course, any project certainly need to customize is readme, but perhaps the default one can be better.

I short, I would like to have a readme that explain how to use the created project and not how to create a new project with drupal-project.

**Comment by normanlolx** [comment]
And how would you think this README may look like?

**Comment by gagarine** [comment]
I'm using somethings like that.

```
#  Site name

URL: https://site.com

We use composer to manage all drupal dependencies. The project was started using https://github.com/drupal-composer/drupal-project

## Init the project on your local machine

- Get the source from git
- install all depencies using composer
- create a local DB
- copy example.env to .env and complete with your access

## Composer
Composer is used to manage dependencies (drupal core, modules, theme, ..)

**Download all require dependency for the project**

    composer install
   
**Install a new module**
   
    composer require drupal/modulename
       
**Check if their is update**
        
    composer outdated "drupal/*"
        
**Update core**

    composer update drupal/core --with-dependencies

**Update a module**

    composer update drupal/modulename --with-dependencies

## Drush

Drush is a command line tools for drupal. Drush is installed with composer automatically.


List all the command

    ./vendor/bin/drush
    
run DB update
    
     ./vendor/bin/drush updatedb
            
Check security update
    
     ./vendor/bin/drush pm:security

Rebuild all cache (first things to do in case of strange bugs)

    ./vendor/bin/drush cache-rebuild
    
Import/Export configuration

    ./vendor/bin/drush config-import
    ./vendor/bin/drush config-export
    
Manage module

    ./vendor/bin/drush pm-enable
    ./vendor/bin/drush pm-disable
   
Make a full backup (Backup your code, files, and database into a single file)

    ./vendor/bin/drush archive-dump
   
Restore

    ./vendor/bin/drush archive-restore

        
## Theme Development

nodejs is used to compile less to css.

**Requirement for development**

- **nodejs** https://nodejs.org/en/

**Install project dependencies**

    npm install

**Work with less**

Start watcher on less files (build on change)

    npm run start

Build sass (one time)

    npm run build
 

## Deployment

todo

```

**Comment by normanlolx** [comment]
Sounds useful. Thing is, the moment you've run `composer create-project` the project is yours and you can do and change whatever you want. When you want to tell your co-workers how this – your – project is supposed to be used, update the README. It's now yours. Apart from that I'd say it's maybe not the most sustainable action to repeat the docs from drupal.org at this place, @see https://www.drupal.org/docs/develop/using-composer/using-composer-with-drupal.

**Comment by gagarine** [comment]
Can we generate (copy) another readme inside the project when we use composer create-project ?

As drupal-project is a caneva, I think we can also propose some kind of caneva for the README.

**Comment by normanlolx** [comment]
I guess you need to submit a PR of your proposed changes to the existing README to have something concrete to talk about.

**Comment by normanlolx** [comment]
Inactive.
