### ISSUE TITLE
Custom commands are not found

### ISSUE THREAD

**Issue by robme** [drupal-composer/drupal-composer-project#461]
I don't know if this is a bug with Drush or the composer template, but any commands installed to `drush/Commands` are not found by Drush (cache is cleared).

Using Drush 9.6.0.

**Comment by normanlolx** [comment]
Without seeing any of your custom implementation or any info about your environment this issue is impossible to be solved from afar.

**Comment by robme** [comment]
I was just using the composer template with Drupal 8.6 and Drush 9.4 or above. Drush worked fine, but it never detected any commands placed in `drush/Commands` or `web/drush/Commands`.

I was trying to use `site_audit` commands, but tried some others from https://packagist.org/search/?type=drupal-drush and it never detected any of them.

I have now downgraded to Drush 8 and now it detects the commands in `drush/Commands`.

**Comment by Chi-teck** [comment]
Drush 9 does not support Drush 8 commands.
https://weitzman.github.io/blog/port-to-drush9

**Comment by normanlolx** [comment]
Sorry for the late reply. Please feel free to reopen by adding your composer.json and the steps/commands to reproduce if the issue still persists. Many thanks 🙂

**Comment by normanlolx** [comment]
Also sounds a bit like a problem with the Site Audit module. Last time I checked it was stuck during refactoring and a lot of things didn't work. It also seemed to have moved more in the direction of a module which must be enabled to use its commands.

There might be an alternative, a fork from the original Site Audit here: https://github.com/pantheon-systems/site-audit-tool
