### ISSUE TITLE
TimeStampItemNormalizerTrait is deprecated in Drupal 8.7.0

### ISSUE THREAD

**Issue by szepeviktor** [drupal-composer/drupal-composer-project#465]
~~Does anybody know the reason why it happens in `RELEASE=dev` only?~~
https://travis-ci.org/drupal-composer/drupal-project/jobs/494480882

> Drupal\serialization\Normalizer\TimeStampItemNormalizerTrait is deprecated in Drupal 8.7.0 and will be removed in Drupal 9.0.0. Use \Drupal\serialization\Normalizer\TimestampNormalizer instead.

So tests fail.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
