### ISSUE TITLE
How to integrate it with core in Drupal7?

### ISSUE THREAD

**Issue by jorgetutor** [drupal-composer/drupal-composer-project#469]
How does this composer project integrate with Drupal 7 core?
It seems that there is no drupal-scaffold (https://github.com/drupal-composer/drupal-scaffold) integration.
What step should I follow?
Thanks in advance

**Comment by zaporylie** [comment]
https://github.com/drupal-composer/drupal-project/tree/7.x maintained by @jcnventura is a good starting point

**Comment by jcnventura** [comment]
There's no drupal-scaffold because there's also no drupal-core for Drupal 7. Drupal-scaffold is required because drupal-core doesn't contain the extra files. This doesn't happen with D7.
