### ISSUE TITLE
Some drupal files not downloading

### ISSUE THREAD

**Issue by jsibley2** [drupal-composer/drupal-composer-project#473]
I use this command:

 `composer create-project drupal-composer/drupal-project:8.x-dev projectdirectory --no-interaction
`
and get this error message:

```
 [Exception]
  Failed to download https://cgit.drupalcode.org/drupal/plain/update.php, https://cgit.drupalcode.org/drupal/plain/sites/development.services.yml, https://cgit.dru
  palcode.org/drupal/plain/sites/default/default.settings.php, https://cgit.drupalcode.org/drupal/plain/robots.txt, https://cgit.drupalcode.org/drupal/plain/index.
  php, https://cgit.drupalcode.org/drupal/plain/.htaccess, https://cgit.drupalcode.org/drupal/plain/sites/example.sites.php, https://cgit.drupalcode.org/drupal/pla
  in/sites/example.settings.local.php, https://cgit.drupalcode.org/drupal/plain/sites/default/default.services.yml
```

in what appears to be step 7/16

I'm running composer 1.8.4

Is there something I should be doing differently to avoid this issue?

Thank you.

**Comment by normanlolx** [comment]
I'd bet this just being some hickups on the Drupal servers. Simply retry it in an hour or so.

**Comment by jsibley2** [comment]
I had the same issue yesterday and again a few hours later today. Still, no luck.

Do any other possibilities come to mind? And do I have to clean out my directory and start over again each time?

**Comment by jsibley2** [comment]
I tried again with -vvv and maybe this helps?

`Exception trace:
 () at /home/jsasse5/clc-test/vendor/drupal-composer/drupal-scaffold/src/PrestissimoFileFetcher.php:83
 DrupalComposer\DrupalScaffold\PrestissimoFileFetcher->fetchWithPrestissimo() at /home/jsasse5/clc-test/vendor/drupal-composer/drupal-scaffold/src/PrestissimoFileFetcher.php:35
 DrupalComposer\DrupalScaffold\PrestissimoFileFetcher->fetch() at /home/jsasse5/clc-test/vendor/drupal-composer/drupal-scaffold/src/Handler.php:163
 DrupalComposer\DrupalScaffold\Handler->downloadScaffold() at /home/jsasse5/clc-test/vendor/drupal-composer/drupal-scaffold/src/Handler.php:136
 DrupalComposer\DrupalScaffold\Handler->onPostCmdEvent() at /home/jsasse5/clc-test/vendor/drupal-composer/drupal-scaffold/src/Plugin.php:83
 DrupalComposer\DrupalScaffold\Plugin->postCmd() at n/a:n/a
 call_user_func() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:176
 Composer\EventDispatcher\EventDispatcher->doDispatch() at phar:///usr/local/bin/composer/src/Composer/EventDispatcher/EventDispatcher.php:96
 Composer\EventDispatcher\EventDispatcher->dispatchScript() at phar:///usr/local/bin/composer/src/Composer/Installer.php:324
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:192
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:145
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:258
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:56
 require() at /usr/local/bin/composer:24`

**Comment by normanlolx** [comment]
What happens when you `composer global remove hirak/prestissimo` first? Is is the same? And what happens when you `rm -rf projectdirectory` first?

**Comment by jsibley2** [comment]
Thank you, removing prestissimo seemed to work.

So, more likely an issue with prestissimo (or some interaction with prestissimo)?

Thanks!

**Comment by normanlolx** [comment]
I don't know to be honest. It was just a wild guess as prestissimo was listed in the exception trace you shared. Maybe try to add it back and `composer globale update --with-dependencies` first next time.

**Comment by leymannx** [comment]
Or `composer self-update`.
