### ISSUE TITLE
Force update module using composer

### ISSUE THREAD

**Issue by nxut** [drupal-composer/drupal-composer-project#478]
I ran composer outdated drupal/* and noticed that I need to update devel module:
drupal/devel  1.2.0  to 2.0.0

In composer.json I have:
` "require-dev": {
     "drupal/devel": "1.*"
}`

When I ran **composer update drupal/devel --with-dependencies** nothing changes. Can anyone explain this to me please?
Thank you in advance!

**Comment by rodrigoaguilera** [comment]
You are fixing the major version to always use devel from the 1.x branch.
The usual approach when you want to update major versions is to edit the composer.json to something like 
```
 "require-dev": { "drupal/devel": "^2" }
```
and then run

```
 composer update drupal/devel --with-dependencies
```

alternative the command
```
 composer require --dev drupal/devel:^2
```

will do also edit the composer.json for you.

Please close the issue if this helped.

**Comment by nxut** [comment]
arigato gozaimashita :smile:
