### ISSUE TITLE
Install error Drupal 8.6.13

### ISSUE THREAD

**Issue by auxiliaryjoel** [drupal-composer/drupal-composer-project#480]
composer install completes,
but then when loading the /web/ directory to initiate the install process, this error occurs:
The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">standard</em> have unmet dependencies: <em class="placeholder">block.block.bartik_account_menu (block), block.block.bartik_help (help, block), block.block.bartik_search (search, block), block_content.type.basic (block_content), comment.type.comment (comment), contact.form.feedback (contact), core.entity_form_display.block_content.basic.default (text), core.entity_form_display.node.article.default (image.style.thumbnail, comment, image, path, text), core.entity_form_display.node.page.default (path, text), core.entity_form_display.user.user.default (image.style.thumbnail, image), core.entity_view_display.node.article.default (image.style.large, comment, image, text), core.entity_view_display.node.article.rss (core.entity_view_mode.node.rss), core.entity_view_display.node.article.teaser (core.entity_view_mode.node.teaser, image.style.medium, image, text), core.entity_view_display.node.page.teaser (core.entity_view_mode.node.teaser, text), editor.editor.basic_html (ckeditor, editor), field.field.block_content.basic.body (field.storage.block_content.body, text, field), field.field.comment.comment.comment_body (field.storage.comment.comment_body, text, field), field.field.node.article.body (field.storage.node.body, text, field), field.field.node.article.comment (comment, field), field.field.node.article.field_image (image, field), field.field.node.article.field_tags (field), field.storage.node.comment (comment, node, field), field.storage.node.field_image (file, image, node, field), field.storage.node.field_tags (node, taxonomy, field), field.storage.user.user_picture (file, image, field), filter.format.basic_html (editor, filter), filter.format.restricted_html (filter), node.type.article (node), rdf.mapping.comment.comment (comment, rdf), rdf.mapping.node.article (node, rdf), rdf.mapping.taxonomy_term.tags (taxonomy, rdf), taxonomy.vocabulary.tags (taxonomy)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core/lib/Drupal/Core/Config/UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('standard', Array) (Line: 485)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1663)
install_install_profile(Array) (Line: 709)
install_run_task(Array, Array) (Line: 584)
install_run_tasks(Array, NULL) (Line: 125)
install_drupal(Object) (Line: 44)

**Comment by dvangimst** [comment]
I have the same problem! Yesterday it worked fine.

Today an install on my local Mac created the same error as above. Also tried on a server and there the installation was also broken.

**Comment by davehas1** [comment]
I have the same issue.

**Comment by jessicaix** [comment]
I have the same issue. The install runs in a loop and installs only half of the database. What I did is download the drupal 8 zip from the project page. Installed that one and pointed the composer drupal install settings files towards that one. That works, but far from ideal. So this needs fixing.

**Comment by weitzman** [comment]
This issue is confusing me. This project just assembles your codebase via Composer. It does not run an installation. What command are folks using to install Drupal? Or are you installing Drupal via the web browser?

**Comment by auxiliaryjoel** [comment]
Hi weitzman, yes the composer project runs successfully, next step is to load the site in web browser page, which then initiates the Drupal install steps. first few steps are OK.
But after assigning database and choosing install type, the error page appears with no option to ignore or proceed. 
I'm running MAMP with 2 other sites that installed OK using the exact same methods, but as of yesterday trying to install this 3rd site and this error is occurring.

**Comment by jessicaix** [comment]
I follow the same steps as auxiliaryjoel. I clone the project, run composer install, then visit my site and then follow the steps after inputting my db settings it goes back to choose the language page. When I check the db I see that it’s only half installed. No errors in the logs. I am using MAMP as well and I use this composer template for all my Drupal projects and never had problems with it. This is the first time. So something seems off

**Comment by mmenavas** [comment]
I'm experiencing this issue too. Installing the site by running `drush si` is a workaround.

**Comment by auxiliaryjoel** [comment]
@mmenavas can you give me more info on how to handle install vi drush si?
And if instsalling that way, does it provide the git structure and directory/files as per this  composer project or would I then no longer be able ti run git pushes and do Drupal Core update via composer? and would I still be able to manage future module inclusions via composer?

**Comment by weitzman** [comment]
I asked around. This is a bug in latest Drupal release, not in this project. Please follow https://www.drupal.org/project/drupal/issues/3045349 for more information. I'm leaving this open so people find it, but closing comments since conversation should happen at the url above.
