### ISSUE TITLE
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction

### ISSUE THREAD

**Issue by knows1** [drupal-composer/drupal-composer-project#481]
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction

1- The following exception is caused by a lack of memory or swap, or not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors
 for details

2- [ErrorException]                                   
  proc_open(): fork failed - Cannot allocate memory

**Comment by weitzman** [comment]
This is a system error, unrelated to this project. Please use google, StackOverflow etc.

**Comment by knows1** [comment]
Danke
