### ISSUE TITLE
Exception thrown after installing site

### ISSUE THREAD

**Issue by bradbulger** [drupal-composer/drupal-composer-project#482]
Just today, a new project and new installation, trying to run Drupal fails with an exception:

TypeError: Return value of Doctrine\Common\Annotations\AnnotationRegistry::reset() must be an instance of Doctrine\Common\Annotations\void, none returned in Doctrine\Common\Annotations\AnnotationRegistry::reset() (line 55 of /var/www/html/seattle/d8symfony/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationRegistry.php).

This same process worked without issue yesterday.

**Comment by bradbulger** [comment]
For what it's worth, if I copy the working project I created yesterday and run composer update on it, it upgrades annotations:

  - Updating doctrine/annotations (v1.4.0 => v1.6.1): Loading from cache

And at that point, different paths in Drupal start failing with the same exception.

**Comment by webflo** [comment]
Please check your PHP configuration. Are you using the same PHP version on command line and your web server?

**Comment by bradbulger** [comment]
Yes apparently there was a version dependent change between Monday and
Tuesday. When I downgraded command line PHP to 7.0 to match the Apache
container, I was able to create a working project again.

**Comment by pfrenssen** [comment]
Thanks for reporting back!
