### ISSUE TITLE
D7: Conflicts with drupal/core

### ISSUE THREAD

**Issue by heilop** [drupal-composer/drupal-composer-project#484]
Currently, the conflicts in the composer file indicate compatibility with Drupal:
```
"conflict": {
    "drupal/core": "8.*"
},
```
I think, this sould be liske this:
```
"conflict": {
    "drupal/core": "7.*"
},
```

**Comment by normanlolx** [comment]
This is for D7. So you must not be able to require a D8 core. This is what this conflict statement is supposed to mean.

**Comment by heilop** [comment]
I got it.
Thanks, @leymannx for your explanation.
