### ISSUE TITLE
Should be/how to update this template itself?

### ISSUE THREAD

**Issue by qichanghai** [drupal-composer/drupal-composer-project#490]
Once a project is created with this project by using **composer create-project**, usually the project will grow on it's own. But since this template itself is also evolving, new dependencies are added, etc.  I think it would be great if this template can also be somehow updated, so the enhancement can also be applied to projects created from it?

**Comment by chrissnyder2337** [comment]
I normally just diff the files in this repository with each of my projects and pull over the changes I want to.

**Comment by NielsSluijs** [comment]
Same for me.

**Comment by normanlolx** [comment]
Watch the repo and then diff your `composer.json` on changes.
