### ISSUE TITLE
Consider adding "discard-changes": true

### ISSUE THREAD

**Issue by joelpittet** [drupal-composer/drupal-composer-project#495]
By adding this:
```
"config": {
    "discard-changes": true
}
```

You can have your build tools use `-n` flag without leaving dirty changes around.
https://getcomposer.org/doc/06-config.md#discard-changes

I can't think of a situation where you'd like to keep this as the default `false` so I'm proposing it be added to this.

**Comment by leymannx** [comment]
Nice, yes. But this is an opinion-based thing I'd say. I prefer the default interactive way of Composer asking me if it should discard or not. Since I never step a foot into the build container or never make any manual changes on the live server it will never be a problem there.

**Comment by normanlolx** [comment]
Ah yes, I think now I understand. `"discard-changes": true` will only be taken into account when running the command with the `--no-interaction` option  (or `-n` flag). That makes sense.

**Comment by AlexSkrypnyk** [comment]
This was added in 2020 when `9.x` was created.

D10: https://github.com/drupal-composer/drupal-project/blob/10.x/composer.json#L54
D11: https://github.com/drupal-composer/drupal-project/blob/11.x/composer.json#L54

Closing.
