### ISSUE TITLE
Error The website encountered an unexpected error. Please try again later.

### ISSUE THREAD

**Issue by InspiredPrynce** [drupal-composer/drupal-composer-project#500]
This happened when installing Drupal8.7.15 and i have done all sorts of things but no avail, please how do i fix it?

Please don't close this without this issue being solved!

Error
The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by <em class="placeholder">standard</em> have unmet dependencies: <em class="placeholder">block.block.bartik_account_menu (block), block.block.bartik_help (help, block), block.block.bartik_search (search, block), block_content.type.basic (block_content), comment.type.comment (comment), contact.form.feedback (contact), core.entity_form_display.block_content.basic.default (text), core.entity_form_display.node.article.default (image.style.thumbnail, comment, image, path, text), core.entity_form_display.node.page.default (path, text), core.entity_form_display.user.user.default (image.style.thumbnail, image), core.entity_view_display.node.article.default (image.style.large, comment, image, text), core.entity_view_display.node.article.rss (core.entity_view_mode.node.rss), core.entity_view_display.node.article.teaser (core.entity_view_mode.node.teaser, image.style.medium, image, text), core.entity_view_display.node.page.teaser (core.entity_view_mode.node.teaser, text), editor.editor.basic_html (ckeditor, editor), field.field.block_content.basic.body (field.storage.block_content.body, text), field.field.comment.comment.comment_body (field.storage.comment.comment_body, text), field.field.node.article.body (field.storage.node.body, text), field.field.node.article.field_image (image), field.storage.node.comment (comment, node), field.storage.node.field_image (file, image, node), field.storage.node.field_tags (node, taxonomy), field.storage.user.user_picture (file, image), filter.format.basic_html (editor, filter), filter.format.restricted_html (filter), node.type.article (node), rdf.mapping.comment.comment (comment, rdf), rdf.mapping.node.article (node, rdf), rdf.mapping.taxonomy_term.tags (taxonomy, rdf), taxonomy.vocabulary.tags (taxonomy)</em> in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core\lib\Drupal\Core\Config\UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('standard', Array) (Line: 481)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1658)
install_install_profile(Array) (Line: 702)
install_run_task(Array, Array) (Line: 577)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 44)

**Comment by normanlolx** [comment]
First, you need to provide a fully reproducible problem. What actions did you take exactly before running into this error? How did you try to install Drupal? Where did you try to install it? What OS? What environment? Second, note that this repo isn't about Drupal itself. But about the Composer template you can use to manage your project's dependencies. Therefore you probably won't get much help here and should consider looking at other places for help. Drupal Answers for example. Though still, you need to provide a fully reproducible problem there, too. Just an error message won't be enough. Hope you understand :)

**Comment by weitzman** [comment]
This project is about assembling a codebase. That happens before you install Drupal. Out of scope, so closing. Sorry.

**Comment by FatherShawn** [comment]
Leaving some links to help the OP find the right place to get help:

https://drupal.stackexchange.com/
https://www.drupal.org/slack

**Comment by InspiredPrynce** [comment]
Installing Drupal using composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction on windows 10, i have php7.1.9 and mysql5.7 and i started the installation process, getting to the INSTALL SITE place, it installs and stops at 14% and then this error shows up!

This happened when installing Drupal8.7.15 and i have done all sorts of things but no avail, please how do i fix it?

Please don't close this without this issue being solved!

Error
The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by standard have unmet dependencies: block.block.bartik_account_menu (block), block.block.bartik_help (help, block), block.block.bartik_search (search, block), block_content.type.basic (block_content), comment.type.comment (comment), contact.form.feedback (contact), core.entity_form_display.block_content.basic.default (text), core.entity_form_display.node.article.default (image.style.thumbnail, comment, image, path, text), core.entity_form_display.node.page.default (path, text), core.entity_form_display.user.user.default (image.style.thumbnail, image), core.entity_view_display.node.article.default (image.style.large, comment, image, text), core.entity_view_display.node.article.rss (core.entity_view_mode.node.rss), core.entity_view_display.node.article.teaser (core.entity_view_mode.node.teaser, image.style.medium, image, text), core.entity_view_display.node.page.teaser (core.entity_view_mode.node.teaser, text), editor.editor.basic_html (ckeditor, editor), field.field.block_content.basic.body (field.storage.block_content.body, text), field.field.comment.comment.comment_body (field.storage.comment.comment_body, text), field.field.node.article.body (field.storage.node.body, text), field.field.node.article.field_image (image), field.storage.node.comment (comment, node), field.storage.node.field_image (file, image, node), field.storage.node.field_tags (node, taxonomy), field.storage.user.user_picture (file, image), filter.format.basic_html (editor, filter), filter.format.restricted_html (filter), node.type.article (node), rdf.mapping.comment.comment (comment, rdf), rdf.mapping.node.article (node, rdf), rdf.mapping.taxonomy_term.tags (taxonomy, rdf), taxonomy.vocabulary.tags (taxonomy) in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core\lib\Drupal\Core\Config\UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('standard', Array) (Line: 481)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1658)
install_install_profile(Array) (Line: 702)
install_run_task(Array, Array) (Line: 577)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 44)
