### ISSUE TITLE
Error The website encountered an unexpected error. Please try again later.

### ISSUE THREAD

**Issue by InspiredPrynce** [drupal-composer/drupal-composer-project#501]
Installing Drupal using `composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction`  on windows 10, i have php7.1.9 and mysql5.7 and i started the installation process, getting to the INSTALL SITE place, it installs and stops at 14% and then this error shows up!

This happened when installing Drupal8.7.15 and i have done all sorts of things but no avail, please how do i fix it?

Please don't close this without this issue being solved!

Error
The website encountered an unexpected error. Please try again later.
Drupal\Core\Config\UnmetDependenciesException: Configuration objects provided by standard have unmet dependencies: block.block.bartik_account_menu (block), block.block.bartik_help (help, block), block.block.bartik_search (search, block), block_content.type.basic (block_content), comment.type.comment (comment), contact.form.feedback (contact), core.entity_form_display.block_content.basic.default (text), core.entity_form_display.node.article.default (image.style.thumbnail, comment, image, path, text), core.entity_form_display.node.page.default (path, text), core.entity_form_display.user.user.default (image.style.thumbnail, image), core.entity_view_display.node.article.default (image.style.large, comment, image, text), core.entity_view_display.node.article.rss (core.entity_view_mode.node.rss), core.entity_view_display.node.article.teaser (core.entity_view_mode.node.teaser, image.style.medium, image, text), core.entity_view_display.node.page.teaser (core.entity_view_mode.node.teaser, text), editor.editor.basic_html (ckeditor, editor), field.field.block_content.basic.body (field.storage.block_content.body, text), field.field.comment.comment.comment_body (field.storage.comment.comment_body, text), field.field.node.article.body (field.storage.node.body, text), field.field.node.article.field_image (image), field.storage.node.comment (comment, node), field.storage.node.field_image (file, image, node), field.storage.node.field_tags (node, taxonomy), field.storage.user.user_picture (file, image), filter.format.basic_html (editor, filter), filter.format.restricted_html (filter), node.type.article (node), rdf.mapping.comment.comment (comment, rdf), rdf.mapping.node.article (node, rdf), rdf.mapping.taxonomy_term.tags (taxonomy, rdf), taxonomy.vocabulary.tags (taxonomy) in Drupal\Core\Config\UnmetDependenciesException::create() (line 98 of core\lib\Drupal\Core\Config\UnmetDependenciesException.php).

Drupal\Core\Config\UnmetDependenciesException::create('standard', Array) (Line: 481)
Drupal\Core\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 132)
Drupal\Core\ProxyClass\Config\ConfigInstaller->checkConfigurationToInstall('module', 'standard') (Line: 150)
Drupal\Core\Extension\ModuleInstaller->install(Array, ) (Line: 83)
Drupal\Core\ProxyClass\Extension\ModuleInstaller->install(Array, ) (Line: 1658)
install_install_profile(Array) (Line: 702)
install_run_task(Array, Array) (Line: 577)
install_run_tasks(Array, NULL) (Line: 118)
install_drupal(Object) (Line: 44)

**Comment by normanlolx** [comment]
Just for clarification, did you understand what's been said in the other issue? https://github.com/drupal-composer/drupal-project/issues/500

**Comment by InspiredPrynce** [comment]
@leymannx yes i did that's why i reposted with this

Installing Drupal using composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction on windows 10, i have php7.1.9 and mysql5.7 and i started the installation process, getting to the INSTALL SITE place, it installs and stops at 14% and then this error shows up!

This happened when installing Drupal8.7.15 and i have done all sorts of things but no avail, please how do i fix it?

Please don't close this without this issue being solved!

**Comment by normanlolx** [comment]
It's off-topic. You need to ask it somewhere else.

**Comment by InspiredPrynce** [comment]
@leymannx stop saying its an off-topic and attend to me if you know the answer. I have been roaming the whole internet seeking for solutions, reading other people's answers and questions yet no answer. If you know how to fix it please help me so i can stop asking it here please

**Comment by NielsSluijs** [comment]
@InspiredPrynce I know these type of errors can be frustrating, but your error is most probably not due a bug/flaw in the code of this project. [Drupal Answers](https://drupal.stackexchange.com/) might be a better place to ask for assistance with your problem, though there it might be considered to broad. So, when posting your question there, I certainly recommend to explain what you did to try to solve the problem (and why it didn't work).
