### ISSUE TITLE
How to use local version of Drush ?

### ISSUE THREAD

**Issue by webmasterpf** [drupal-composer/drupal-composer-project#505]
Hi,

I just install D8.7.5 via composer as described, and I can see a drush folder created.
But on my server, I globally use Drush 8, so how can I Drush 9 ( I guess) locally ?

Thanks

**Comment by normanlolx** [comment]
Yes, locally.

```bash
$ cd /path/to/your/project
$ vendor/drush/drush/drush status
```

And with [Drush Launcher](https://github.com/drush-ops/drush-launcher) installed you have a global `drush` command that automagically always uses the local Drush.

**Comment by normanlolx** [comment]
But actually that's out of scope and you shouldn't use this project's issue queue for general questions about Composer or Drush.

**Comment by webmasterpf** [comment]
Ok, is it Drush project better for my ask ?
How can I move to it ?
Then, is it possible to use a symlink like Drush9 instead of `vendor/drush/drush/drush`  ?

**Comment by normanlolx** [comment]
You don't move it. Since Drush 9 you always only install it as a local dependency.

> Drush only supports one install method. It requires that your Drupal site be built with Composer and Drush be listed as a dependency.

**Comment by webflo** [comment]
@leymannx Thanks for the support!
