### ISSUE TITLE
What is the rationale behind using webflo/drupal-core-require-dev metapackage

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupal-composer/drupal-composer-project#506]
Currently, dev dependencies are added through the [webflo/drupal-core-require-dev](https://github.com/webflo/drupal-core-require-dev) package. 

These are the downsides of using this instead of explicitly specifying versions:
- Not clear what packages are used by looking directly at `composer.json`.
- Need to keep in sync with another repository  => PRs need to be synchronised.

What are the advantages of using such approach in a Drupal project template?

**Comment by jcnventura** [comment]
See #348, for the rationale.

**Comment by AlexSkrypnyk** [comment]
From @webflo 
>The development dependencies got outdated over time. It was my goal to provide it as and standalone packages. I hope this makes it easier to update your project later on.

Well, it kinda _does not_ make it easier to update your project later on.

If the consumer project want to update a version of one of the dependencies or exclude it altogether, the developer would have to go to `webflo/drupal-core-require-dev` repo and copy/paste required dependencies. Since this project is a template, doing these actions defeats the purpose of the template, which is a kickstart with one command. 

Also, as others pointed out in https://github.com/drupal-composer/drupal-project/pull/348#issuecomment-362237776, it is "hard to override the dependencies on the fly" and it is hard to see what those dependencies are.

I would understand if that metapackage would be used in the specific consumer project, where it is controlled by a group of specific developers in specific company, but using it in a template like this (with so many community developers), makes dependencies inclusion not as transparent as expected from the template.

So, is it possible to move all `require-dev` back into `composer.json` for transparency?

**Comment by greg-1-anderson** [comment]
See also the discussion in #477.

**Comment by normanlolx** [comment]
`webflo/drupal-core-require-dev` has been replaced with `drupal/core-dev` in https://github.com/drupal-composer/drupal-project/pull/522.
