### ISSUE TITLE
Add FAQ describing each project included in composer.json

### ISSUE THREAD

**Issue by bunthorne** [drupal-composer/drupal-composer-project#507]
I want to be able to use a project like this to start my drupal project, but I want to be able to remove the projects that are purely for developers, such as drush and drupal console and those that have dev tool dependencies. My goal is for a very light install to manage a simple site. I have been able to figure it out for myself for the most part, but the most natural place for the information is right here in the project that creates the composer.json in the first place. Since the composer.json itself cannot be commented, could you put a simple description for each require and require-dev in the file that says what it does and whether it is required or optional for the drupal site?
Thanks

**Comment by normanlolx** [comment]
Easier would be you'd simply start to google every dependency yourself first. And when you're done and something's left unclear, you'd list the exact packages here and what exactly is unclear about them and we'll have a look what we can do to help you. Thanks

**Comment by bunthorne** [comment]
Easier? Not for any of the less-experienced users who are directed to your project from the drupal.org pages on how to build a site with composer and get a huge package of dependencies without knowing which of them they want or need.
This project makes decisions on what to include. It would be useful to users to document those decisions.

**Comment by normanlolx** [comment]
Easier as in: This project is open source, same as Drupal. If you find something's missing, you are asked to contribute. Maybe search the web for info about the packages that are unclear to you, learn what they are used for, and propose changes to the README in a pull request, adding the info you were missing in the first place.
