### ISSUE TITLE
console-en not included with project

### ISSUE THREAD

**Issue by girdzijauskas** [drupal-composer/drupal-composer-project#508]
After using 
`composer create-project drupal-composer/drupal-project:8.x-dev my-project --stability dev --no-interaction`

to create a new project, trying to run the console gives you a recursive loop that results in an out of memory on `src/vendor/drupal/console-core/src/Utils/TranslatorManager.php on line 108` 

This is because it's looking for a folder `console-en` in `vendor/drupal`, but it's not there.

Upon further inspection, previous projects that I created using the above command include the folder `console-en` - and the console is fixed by pasting that folder in.

What has changed recently to cause this behaviour?

**Comment by zaporylie** [comment]
I think it's a change to https://github.com/composer/installers/pull/311 that has been tagged as 1.7.0 yesterday.

**Comment by eiriksm** [comment]
Currently a fix for this might be:

```
diff --git a/composer.json b/composer.json
index a5453c7..46e7a27 100644
--- a/composer.json
+++ b/composer.json
@@ -178,6 +178,9 @@
       "drupal/core": [
         "type:drupal-core"
       ],
+      "vendor/drupal/{$name}": [
+        "drupal/console-en"
+      ],
       "drupal/libraries/{$name}": [
         "type:drupal-library",
         "vendor:npm-asset"
```

**Comment by eiriksm** [comment]
...and an actual fix in https://github.com/hechoendrupal/drupal-console-core/pull/364

**Comment by ghost** [comment]
For me https://github.com/hechoendrupal/drupal-console-core/pull/364 does not fix the issue of the install location.  Defining the composer/installers path does.

**Comment by eiriksm** [comment]
https://github.com/hechoendrupal/drupal-console-core/pull/364 is not supposed to fix the location. It is supposed to support the new location, and also avoid infinite recursion

**Comment by joshuaboltzmc** [comment]
I'm having this same issue after upgrading Drupal to 8.7. I assume there was some dependency along the lines with 8.7 that was also upgraded, such as Drupal console updated and now this issue is present. I'm noticing the issue in a Bitbucket pipelines where it's giving this error
`Container 'Build' exceeded memory limit.`

And inside a local Vagrant for the Drupal site, I am also seeing this error:
```
../bin/drupal --version
PHP Fatal error:  Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /home/vagrant/docroot/vendor/drupal/console-core/src/Utils/TranslatorManager.php on line 108

Fatal error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 262144 bytes) in /home/vagrant/docroot/vendor/drupal/console-core/src/Utils/TranslatorManager.php on line 108
```

**Comment by joshuaboltzmc** [comment]
I tried making the change from https://github.com/drupal-composer/drupal-project/issues/508#issuecomment-521127647, but it results in the same error I posted in my earlier comment.

**Comment by jcnventura** [comment]
As per hechoendrupal/drupal-console-core#364 (comment), we should add console/language to the .gitignore file.

**Comment by jmolivas** [comment]
This was related to an old PR https://github.com/composer/installers/pull/311 merged to the `composer/installers` repository that is no longer required.

But got fixed on latest release of the `drupal-console` project
https://github.com/hechoendrupal/drupal-console/releases/tag/1.9.3

**Comment by webflo** [comment]
Thanks! No changes required in this project.
