### ISSUE TITLE
Can't install because no matching package found

### ISSUE THREAD

**Issue by ericheydrich** [drupal-composer/drupal-composer-project#511]
Problem 1
    - webflo/drupal-core-require-dev 8.8.x-dev requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.x-dev requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.6 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.5 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.4 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.3 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.2 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.1 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.0-rc1 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.0-beta2 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.0-beta1 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.0-alpha2 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.0-alpha1 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - webflo/drupal-core-require-dev 8.7.0 requires behat/mink-selenium2-driver 1.3.x-dev -> no matching package found.
    - Installation request for webflo/drupal-core-require-dev ^8.7.0 -> satisfiable by webflo/drupal-core-require-dev[8.7.0, 8.7.0-alpha1, 8.7.0-alpha2, 8.7.0-beta1, 8.7.0-beta2, 8.7.0-rc1, 8.7.1, 8.7.2, 8.7.3, 8.7.4, 8.7.5, 8.7.6, 8.7.x-dev, 8.8.x-dev].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

**Comment by normanlolx** [comment]
What command did you run exactly before you got this error? In what environment? Mac, Windows, Raspberry Pi?

**Comment by rodrigoaguilera** [comment]
I think the problem is that the virtual branch 1.3.x-dev on behat/mink-selenium2-driver doesn't exist anymore because 1.4.0 was released. 

Relevant issue
https://www.drupal.org/project/drupal/issues/3078671

**Comment by ericheydrich** [comment]
I ran composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction on Ubuntu with PHP 7.0 and in second try with PHP 7.2.

**Comment by bojanz** [comment]
Also tracked in https://github.com/webflo/drupal-core-require-dev/issues/14

**Comment by jamie-tillman** [comment]
FYI, I was able to get composer to complete by adding this to the composer.json after the first failure and running `composer update`:
```
"behat/mink-selenium2-driver": "dev-master as 1.3.x-dev"
```
Not a long term fix, obviously, but I needed me some Drupal8 *now*.

**Comment by rindevich** [comment]
same issue for me, doesn't possible to create new project.

"behat/mink-selenium2-driver": "dev-master as 1.3.x-dev" - solution

**Comment by piratawww** [comment]
> FYI, I was able to get composer to complete by adding this to the composer.json after the first failure and running `composer update`:
> 
> ```
> "behat/mink-selenium2-driver": "dev-master as 1.3.x-dev"
> ```
> 
> Not a long term fix, obviously, but I needed me some Drupal8 _now_.

Works for me... Thx!!

**Comment by Cprofessionals** [comment]
> > FYI, I was able to get composer to complete by adding this to the composer.json after the first failure and running `composer update`:
> > ```
> > "behat/mink-selenium2-driver": "dev-master as 1.3.x-dev"
> > ```
> > 
> > 
> > Not a long term fix, obviously, but I needed me some Drupal8 _now_.
> 
> Works for me... Thx!!

Just for clarity, This line is to be put in the "required": section of the composer.json file.

Thanks piratawww. This worked great!

**Comment by Unifex** [comment]
The solution @jamie-tillman suggested worked for me too.

**Comment by CarlosRinconOmitsis** [comment]
The same and the solution @jamie-tillman suggesteds worked like a charm.

The code in my require section of composer.json:

    "require": {
        "php": ">=5.6",
        "composer/installers": "^1.2",
        "cweagans/composer-patches": "^1.6.5",
        "drupal-composer/drupal-scaffold": "^2.5",
        "drupal/console": "^1.0.2",
        "drupal/core": "^8.7.0",
        "drush/drush": "^9.0.0",
        "vlucas/phpdotenv": "^2.4",
        "webflo/drupal-finder": "^1.0.0",
        "webmozart/path-util": "^2.3",
        "zaporylie/composer-drupal-optimizations": "^1.0",
        "behat/mink-selenium2-driver": "dev-master as 1.3.x-dev"
    },

After edit composer.json: composer update --lock

**Comment by davehas1** [comment]
It seems like every time I install D8 using drupal-composer/drupal-project I have to visit this issue queue to overcome the latest 'cant install' error!

Thanks @jamie-tillman for the temporary fix :)

**Comment by ghost** [comment]
mink-selenium2-driver at version 1.3.1 now only on stable state. Ther's not version 1.3.dev - only 1.4.dev - at repo of this package

**Comment by ikachinskiy** [comment]
> What command did you run exactly before you got this error? In what environment? Mac, Windows, Raspberry Pi?

mink-selenium2-driver at version 1.3.1 now only on stable state. Ther's not version 1.3.dev - only 1.4.dev - at repo of this package

**Comment by ebremer** [comment]
@jamie-tillman solution worked for me too.

**Comment by greg-1-anderson** [comment]
This should be resolved now.  behat/mink-selenium2-driver created a `1.3` branch, which should obviate the need to use these workarounds.

**Comment by mglaman** [comment]
^ the 1.3 branch exists, but still hitting this problem

**Comment by greg-1-anderson** [comment]
You need to use minimum-stability dev, or the workaround `"behat/mink-selenium2-driver": "dev-master as 1.3.x-dev"` for this to work.

It would be easier if the 1.4.0 release was available. The request for that is at: https://github.com/minkphp/MinkSelenium2Driver/issues/269

**Comment by normanlolx** [comment]
If someone's still having issues with this, try to replace `webflo/drupal-core-require-dev` with `drupal/core-dev`.
