### ISSUE TITLE
--no-dev parse error

### ISSUE THREAD

**Issue by yktdan** [drupal-composer/drupal-composer-project#513]
Getting an error on selenium so I tried --no-dev to not require it and then get a parse error. See attached.
![composer-fail](https://user-images.githubusercontent.com/1762447/64171547-f703af80-ce20-11e9-9224-d301ce74b358.jpg)
![composer-fail2](https://user-images.githubusercontent.com/1762447/64171557-fd922700-ce20-11e9-9f4c-bfb5f4e6ab33.jpg)

**Comment by normanlolx** [comment]
Maintainer needs more info. Feel free to reopen if the issue persists. No screenshots of command line output please. Use code-highlighting instead. Thank you 🙂

**Comment by yktdan** [comment]
I can't recreate something that happened well over a year ago. If reports aren't looked at in reasonable time they should just be ignored as the reporter has almost certainly moved on.

**Comment by leymannx** [comment]
If you don't understand open source, please don't use it. Thank you 🙂
