### ISSUE TITLE
can't install drupal project with composer

### ISSUE THREAD

**Issue by sahraouilarbi** [drupal-composer/drupal-composer-project#529]
Using de command :
composer create-project drupal-composer/drupal-project:8.x-dev some-dir --no-interaction
I got the following error message

![Capture d’écran 2019-10-03 à 15 59 18](https://user-images.githubusercontent.com/1643972/66138618-d59c0c00-e5f6-11e9-901c-757f084495ed.png)

**Comment by normanlolx** [comment]
Please don't add sreenshots of error messages. Please paste them here and highlight them as code or blockquote instead. We also don't know what your environment is (PHP version, Composer version, OS etc.). You may want to provide this information as well to get your issue solved quickly.

**Comment by sahraouilarbi** [comment]
Resolved by the following command :
`sudo xcodebuild -license`

PHP 7.1.23
Composer version 1.8.4
OS : macOs 10.14.6 (18G103)

**Comment by webflo** [comment]
Great!
