### ISSUE TITLE
When trying to install / update composer I get Could not scan for classes inside "/app/vendor/phpunit/php-text-template/src/"

### ISSUE THREAD

**Issue by Chris-Archer-Upbeat** [drupal-composer/drupal-composer-project#536]
When trying to install / update composer I get:

```Could not scan for classes inside "/app/vendor/phpunit/php-text-template/src/" which does not appear to be a file nor a folder ```

**Comment by normanlolx** [comment]
Sorry for the late reply. You probably fixed the issue yourself already. If not please feel free to reopen it, by adding the exact steps to reproduce, most important: the comoser.json file and the exact commands you've run. Many thanks 🙏
