### ISSUE TITLE
how to deal with non-drupal dependencies of drupal modules?

### ISSUE THREAD

**Issue by michaellenahan** [drupal-composer/drupal-composer-project#54]
I wanted to install https://www.drupal.org/project/webprofiler.

```
composer create-project drupal-composer/drupal-project:8.x-dev dc1 --stability dev --no-interaction
cd dc1
composer require "drupal/webprofiler:8.2.0-beta15"
```

Error message was as follows:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for drupal/webprofiler 8.2.0-beta15 -> satisfiable by drupal/webprofiler[8.2.0-beta15].
    - drupal/webprofiler 8.2.0-beta15 requires isagalaev/highlight.js 8.* -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

I wonder what the problem is here? Is it that https://packagist.drupal-composer.org does not know about isagalaev/highlight.js?

Ah. I guess I need to add github under "repositories". Will try that tomorrow :)

**Comment by webflo** [comment]
There are several things wrong in webprofilers [composer.json](http://cgit.drupalcode.org/webprofiler/tree/composer.json).
- The "repositories" key is only supported on root packages. It means composer will not resolve this repo. https://getcomposer.org/doc/04-schema.md#repositories
- The autoload definition. "vendor/symfony/stopwatch/Symfony/Component/Stopwatch/Stopwatch.php" is not part of drupal/webprofiler package.
- The package type is not valid. Should be "drupal-module"

**Comment by webflo** [comment]
Please follow https://www.drupal.org/node/2502489
