### ISSUE TITLE
Drush packages are installed in path that is not in gitignore

### ISSUE THREAD

**Issue by Dropa** [drupal-composer/drupal-composer-project#540]
Contrib drush packages are intended to be ignored in gitignore, but in path `./drush/contrib/` 

https://github.com/drupal-composer/drupal-project/blob/8.x/.gitignore#L2

Composer installs drush packages into `./drush/Commands/contrib/`
https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L77

Not sure which one is incorrect, but probably gitignore is easier to fix

**Comment by normanlolx** [comment]
Sorry for the late reply. Do you maybe have a sample Drush package at hand to reproduce that? This would help a lot. Many thanks!

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
