### ISSUE TITLE
drush updatedb -y gives syntax error.

### ISSUE THREAD

**Issue by Pates93** [drupal-composer/drupal-composer-project#542]
Hello. I have been trying to update my website to the newest version of drupal core. Composer update works fine, but when I run drush updatedb -y it gives me a syntax error. Any help much appreciated.

Command prompt output can be seen below.

C:\inetpub\wwwroot\myProject\web>drush updatedb -y

 ---------- ------------------------------------------- --------------- -----------------------------------------------
  Module     Update ID                                   Type            Description
 ---------- ------------------------------------------- --------------- -----------------------------------------------
  system     8801                                        hook_update_n   Remove 'path.temporary' config if redundant.
  system     8802                                        hook_update_n   Fix system.theme:admin when the default theme
                                                                         is used as the admin theme.
  system     8803                                        hook_update_n   Install the 'path_alias' entity type.
  system     8804                                        hook_update_n   Convert path aliases to entities.
  system     8805                                        hook_update_n   Change the provider of the 'path_alias'
                                                                         entity type and its base fields.
  locale     8800                                        hook_update_n   Clear Locale project storage to use new 'all'
                                                                         instead of 8.x in URLs.
  embed      8101                                        hook_update_n   Moved to
                                                                         embed_post_update_convert_encoded_icon_data()
                                                                         .
  embed      convert_encoded_icon_data                   post-update     Convert embed button icons from managed files
                                                                         to encoded data.
  path       create_language_content_settings            post-update     Create the language content settings
                                                                         configuration object for path aliases.
  search     block_page                                  post-update     Configures default search page for
                                                                         instantiated blocks.
  system     entity_reference_autocomplete_match_limit   post-update     Populate the new 'match_limit' setting for
                                                                         the ER autocomplete widget.
  system     layout_plugin_schema_change                 post-update     Clear the schema cache.
  taxonomy   configure_status_field_widget               post-update     Add status with settings to all form displays
                                                                         for taxonomy entities.
  text       add_required_summary_flag                   post-update     Update text_with_summary fields and widgets
                                                                         to add summary required flags.
  views      limit_operator_defaults                     post-update     Define default values for limit operators
                                                                         settings in all filters.
  views      remove_core_key                             post-update     Remove core key from views configuration.
 ---------- ------------------------------------------- --------------- -----------------------------------------------

 // Do you wish to run the specified pending updates?: yes.

>  [notice] Update started: system_update_8801
>  [notice] Update completed: system_update_8801
>  [notice] Update started: system_update_8802
>  [notice] Update completed: system_update_8802
>  [notice] Update started: system_update_8803
>  [notice] The "path_alias" entity type has been installed.
>  [notice] Update completed: system_update_8803
>  [notice] Update started: system_update_8804
>  [notice] Path aliases have been converted to entities.
>  [notice] Update completed: system_update_8804
>  [notice] Update started: system_update_8805
>  [notice] Update completed: system_update_8805
>  [notice] Update started: locale_update_8800
>  [notice] Update completed: locale_update_8800
>  [notice] Update started: embed_update_8101
>  [notice] Update completed: embed_update_8101
>  [notice] Update started: embed_post_update_convert_encoded_icon_data
>  [notice] Update completed: embed_post_update_convert_encoded_icon_data
>  [notice] Update started: path_post_update_create_language_content_settings
>  [notice] Update completed: path_post_update_create_language_content_settings
>  [notice] Update started: search_post_update_block_page
>  [notice] Update completed: search_post_update_block_page
>  [notice] Update started: system_post_update_entity_reference_autocomplete_match_limit
>  [notice] Update completed: system_post_update_entity_reference_autocomplete_match_limit
>  [notice] Update started: system_post_update_layout_plugin_schema_change
>  [notice] Update completed: system_post_update_layout_plugin_schema_change
>  [notice] Update started: taxonomy_post_update_configure_status_field_widget
>  [notice] Update completed: taxonomy_post_update_configure_status_field_widget
>  [notice] Update started: text_post_update_add_required_summary_flag
>  [notice] Update completed: text_post_update_add_required_summary_flag
>  [notice] Update started: views_post_update_limit_operator_defaults
>  [notice] Update completed: views_post_update_limit_operator_defaults
>  [notice] Update started: views_post_update_remove_core_key
>  [notice] Update completed: views_post_update_remove_core_key

In ProcessBase.php line 188:

  Unable to decode output into JSON: Syntax error

  {
      "0": {
          "system": {
              "8801": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "update"
              },
              "8802": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "update"
              },
              "8803": {
                  "results": {
                      "query": "The "path_alias" entity type has been installed.",
                      "success": true
                  },
                  "type": "update"
              },
              "8804": {
                  "results": {
                      "query": "Path aliases have been converted to entities.",
                      "success": true
                  },
                  "type": "update"
              },
              "8805": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "update"
              },
              "entity_reference_autocomplete_match_limit": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              },
              "layout_plugin_schema_change": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          },
          "locale": {
              "8800": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "update"
              }
          },
          "embed": {
              "8101": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "update"
              },
              "convert_encoded_icon_data": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          },
          "path": {
              "create_language_content_settings": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          },
          "search": {
              "block_page": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          },
          "taxonomy": {
              "configure_status_field_widget": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          },
          "text": {
              "add_required_summary_flag": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          },
          "views": {
              "limit_operator_defaults": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              },
              "remove_core_key": {
                  "results": {
                      "query": null,
                      "success": true
                  },
                  "type": "post_update"
              }
          }
      },
      "drush_batch_process_finished": true
  }

updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]] [--no-cache-clear] [--no-post-updates] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command>

**Comment by normanlolx** [comment]
This issue queue is for issues with the Composer template. Not with Drupal core or Drush.

Maybe related: https://www.drupal.org/project/drupal/releases/8.8.0

> ### Changes to path aliases and a critical note for sites using the Pathauto contributed module
> 
> * If you have the contributed Pathauto module enabled, you must update to the latest version of Pathauto before or at the same time as you update to Drupal 8.8.0. **Failure to update Pathauto before updating core could result in data loss**. Drupal 8.8.0 declares a conflict with Pathauto 8.x-1.5 or lower for this reason.
> * If you are using the Subpathauto contributed module, you must update to the latest version of Subpathauto to be able to run updates via update.php.
> * The Path Alias core subsystem has been moved to the path_alias module. An upgrade path is provided from Drupal 8.7 for this change.
> * Custom URL aliases are now provided by a new revisionable and publishable path_alias content entity type. Path alias services have been kept in place for backwards compatibility, and path alias hooks have been deprecated.
> * As part of the change to path aliases, path alias administration forms have been converted to generic entity forms. This means form IDs and form class names have changed, so custom code needs to be updated for any hook_form_alter() or hook_form_FORM_ID_alter() implementations that were using the previous form IDs. Additionally, some path routes have been deprecated and replaced by generic entity route.
