### ISSUE TITLE
ScriptHandler.php should be automatically upgraded

### ISSUE THREAD

**Issue by gagarine** [drupal-composer/drupal-composer-project#545]
The project should not upgrade himself?

Typically after https://github.com/drupal-composer/drupal-project/issues/539 people have to manually copy/past the files?

**Comment by normanlolx** [comment]
No this whole project is just a template. If you want to get the latest changes you need to git diff and adjust manually. I know this might be frustrating but it's a chicken-or-the-egg problem somehow and can't be easily fixed. We first would need proper releases for that (https://github.com/drupal-composer/drupal-project/issues/425). And then maybe have some mechanism that at least notifies you the next time you `composer update` about possible changes to be done. That's a lot. For now it's won't fix, I'm sorry.
