### ISSUE TITLE
Updating core and module is not enough

### ISSUE THREAD

**Issue by gagarine** [drupal-composer/drupal-composer-project#546]
There is dependencies that are not going to be updated by running` composer update drupal/core drupal/core-dev --with-dependencies`

Some it's because the core didn't update them yet. But other is just because they are not part of the core. Would be so much easier if we can just do a `composer update`.

`composer outdated`
![Screenshot 2019-12-28 at 13 45 33](https://user-images.githubusercontent.com/164074/71543868-83118800-2978-11ea-85a6-ed0359e3aaf7.png)

**Comment by normanlolx** [comment]
Not sure if I understand. What exactly did you expect to be updated, but didn't update? You could just run `composer update --with-dependencies` to update everything. Or try `composer update drupal/core 'drupal/core-*' --with-all-dependencies`. Or try `composer update "drupal/*" --with-dependencies`. Feel free to reopen is this still is an issue.
