### ISSUE TITLE
Update ScriptHandler to support symlinks

### ISSUE THREAD

**Issue by SkywardRay** [drupal-composer/drupal-composer-project#549]
We use docker-project in our single command rollout of new projects. The /sites/default/files directory is created by the ScriptHandler and afterward the /sites/default/files directory is then symlinked by wodby for use with docker. 

This is all working fine, the problem comes with the post-update-cmd and post-install-cmd events. They are run multiple times during our creation process and createRequiredFiles check if the /sites/default/files directory exists every times. Which causes an exception because it doesn't exist it is actually a symlink now.

I would love to fix this problem and I have come up with 2 solutions:
- Check if directories are symlinks if they don't exist.
- Only run the createRequiredFiles method only in the post-create-project-cmd event instead of every time.

How do you feel about this?

**Comment by normanlolx** [comment]
Sounds good. You can simply adjust the ScriptHandler.php in your project.

**Comment by SkywardRay** [comment]
I've tested locally and a simple change to the ScriptHandler would fix this problem on our end, I have made a pull request here: https://github.com/drupal-composer/drupal-project/pull/551

**Comment by AlexSkrypnyk** [comment]
Committed to both `10.x` and `11.x`.
