### ISSUE TITLE
Composer install deletes modules and themes

### ISSUE THREAD

**Issue by andyvanee** [drupal-composer/drupal-composer-project#55]
This may be related to #1 and #5, but this project should have a huge disclaimer: DO NOT put your modules or themes in the normal place! `composer install` or `composer update` may delete them all if `drupal/drupal` updates or re-installs.

Here are the basic steps to reproduce:

```
composer create-project drupal-composer/drupal-project:7.x-dev --stability dev --no-interaction drupal_site
cd drupal_site
mkdir web/sites/all/themes/example
mkdir web/sites/all/modules/example
touch web/sites/all/themes/example/example.info
touch web/sites/all/modules/example/example.info
# vendor isn't committed to repo...
rm -rf vendor
# now to wipe out all my work in themes and modules
composer install
```

I now see that my themes and modules should have been placed in a `contrib` sub-directory, but I don't think I'd be the first to make that mistake. Is there a reason not to preserve paths on the themes and modules directories themselves?

**Comment by webflo** [comment]
@derhasi to the rescue!

**Comment by tobiasbaehr** [comment]
Thats absolute ok so. ,-)

For composer the web/sites/all/modules/example is part of drupal-core. Because no composer type use it in extra -> installer-paths and it is also not excluded via extra -> preserve-paths

And because web/sites/all/modules/example is not in core therefore composer delete it.

**Comment by jcnventura** [comment]
As per [Basic Directory Structure of a Drupal 7 Project](https://www.drupal.org/node/2621480), you should place any non-contrib module in sites/all/modules/custom. The project will preserve anything in that directory.

**Comment by andyvanee** [comment]
Thanks for the feedback :)

I'm fine with this closed since it's been quite some time since I've worked with D7, but I remember losing work due to this. That page doesn't seem to state that in any absolute terms the way I'm reading it? What it says is:

> **/sites/all/modules/custom:** Often Drupal users place here their custom modules.
>
> You're most safe, if you even place your custom modules in the /sites/all/modules folder.

**Comment by derhasi** [comment]
Just for documentation: The reason for this behaviour is, that the `drupal-composer/preserve-paths` configuration (in https://github.com/drupal-composer/drupal-project/blob/7.x/composer.json#L77) is set to `sites/all/modules/custom`. If you want to persist another modules directory, you have to add it in the configuration there.

`drupal-composer/preserve-paths` is only needed in D7.

**Comment by jigarius** [comment]
For me, it just deleted the `sites/default/files` directory! Also, it changes the permissions every time I execute composer commands. Is that normal?

**Comment by jcnventura** [comment]
It will delete it, unless it is configured to preserve it. That's why the template configures that path to be preserverd. As to setting permissions on sites/default, yes it is very normal. Not only when you execute composer, but also when you run Drupal.

**Comment by sandykadam** [comment]
Hi Guys,

This thread is old but I have relevant issue, my custom modules are in `dist/sites/myproject.com/modules/custom/modulename`

I have added this in preserve-path 
`"preserve-paths": [
      "dist/sites/myproject.com"
    ]`

But it still removes the whole dist directory and resintall if update or install. How can we retain it irrespective of action.

**Comment by jcnventura** [comment]
Hi, The way preserve-paths works is that it does a temporary copy and then restores that after composer has installed, it should just work, but truth be told, it is a project that is not actively maintained.

I'm going to assume that "dist/" is configured as your web root.

Nowadays, I'd recommend that you move that myproject.com out of dist/sites and place it in a sites directory at the repo root level (i.,e same level as dist and the composer.json. Then create a symlink to it from dist/sites/myproject.com, and keep the preserve-paths setting to restore that symlink.

Then again, if it is a bug with drupal-composer/preserve-paths, please report that in the issue queue there: https://github.com/drupal-composer/preserve-paths/issues
