### ISSUE TITLE
Make zaporylie/composer-drupal-optimizations a dev dependency?

### ISSUE THREAD

**Issue by mikemccaffrey** [drupal-composer/drupal-composer-project#555]
The package readme for zaporylie/composer-drupal-optimizations instructs you to require it as a dev dependency, since it is only intended to be effective on updates and requires: https://github.com/zaporylie/composer-drupal-optimizations

Is there any reason that it should be a non-dev dependency? Does it do something to improve composer performance on a simpler composer install?

**Comment by normanlolx** [comment]
It was added in https://github.com/drupal-composer/drupal-project/pull/442 to reduce the memory usage in general. Ping @zaporylie.

**Comment by webflo** [comment]
The plugin is not needed with Composer 2.
