### ISSUE TITLE
composer install and composer require should not rewrite .htaccess and other files

### ISSUE THREAD

**Issue by tinamrak** [drupal-composer/drupal-composer-project#556]
I've been using this project for all my Drupal sites and I noticed one thing that bothers me.

When requiring new modules locally or running composer install on production (I use git for deployment) the following files will *always* be overwritten.

![Screenshot](https://i.imgur.com/lbbIpF2.png)

I understand that this is done on `composer create-project` and `composer update` but why when requiring new modules?

Is there any way to prevent this?

**Comment by tinamrak** [comment]
I was sure that this didn't happen in the past so I explored a little further (thanks [Zan](https://github.com/zanvidmar) for helping me) and found that this happens since `drupal-composer/drupal-scaffold` was changed to `drupal/core-composer-scaffold`. Related issue: https://github.com/drupal-composer/drupal-project/pull/522

Are there any downsides if I keep the old (`drupal-composer/drupal-scaffold`) package?

**Comment by tinamrak** [comment]
I found a solution but this will also exclude these files on `composer update`: [Excluding Scaffold Files](https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_6)

I'm not an expert in composer but is it possible to somehow disable exclusion on `composer update`?

**Comment by normanlolx** [comment]
Maybe use the approach covered on the same page under [Altering Scaffold Files](https://www.drupal.org/docs/develop/using-composer/using-drupals-composer-scaffold#toc_4). By that you always use the core scaffold files and apply your own patches to make them look like you want. When you `$ composer update` and there are changes in these files you'll recognise it by your patches failing to apply. You then can review and readjust your patches accordingly. https://drupal.stackexchange.com/a/290990/15055

But let's continue this discussion somewhere else. It's off-topic here.

**Comment by joestewart** [comment]
Relevant core issue: "Avoid re-scaffolding unchanged files (and printing scaffold file information over and over)" https://www.drupal.org/project/drupal/issues/3103090

**Comment by tinamrak** [comment]
Thank you both!
I also found this issue: https://www.drupal.org/project/drupal/issues/3092563

> Scaffold files should not be modified in Composer-managed Drupal sites; instead, users are expected to use "append" or "patch" capabilities to add their custom content to the Drupal-provided files. Some users do not know this yet, though, so some additional behavior to detect and warn users who modify the generate files is being proposed.

I am closing this.
