### ISSUE TITLE
Drupal 9

### ISSUE THREAD

**Issue by kamalkech** [drupal-composer/drupal-composer-project#557]
Hi 
Drupal 9 beta was already available 
there is no branch for this new version ?

**Comment by normanlolx** [comment]
Maybe start one by providing a pull request ?

**Comment by jcnventura** [comment]
Why use this instead of drupal/core-composer-scaffold ?

**Comment by kamalkech** [comment]
@jcnventura because this is better than drupal/core-composer-scaffold that has just 9 starts for now

**Comment by pjoulot** [comment]
@jcnventura And this project is already using it:
`
"drupal/core-composer-scaffold": "^8.8.0",`

https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json

**Comment by Natshah** [comment]
Use **drupal/recommended-project** it's the new drupal recommended project template
https://github.com/drupal/recommended-project

**Comment by normanlolx** [comment]
Sorry I didn't remember this issue when I opened #568. I provided a PR and install instruction for Drupal 9 over there now.

**Comment by kamalkech** [comment]
I found this https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies

what about drupal console !

**Comment by normanlolx** [comment]
@kamalkech – Regarding Drupal Console see https://github.com/drupal-composer/drupal-project/issues/568#issuecomment-653398677. Maybe let's close this issue as duplicate (although it happened to be created earlier, yes).

@kamalkech – Regarding drupal/recommended-project see https://github.com/drupal-composer/drupal-project/issues/538
