### ISSUE TITLE
Remove PHP 7.1 form Travis CI builds since 7.1 is not supported / EOL

### ISSUE THREAD

**Issue by shrop** [drupal-composer/drupal-composer-project#562]
Remove PHP 7.1 builds/tests for Drupal Project since it is no longer supported by the PHP Community. PHP 7.1 is EOL with no further security updates as of December 1st, 2019. See: https://www.php.net/supported-versions.php.

**Comment by shrop** [comment]
Also removed PHP 7.0 since it was still in there too.

**Comment by shrop** [comment]
@joestewart mentioned something in Drupal Slack that might weigh-in on this one:

"Not sure about drupal-project.  Drupal 8.8 still supports >-7.0.8. "

**Comment by jcnventura** [comment]
This should probably be revisited only in November 2021, then (https://www.drupal.org/docs/understanding-drupal/drupal-9-release-date-and-what-it-means/what-happens-to-drupal-8-now-that)

But I wonder if this project is still useful for anything other than the Drupal 7 branch.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
