### ISSUE TITLE
Upgrade instructions to Drupal 9 for existing projects

### ISSUE THREAD

**Issue by andeersg** [drupal-composer/drupal-composer-project#565]
I'm trying to upgrade to Drupal 9.0.0-rc1. But I run into errors such as:
```
- Installation request for symfony-cmf/routing (locked at 1.4.1) -> satisfiable by symfony-cmf/routing[1.4.1].
```
Should all these packages be required at 9.0.0-rc1?
```
"drupal/core": "^8.8.0",
"drupal/core-composer-scaffold": "^8.8.0",
"drupal/core-dev": "^8.8.0"
```

Or is that the wrong approach? Could be a nice instruction to have in the readme maybe.

**Comment by geerlingguy** [comment]
FYI, I've had this issue as well on my live stream: https://github.com/geerlingguy/drupal-for-kubernetes/issues/29

**Comment by geerlingguy** [comment]
During the live stream, while trying to upgrade, I deleted the composer.lock file and vendor directory, then updated dependencies `drupal/core-composer-scaffold` and `drupal/core` to `^9.0`, then tried running `composer install -vvv`, but it didn't seem to work. I was using the drupal-project recommended template so maybe there's some cruft left over from that.

**Comment by andeersg** [comment]
I think I figured something out. I followed https://www.drupal.org/docs/upgrading-drupal/upgrading-from-drupal-8-to-drupal-9-or-higher, but had to add `drupal/core`:
```
composer require drupal/core-recommended:^9.0.0 drupal/core-composer-scaffold:^9.0.0 drupal/core:^9.0.0  --update-with-dependencies --no-update

composer require drupal/core-dev:^9.0.0 --dev --update-with-dependencies --no-update

composer update
```
Then it upgraded without errors. But maybe `drupal/core` should be removed now that `drupal/core-recommended` is present?

**Comment by andeersg** [comment]
Removing `drupal/core` seems to work.

**Comment by lchabrand** [comment]
Hi, did you find the best solution ?

**Comment by andeersg** [comment]
What seems to work is:
```
composer require drupal/core-recommended:^9.0.0 drupal/core-composer-scaffold:^9.0.0 drupal/core:^9.0.0  --update-with-dependencies --no-update

composer require drupal/core-dev:^9.0.0 --dev --update-with-dependencies --no-update

composer update

composer remove drupal/core
```
Only tested locally, but that seems to work fine. And keeps all the good parts of this project :)

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
