### ISSUE TITLE
Should we commit console directory

### ISSUE THREAD

**Issue by mstrelan** [drupal-composer/drupal-composer-project#567]
Drupal console installs a whole lot of translation files in to the console directory. Should this be gitignored or committed?

**Comment by simesy** [comment]
It depends on your project whether you want to ship custom console configuration.

**Comment by mstrelan** [comment]
Fair enough. I am thinking of ignoring `console/language/console-en/translations` but wonder if I should just ignore `console/language`.

**Comment by simesy** [comment]
I personally ignore all of it by default, i guess you'd know what you wanted and why?

**Comment by mstrelan** [comment]
> I personally ignore all of it by default

Nice, that's what I wanted to hear.

> i guess you'd know what you wanted and why?

If only that was true. I assume custom stuff can go somewhere in here and the stuff mentioned above looks more like third-party dependencies. It feels like committing `/vendor`. I guess if I ever stuck something custom under `/console` I'd know what needs to be kept, and in the meantime I can ignore the lot.

Wondering if something sensible should be added to the README or default .gitignore file.

**Comment by simesy** [comment]
So looks like it's storing settings equivalent to drushrc.php. you could pass arguments direct to console commands (which is what I do) or have defaults come from yml in that directory. Closest to docs i found was https://github.com/hechoendrupal/drupal-console/issues/2725#issuecomment-248549287

**Comment by joestewart** [comment]
Isn't #509 relevant?

**Comment by mstrelan** [comment]
Thanks @joestewart apparently my search skills are lacking.
