### ISSUE TITLE
I get this "ERR_TOO_MANY_REDIRECTS" when I try to install Drupal.

### ISSUE THREAD

**Issue by steveoriol** [drupal-composer/drupal-composer-project#578]
When clicking on "Save and continue" /core/install.php for new installation I get the error of ERR_TOO_MANY_REDIRECTS....?
This is certainly not a problem with "drupal-project" because if I use "recommended-project", I get the same error ...
Do you have any idea why I got this error ?
I tried to install for a site or for multi-sites, it is the same thing.

**Comment by steveoriol** [comment]
In fact, if I choose "English" as language instead of my default "French" language, the installation works ...

**Comment by normanlolx** [comment]
Hard to tell. Please feel free to add more information like the exact commands you used to install the project and your composer.json to let us reproduce the issue and then reopen it. Honesty sounds more like a core bug (if reproducible), which should be filed at https://www.drupal.org/project/issues/drupal.
