### ISSUE TITLE
Problem With Drupal 7 Installs and Updates

### ISSUE THREAD

**Issue by ElusiveMind** [drupal-composer/drupal-composer-project#582]
Installing or updating Drupal 7 sites with this project results in the following

![Screen Shot 2020-11-18 at 2 14 19 PM](https://user-images.githubusercontent.com/195676/99579576-5b6e4880-29ac-11eb-99fa-c5d88e4d3cfe.png)

Happens on install
Happens on update. Attempting to update from 7.73

**Comment by normanlolx** [comment]
What command did you use to update? And how does your composer.json look like? Please add more info to reproduce this problem and feel free to reopen the issue if the problem still persists.
