### ISSUE TITLE
The .env file is not created or copied over when using this template

### ISSUE THREAD

**Issue by xmacinfo** [drupal-composer/drupal-composer-project#588]
Loading the site complains that the .env file is missing.

`Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read any of the environment file(s) at [/Users/jacques/web/Sites/tests/drupal91modules/.env]. in /Users/jacques/web/Sites/tests/drupal91modules/vendor/vlucas/phpdotenv/src/Store/FileStore.php:68 Stack trace: #0 /Users/jacques/web/Sites/tests/drupal91modules/vendor/vlucas/phpdotenv/src/Dotenv.php(222): Dotenv\Store\FileStore->read() #1 /Users/jacques/web/Sites/tests/drupal91modules/load.environment.php(18): Dotenv\Dotenv->load() #2 /Users/jacques/web/Sites/tests/drupal91modules/vendor/composer/autoload_real.php(73): require('/Users/jacques/...') #3 /Users/jacques/web/Sites/tests/drupal91modules/vendor/composer/autoload_real.php(63): composerRequireece7909b1d5e2d37f32969d163ed945d('d511210698f02d8...', '/Users/jacques/...') #4 /Users/jacques/web/Sites/tests/drupal91modules/vendor/autoload.php(7): ComposerAutoloaderInitece7909b1d5e2d37f32969d163ed945d::getLoader() #5 /Users/jacques/web/Sites/tests/drupal91modules/web/autoload.php(16): require('/Users/jacq in /Users/jacques/web/Sites/tests/drupal91modules/vendor/vlucas/phpdotenv/src/Store/FileStore.php on line 68`

I had to manually copy over the `.env` file from web/core to be able to load the install.php page.

**Comment by normanlolx** [comment]
This was caused by #584 and has been fixed again in #589.
