### ISSUE TITLE
Composer breaking my Drupal9 installation.

### ISSUE THREAD

**Issue by strben** [drupal-composer/drupal-composer-project#591]
Hello all... 

I think I posted this in the wrong area.  Didn't realize there was a special drupal-composer area.

https://github.com/composer/composer/issues/9597

Basically I am trying to use composer to install "defuse/php-encryption" but composer also tries to install Drupal-Core 9.1.2 even though I already have that installed and working.  It is overwriting something I guess because when it completes, my Drupal is broken and I have to restore from backups.

Please see link above.

Thank you!

**Comment by normanlolx** [comment]
Hey @strben this issue queue is for issues related to the `"name": "drupal-composer/drupal-project"` named project. You are using `"name": "drupal/legacy-project"` which says `"Project template for Drupal 9 projects with composer following drupal/drupal layout"` in its description. `drupal/drupal` [is deprecated](https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies#deprecated-drupal-drupal) and for `drupal/legacy-project` it says the following in the [official docs](https://www.drupal.org/docs/develop/using-composer/starting-a-site-using-drupal-composer-project-templates#s-drupallegacy-project):

> Use the legacy project layout only if there is some reason why you cannot use the recommended project layout.

However, this is more of a core issue and you might create a support request in the [core issue queue](https://www.drupal.org/project/issues/drupal) or on [Drupal Answers](https://drupal.stackexchange.com/). But the very best would actually be you try to refactor your project to either use [this](https://github.com/drupal-composer/drupal-project/blob/9.x/composer.json) (community) or [this](https://github.com/drupal/recommended-project/blob/9.1.2/composer.json) (core) composer.json file.
