### ISSUE TITLE
Non-English setup

### ISSUE THREAD

**Issue by WardinT** [drupal-composer/drupal-composer-project#596]
I think the translations directory needs to be included within /sites/default/files via post-install script.

However I dare not modifying as I may not be aware of undesired side-effects.

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
