### ISSUE TITLE
Docummentation / Drupal version DEV

### ISSUE THREAD

**Issue by kamalkech** [drupal-composer/drupal-composer-project#603]
In documentation you mentioned to download drupal version dev!!!
`composer create-project drupal-composer/drupal-project:9.x-dev some-dir --no-interaction`

That's not good idea, you should use version release instead of dev !!
i try to choose drupal-project:9.2.0 or drupal-project:9.x but not found !

**Comment by normanlolx** [comment]
Have you tried it out? What version of core did you get? Dev relates to this project template which has no releases. It doesn't relate to core.
