### ISSUE TITLE
Composer could not find a composer.json

### ISSUE THREAD

**Issue by n00bhax** [drupal-composer/drupal-composer-project#604]
Trying a fresh install of drupal 9 using this project. 
I'm very new to composer, drush and drupal. 

> When installing the given composer.json some tasks are taken care of:

To install the json, I assume "php composer.phar install" must be ran, but this gives the following:

> Composer could not find a composer.json file in /home/mydir
> To initialize a project, please create a composer.json file. See https://getcomposer.org/basic-usage

The .json is in another directory than the composer.phar file.

**Comment by n00bhax** [comment]
It seems that going into the directory helps...

![image](https://user-images.githubusercontent.com/28760191/130495555-10b4783f-25d6-42f9-b121-ecb802a4a9f3.png)

Is git necessary to complete the installation? 
This wasn't the case I think with drupal/recommended-project

**Comment by normanlolx** [comment]
Yes you need to be inside a directory with a valid composer.json when running the install command. Alternatively run the create-project command from the README which will create the project in a new, given directory (replace some-dir with any other directory name). Yes seems git is necessary.
