### ISSUE TITLE
Issue with vlucas/phpdotenv and Composer 2.2

### ISSUE THREAD

**Issue by tstoeckler** [drupal-composer/drupal-composer-project#608]
Due to https://github.com/composer/composer/pull/10065 Composer will now require any files specified as part of the autoloader when executing scripts and plugins, so in particular for this repo this that  means `load.environment.php` will be loaded when the `composer/installers` plugin is installed, which might be before `vlucas/phpdotenv` is installed. Requiring the file then results in

> Fatal error: Uncaught Error: Class 'Dotenv\Dotenv' not found in .../load.environment.php:14

Probably checking `class_exists()` and just bailing if that's false is fine? But not sure...

**Comment by edurenye** [comment]
Got the same error, for now my workaround is to stick with version `2.1.14`.

**Comment by mroest** [comment]
Same issue here...

**Comment by edurenye** [comment]
This seem to have been fixed in https://github.com/composer/composer/issues/10382, you can test using `composer self-update --snapshot`. At least it worked for me.
