### ISSUE TITLE
Pantheon?

### ISSUE THREAD

**Issue by kostajh** [drupal-composer/drupal-composer-project#61]
Lovely project. Has anyone used this successfully with Pantheon? They assume that the Drupal site lives in the root of the repo (not the `web`) subdirectory.

**Comment by webflo** [comment]
@greg-1-anderson Can you help?

**Comment by greg-1-anderson** [comment]
I have not built such a thing myself yet, but I will at some point.  The steps you'd have to go through to make this project work shouldn't be too involved.

The easiest way to adapt this project to Pantheon would be to modify the composer.json file to relocate the 'vendor' directory to web/vendor.  After that, you would need to once again edit the autoload.php file at web/autoload.php to include the autoloader at vendor/autload.php (just like the standard one in Drupal core).

Next, take the files .gitignore, sites/default/settings.php and sites/default/settings.pantheon.php, and copy them into your project.  At some point, Pantheon will provide a project that you can `require` to get the necessary settings.pantheon.pp file.  With this model, you should be able to run 'composer update' from the root of your project to update your code, and then you'd just need to copy the 'web' directory to the root of your Pantheon site.  There are some scripts to do this sort of thing in https://github.com/pantheon-systems/example-drupal7-circle-composer which could be adapted to this purpose. 

As of Drupal-8.0.0-rc1, your other option is to just use the composer.json bundled with Drupal to manage your file. Just cd to the project root, and you may use 'composer require' to pull in your Drupal modules and themes.  Using this technique, you would use composer to update your dependencies, and `drush pm-updatecode` to update Drupal core.  Note that `pm-updatecode` is presently broken with Drupal 8.  Hopefully this too will be resolved soon; see https://github.com/drush-ops/drush/pull/1685 and https://github.com/drush-ops/drush/issues/1701.

**Comment by kostajh** [comment]
@greg-1-anderson thanks so much for the detailed reply. Based on that, I guess I'm not totally clear on the advantages of using this project versus what `8.0.0-rc1` allows via its `composer.json`, so I'll experiment a bit to see for myself. Meanwhile, I think there's enough info here to close out the issue but I'll leave that for @webflo. Thanks all!

**Comment by greg-1-anderson** [comment]
If you use the composer.json in 8.0.0-rc1/2, `composer update` will not update Drupal core, but it will update all of the modules you added via `composer require`.

**Comment by webflo** [comment]
Alright, feel free to re-open if you have any questions.

**Comment by greg-1-anderson** [comment]
Note also that https://github.com/drupal-composer/drupal-project/pull/77, once merged, will get us a lot closer to being able to use this project on Pantheon. Just a few changes to composer.json will be needed. The same should be true of other providers, like Acquia. Not sure how we are going to manage the differences -- this is not necessarily the responsibility of this project.  We're moving in the right direction to make it easy, though.
