### ISSUE TITLE
Installs drush 10.6 which is end-of-life

### ISSUE THREAD

**Issue by leducvin** [drupal-composer/drupal-composer-project#611]
Apologies if this has already been raised, but on branch 9.x, this install drush 10.6, which per https://www.drush.org/latest/install/ is end-of-life since Jan 2022.

The officially recommended version, and compatible with php 7.4, is now drush 11. Unless there's reasons I'm unaware of to still use drush 10.

**Comment by webflo** [comment]
Thanks! Fixed it

**Comment by leducvin** [comment]
Oops. Might have found a reason for keeping drush 10.6.

From Readme.md:
> This project supports PHP 7.3 as minimum version

This should probably be updated to say it supports PHP 7.4 as a minimum? Or revert to drush 10.6.

**Comment by webflo** [comment]
PHP 7.4 is the minimum recommended version for Drupal 9.4. https://www.drupal.org/project/drupal/releases/9.4.0 => "Platform requirements changes"

**Comment by normanlolx** [comment]
@leducvin you can provide an MR updating the README

**Comment by leducvin** [comment]
@leymannx of course, here you go: #612
