### ISSUE TITLE
update-scaffold fails on OS X

### ISSUE THREAD

**Issue by zxaos** [drupal-composer/drupal-composer-project#62]
`/tmp` doesn't necessarily exist so the script just dies immediately.

**Comment by deviantintegral** [comment]
Weird - /tmp has always existed for me on OS X. What causes it to be missing?

**Comment by zxaos** [comment]
Not sure - I was on an El Capitan machine and the script failed because the folder was missing. If there's no other instances of it, maybe I just had an unusual or busted machine. :-)

**Comment by webflo** [comment]
We could switch to `mktemp -d`

**Comment by webflo** [comment]
Please review #78. I added the call to `mktemp -d` there.

**Comment by zxaos** [comment]
Resolves the issue on that machine, thanks!
