### ISSUE TITLE
Update the Composer template to support creating Drupal 10 sites

### ISSUE THREAD

**Issue by xmacinfo** [drupal-composer/drupal-composer-project#620]
I wonder what needs to be done to support Drupal 10.

I like this template over `drupal/recommended project` because it installs Drush and other tools.

Or, once we use this template to install Drupal 9, provide the instructions to upgrade to Drupal 10.

**Comment by webflo** [comment]
The work has already been done in https://github.com/drupal-composer/drupal-project/pull/616. I changed the repo to use 10.x as the default branch.

**Comment by xmacinfo** [comment]
To upgrade to Drupal 10, using this template, I needed to do:

1. Install Drupal 9 with this template (it currently installs Drupal 9.5 including `drupal/core-dev`).
2. Run `composer remove drupal/core-dev`, as this prevents updating to Drupal 10.
3. Finally, to get back the dev components, but this time for Drupal 10, run `composer r drupal/core-dev:^10.0.0 -W --dev`.

And then open the site in a browser to do the configuration (provided you created the database and configured your web server).

That’s it. We get all the benefits of this `drupal-composer/drupal-project` template in a Drupal 10 installation.

**Comment by xmacinfo** [comment]
Awesome. The default branch for this project has been changed to `10.x` while I performed my installation through D9. 😄
