### ISSUE TITLE
installing different core branches - match to drupal-project branch?

### ISSUE THREAD

**Issue by bradbulger** [drupal-composer/drupal-composer-project#625]
This is somewhat related to [#173] but a more general question. Do the branches of drupal-project relate to the branches of core Drupal? 9.x for 9.x, 10.x for 10.x, etc. Or should we get the most recent drupal-project code, and then edit the composer files to reinstall the core Drupal branch we need? (I say that with only a vague understanding of what that means...)

I tried create-project with drupal-project:9.x and it ran fine, giving me core Drupal 9.5.9. I'm checking if that is the right way to do it.

**Comment by AlexSkrypnyk** [comment]
> Do the branches of drupal-project relate to the branches of core Drupal? 

yes

> Or should we get the most recent drupal-project code, and then edit the composer files to reinstall the core Drupal branch we need? 

No, you should use the relevant branch.

Please note that the HEAD of every branch, which refers currently supported Drupal branch (`10.x`, `11.x`), works with the currently supported Drupal version. If there is a breaking change in the currently supported Drupal version releases - this project will make an appropriate change to continue to support the currently supported Drupal version. What this means is that this project does not have a minor-patch release parity with Drupal core.

There is a discussion about releases of this project in https://github.com/drupal-composer/drupal-project/issues/425

Let's continue there.
