### ISSUE TITLE
Deprecation Notice: drupal_rewrite_settings() is deprecated in drupal:10.1.0 in ScriptHandler.php

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupal-composer/drupal-composer-project#626]
Drupal `10.1.x` added `SettingsEditor` class and a deprecation notice for `drupal_rewrite_settings()`.

```
Deprecation Notice: drupal_rewrite_settings() is deprecated in drupal:10.1.0 and is removed from drupal:11.0.0. Use SettingsEditor::rewrite() instead. The order of the arguments has also changed: $settings_file is now required and is the first argument of the method. See https://www.drupal.org/node/3244583 in /app/web/core/includes/install.inc:265
Created a sites/default/settings.php file with chmod 0666
```

We need to update the `ScriptHandler.php` to use `SettingsEditor::rewrite()` instead.

Should we still support `drupal_rewrite_settings()` for sites using core `<10.1.x`?

**Comment by AlexSkrypnyk** [comment]
We can still support `drupal_rewrite_settings()`  for sites using core `<10.1.x` like so

<img width="835" alt="Cursor_and_Updated_ScriptHandler__by_AlexSkrypnyk_·_Pull_Request__942_·_drevops_drevops" src="https://github.com/drupal-composer/drupal-project/assets/378794/f6a1e9cb-c269-46e1-aa2e-adc8ff6c18b7">

Happy to provide a PR

**Comment by AlexSkrypnyk** [comment]
bump

**Comment by AlexSkrypnyk** [comment]
@leymannx 
is this something that the project would be interested to have updated? I'm happy to provide a PR

**Comment by normanlolx** [comment]
@AlexSkrypnyk - Oh yes, that would be great. And if we bump everything properly we don't even need the class check.

**Comment by normanlolx** [comment]
Ah yeah, we bumped already to 10.2, so no class check needed.

**Comment by AlexSkrypnyk** [comment]
@leymannx 
done. 
https://github.com/drupal-composer/drupal-project/pull/634
please review. thank you
