### ISSUE TITLE
Offering help with repository maintenance

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupal-composer/drupal-composer-project#627]
Hi all,

I'd like to help with maintaining this repo. 

As of 8 October 2023, there are 33 issues and 33 PRs open, some of which go 5 years back.

This project is used by many, so I think it is important to keep things flowing.

I'm happy to do any time of maintenance: from triaging to CI setup and actual coding.

Hoping to hear from one of the maintainers.

Thanks

**Comment by normanlolx** [comment]
@webflo – I think we should add Alex as a maintainer for the template. He's using the template a lot in automated tests and by that is always a bit ahead when it comes to update to the latest requirements and is always providing high quality MRs.

**Comment by webflo** [comment]
I haven't done much recently anyway. Thanks AlexSkrypnyk for your contribution. I have added you as a maintainer.

**Comment by webflo** [comment]
BTW, we should bump the CI to PHP 8.3

**Comment by AlexSkrypnyk** [comment]
@webflo 
Thanks. I'm happy to work on all of the "uplift" stuff around CI and testing.

If interested, see how I do CI https://github.com/AlexSkrypnyk/scaffold/tree/main/.github/workflows

Also, confirming that, while I have direct commit access, I acknowledge and confirm that I will be adding changes through PRs and will be seeking the approval for those changes from other maintainers.

Thanks again for adding me
