### ISSUE TITLE
update-scaffold produces incorrect results if drush is not installed

### ISSUE THREAD

**Issue by zxaos** [drupal-composer/drupal-composer-project#63]
If drush is not installed, the update-scaffold script runs without error, but the output is wrong (just deleting the old scaffold).

**Comment by webflo** [comment]
Please review #78

**Comment by jcnventura** [comment]
I'd say that solves it.

**Comment by yched** [comment]
#78 was merged, means this can be closed ?

**Comment by webflo** [comment]
Yes, thanks!
