### ISSUE TITLE
[META] Issues and PRs cleanup

### ISSUE THREAD

**Issue by AlexSkrypnyk** [drupal-composer/drupal-composer-project#644]
This issue is for _this_ repo maintainers.

Looking at the number and age of some issues and PRs, I suggest to close anything older than Dec 31 2021. When closing, the comment will be provided with a reason.

I'm happy to go through issues and PRs.

Looking for comments from at least 3 maintainers.

**Comment by weitzman** [comment]
I have long ago moved to drupal-recommended. I suggest asking @webflo for co-maintainership if you want to keep this project going.

**Comment by weitzman** [comment]
I just removed myself from maintainship of this project.

**Comment by normanlolx** [comment]
Yeah I think a lot of issues can be closed due to inactivity. Would help a lot to keep the overview when orphaned issues and PRs get closed. Go for it 💪🏻

**Comment by AlexSkrypnyk** [comment]
I'm going to review every issue and close it if there was no update in the last year with the message:

```
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
```

As the message states, the author of the issue/PR can always reopen it.

**Comment by normanlolx** [comment]
Thanks a lot! Feels much more managable now.
