### ISSUE TITLE
post-install script fails to run on Windows

### ISSUE THREAD

**Issue by bramcordie** [drupal-composer/drupal-composer-project#65]
The composer post install command fails on Windows with the following error message:

```
'scripts' is not recognized as an internal or external command,
operable program or batch file.
Script scripts/composer/post-install.sh handling the post-install-cmd event returned with an error

  [RuntimeException]
  Error Output: 'scripts' is not recognized as an internal or external command,
  operable program or batch file.
```

I did a quick Github search: `filename:composer.json q:post-install-cmd*.sh` and noticed most projects run shell scripts with bash.

When I update the _scripts_ property in _composer.json_ the problem is resolved:

```
"scripts": {
  "post-install-cmd": "bash ./scripts/composer/post-install.sh"
}
```

**Comment by bramcordie** [comment]
@webflo Do you have any remarks on this approach? Else I'll go ahead and set up a pull request.

**Comment by webflo** [comment]
Does it work with <code>sh ./scripts/composer/post-install.sh</code> as well?

**Comment by bramcordie** [comment]
`sh` or  `bash` works either way when I'm using the git bash shell.
If you want to use Powershell you will have to make `sh.exe` available on `PATH`, see: http://stackoverflow.com/questions/1098786/run-bash-script-from-windows-powershell.

**Comment by webflo** [comment]
Please submit a PR as is or convert the shell script to PHP for better compatibility.

**Comment by bramcordie** [comment]
I'm going to leave the shell scripts since their PHP equivalent just wrap the UNIX commands. eg: http://php.net/manual/en/function.chmod.php. Expect a PR this weekend.

I think it's safe to assume that all the Windows users that use a composer-based workflow also have Git and the accompanying UNIX tools installed via https://git-for-windows.github.io/. This way they have access to all the commands in the post-install script. We probably want to mention this in the README.

The script that pulls in the latest release Drupal release via Drush uses rsync which is not included with the UNIX tools included with Git. I run this one in my linux virtual machine, again something worth mentioning in the docs.
