### ISSUE TITLE
Add composer normalize to CI

### ISSUE THREAD

**Issue by normanlolx** [drupal-composer/drupal-composer-project#653]
As a follow-up on #647 let's add `composer normalize --dry-run` to the CI to let it fail when the composer.json is not normalized.

https://github.com/ergebnis/composer-normalize?tab=readme-ov-file#continuous-integration

**Comment by AlexSkrypnyk** [comment]
I suggest we wait for this one to land first
https://github.com/drupal-composer/drupal-project/pull/654
