### ISSUE TITLE
Workflow to update Drupal Core

### ISSUE THREAD

**Issue by morenstrat** [drupal-composer/drupal-composer-project#67]
Based on the information in README.md, I tried updating from drupal-8.0.0-rc2 to drupal-8.0.0-rc3 by running composer update drupal/core and then scripts/drupal/update-scaffold. Now my settings.php and public files folder are gone. What is the correct workflow to update Drupal Core and not lose these files?

**Comment by webflo** [comment]
I merged https://github.com/drupal-composer/drupal-project/pull/59 a few minutes ago. It should simplify the update process.

**Comment by bradjones1** [comment]
I think this is OK to close?

**Comment by webflo** [comment]
Yes, thanks for the reminder.
