### ISSUE TITLE
Hardcoded config dir breaks "drush updb"

### ISSUE THREAD

**Issue by sascha-krug** [drupal-composer/drupal-composer-project#675]
After merged PR https://github.com/drupal-composer/drupal-project/pull/673  with hard coded config dir "../config/sync" our drupal install/update process breaks, because our config dir, drupal root and composer root are on the same level, meaning it should be configured as "config/sync".

For the meantime I will manually override the dir in our project.

**Comment by webflo** [comment]
@sascha-krug  Could you try https://github.com/webflo/drupal-finder/pull/73 it should fix drupal-finder in composer script.

**Comment by AlexSkrypnyk** [comment]
#677 has resolved this. Please feel free to re-open if the issue still exists.
