### ISSUE TITLE
How to handle module library dependencies

### ISSUE THREAD

**Issue by jasonruyle** [drupal-composer/drupal-composer-project#68]
I'm enjoying the workflow for building out a new D8 site, but I'm looking at installing a module that has 3rd party requirements and am wondering what is the best practice for something like this?

**Comment by webflo** [comment]
What do you mean by library? JS/CSS/Frontend Stuff or PHP libraries?

**Comment by webflo** [comment]
I am aware of two solutions for PHP libs.
1. Manage these 3rd party requirements on the project level (your root composer.json)
2. Use the [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) to merge your  module dependencies.

**Comment by jasonruyle** [comment]
Thanks for the link.  Just read a post with several different options and has some useful details.
https://bojanz.wordpress.com/2015/09/18/d8-composer-definitive-intro/

**Comment by rodrigoaguilera** [comment]
I found no way of downloading JS libraries like colorbox.. I ended up with an old style makefile. Can we reopen this at least for documenting?

**Comment by kasperg** [comment]
From https://www.drupal.org/node/2471553 which is linked in the README:

> To download a project which is not on Drupal.org or a Composer package then [define it as a custom package repository and add it as a dependency](https://getcomposer.org/doc/05-repositories.md#package-2).
> This method supports version control checkouts from custom branches or tags as well as file downloads.

Here you might do something like this:

``` json
{
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "jackmoore/colorbox",
                "version": "1.6.3",
                "dist": {
                    "url": "https://github.com/jackmoore/colorbox/archive/1.6.3.zip",
                    "type": "zip"
                },
                "source": {
                    "url": "https://github.com/jackmoore/colorbox",
                    "type": "git",
                },
            }
        }
    ],
    "require": {
        "jackmoore/colorbox": "1.6.*"
    }
}
```

**Comment by rodrigoaguilera** [comment]
Then I think we should add 
            "web/libraries/{$name}": ["type:drupal-library"],
To the installer paths and 
web/libraries to the .gitignore so they can be declared like in
https://www.drupal.org/node/2471553

IS is reasonable to open another issue for that or this one can be reopened?

**Comment by weitzman** [comment]
FWIW, I found a way to move any library to any path. See [this example](https://gist.github.com/weitzman/31c7a0f0a98ee568078348bcd4d52e49) which depends on the oomphinc/composer-installers-extender package for its magic.

**Comment by ghost** [comment]
@weitzman 

When I use it, I _do_ get the targeted JS libs (for me, atm, those required by '/github/drupalprojects/devel', specifically 'mbostock/d3' & 'components/highlightjs') but not just installed in /libraries

```
cat composer.json

    "extra": {
        "installer-types": ["library"],
        "installer-paths": {
            ...
            ],
                "libraries/{$name}": [
                     "mbostock/d3",
                     "components/highlightjs"
            ]
        }

cd <project>
find . -type d | egrep "/d3$|/highlightjs$"
    (empty)

composer -v require \
 mbostock/d3 \
 components/highlightjs

find . -type d | egrep "/d3$|/highlightjs$"
    ./libraries/d3
    ./vendor/components/highlightjs
```

IIUC, /vendor path is supposed to be for 'core' libraries?

and, unfortunately, even after this install, 'status' page reports

```
D3.js library     Not found
Webprofiler module requires D3.js library to properly render data. Download D3.js into /libraries/d3/d3.min.js.

highlight.js library     Not found
Webprofiler module requires highlight.js library to syntax highlight collected queries. Download highlight.js assets into /libraries/highlight.
```

Where should BOTH these libraries end up, how do I get them both in the same path/place, and how do I get them recognized by Drupal?

@jasonruyle You referenced @bojanz 's post b4 closing.  What did you end up doing that works?

**Comment by webflo** [comment]
components/highlightjs is type: component. Add "component" to installer-types, like this:

```
"installer-types": ["library", "component"]
```

**Comment by ghost** [comment]
Okay, that works for location

```
find . -type d | egrep "/d3$|/highlightjs$"
    ./libraries/highlightjs
    ./libraries/d3
```

But, I still get the 'not found' errors in reports/status.

I thought we're supposed to be using composer these days to  manage packages, libraries, etc & their dependencies in Drupal8 installs.

Any idea why
- this is NOT handled in the /devel module?  It's that module's dependencies ...
- 'status' doesn't see/accept the libs

?

**Comment by weitzman** [comment]
I dont think highlightjs and d3 were available via Packagist when we last discussed this. Now they are. So I agree that these should be added to the devel (or devel/webprofiler) composer.json. I'm not sure that helps with getting the projects out of /vendor and into /libraries.

As for the requirements check still failing, see code in webprofiler_requirements(). Maybe its buggy or maybe you can see where it wants the libraries to end up. We could potentially make this check better/flexible. I am a devel maintainer.

**Comment by ghost** [comment]
>  agree that these should be added to the devel (or devel/webprofiler) composer.json

ok

> not sure that helps with getting the projects out of /vendor and into /libraries

probably doesn't matter for the webprofiler's usage right?  unless any other module does/might use them.  then I'd argue they should be in a drupal-standard location.  which sounds like, <project>/libraries/${name} ?

> We could potentially make this check better/flexible. 

in

```
./web/modules/contrib/devel/webprofiler/webprofiler.install
```

this is the relvant code

```
    ...
    function webprofiler_requirements($phase) {
      $requirements = [];
    ...
!!!        $has_d3 = _webprofiler_verify_library('webprofiler', 'd3');
    ...
!!!        $has_highlight = _webprofiler_verify_library('webprofiler', 'highlight');
    ...
      return $requirements;
    }
    ...
    function _webprofiler_verify_library($extension, $name) {
      /** @var Drupal\Core\Asset\LibraryDiscovery $library_discovery */
      $library_discovery = \Drupal::service('library.discovery');
      $library = $library_discovery->getLibraryByName($extension, $name);
    ...
```

which clearly uses

```
https://api.drupal.org/api/drupal/core%21core.services.yml/service/library.discovery/8.1.x
```

I'm not clear what paths it searches, and whether it makes sens to extend the class, or add a different search mechanism.

> I am a devel maintainer.

Where on github/stackexchange should this discussion be moved?  Seems its more focused on /devel itself, but has some connection to this scaffold ... if only to make sure the dirs used as its default &/or any arbitray/extended paths are found/used by the Drupal modules that need them.

**Comment by weitzman** [comment]
The best spot to discuss is https://www.drupal.org/project/issues/devel. Pls create new issue and use component=webprofiler. Some prior discussion is at https://www.drupal.org/node/2502489 and newer https://www.drupal.org/node/2349471

**Comment by ghost** [comment]
@weitzman not an option there anymore.  I'll have to leave it with you.

**Comment by weitzman** [comment]
I read a bit but can't quite follow what devel's composer.json should do to make its library install easier. ping @robloach for guidance.

**Comment by RobLoach** [comment]
@user58258 

> I still get the 'not found' errors in reports/status.
> this is NOT handled in the /devel module? It's that module's dependencies ... 'status' doesn't see/accept the libs

As Moshe mentioned, we should update this in the [Devel](https://www.drupal.org/project/devel) space to discover the install location. _alpha1_ just recently came out, so it's not quite ready for production, so expect issues until that comes. Thank you for trying it out.

This just needs to tweak the settings so that it's brought into the correct location. I've created an issue for you over at https://www.drupal.org/node/2768925 . Feel free to continue discussion over there.
