### ISSUE TITLE
Neat project!

### ISSUE THREAD

**Issue by RobLoach** [drupal-composer/drupal-composer-project#8]
Where are you going to go with it? What's needed to push it forwards? There's also http://hubdrop.org/ which will mirror Drupal modules/themes on GitHub. Might be a bit handy as Packagist has pretty solid GitHub integration.

**Comment by kasperg** [comment]
> Where are you going to go with it?

The point is to enable a Composer-based workflow to manage dependencies in Drupal projects. 

This could have a number of different outcomes such as:
1. Providing the official Composer repository for projects on drupal.org
2. Eliminating the need for `drush dl`, `drush upc` etc.
3. Eliminating the need for Drush Make. 

> What's needed to push it forwards?

As I see it at this point we generally need to get more developers to try it out.

The core of the development work is actually going on in [drupal-composer/drupal-parse-composer](https://github.com/drupal-composer/drupal-parse-composer) which provides the Composer packages. There are probably lots of edge cases that still need to be found and worked out.

> There's also http://hubdrop.org/ which will mirror Drupal modules/themes on GitHub. Might be a bit handy as Packagist has pretty solid GitHub integration.

The crucial point here is providing [Composer package definitions](https://getcomposer.org/doc/04-schema.md) for all Drupal projects through a Composer repository. Having them on GitHub does not really make much of a difference in my opinion.

**Comment by derhasi** [comment]
With [Drupal Packagist](https://github.com/drupal-composer/drupal-packagist) we try to provide up to date packagist information for all projects on drupal.org. Therefore releases are parsed and even the commitlog, so we realy have up to date package information. The source for the code are the git repos and tar-files from drupal.org, so we do not mirror code anywhere.

The next steps for this template would be to
- Update documentation to the new features
- Implement a 8.x branch based on https://github.com/tstoeckler/drupal-site-template [see discussion](https://groups.drupal.org/node/455693)
- Maybe show some examples of implementing contrib modules and themes, and maybe even assets

**Comment by derhasi** [comment]
> > There's also http://hubdrop.org/ which will mirror Drupal modules/themes on GitHub. Might be a bit handy as Packagist has pretty solid GitHub integration.
> 
> The crucial point here is providing Composer package definitions for all Drupal projects through a Composer repository. Having them on GitHub does not really make much of a difference in my opinion.

My perspective is, that currently still drupal.org is the reliable source for the projects. I think hubdrop is a good solution for the actual development where maintainers want to use the tools and workflow from github. But at the end the code will be hosted on drupal.org anyways.

**Comment by cpliakas** [comment]
Nothing to contribute other than a +1 to "great initiative". Look forward to following the progress.

**Comment by andreasbergqvist** [comment]
I agree on "great initiative".

Have you been in the talks of Drupal developers of making this the "standard way"?

Do you have any data on how many sites are using this setup?
Would you recommend on using it on production sites?

**Comment by webflo** [comment]
@andreasbergqvist Thanks :)

I don´t know how many site are using this setup, but Drupal Packagist has some statistics about installed packages and its growing fast IMO. https://packagist.drupal-composer.org/statistics

I use the template and Drupal Packagist in two different projects. It try to keep it as stable as possible.
