### ISSUE TITLE
Timeout causes preserve-paths to be lost

### ISSUE THREAD

**Issue by zikphil** [drupal-composer/drupal-composer-project#80]
Hello,

I've noticed that since you provided the new composer.json to use with Drupal 7 you are using composer-preserve-paths. The problem while using this new method is that if for example git.drupal.org times out while trying to pull the latest version, your web/ folder will be empty and all your custom codes won't be restored even if the files are in your preserve-paths. This seems a bit risky to lose uncommitted code while running a composer install to make sure that something is working or is updated...

Is there something i am not understanding properly?

**Comment by thomscode** [comment]
If this is composer timing out, you can either increase or disable the default 5 minute composer timeout:
```
composer config process-timeout 0
```
https://getcomposer.org/doc/06-config.md#process-timeout.

**Comment by jcnventura** [comment]
This is probably a bug against composer-preserve-paths, not against drupal-project.
