### ISSUE TITLE
composer.json and Drupal root issue

### ISSUE THREAD

**Issue by tobiberlin** [drupal-composer/drupal-composer-project#81]
Hey,

I run into this issue when I installed the Composer Manager module (https://www.drupal.org/project/composer_manager) After installing this module I keep getting the following errors:

`RuntimeException: \web\composer.json is not readable.`

This is caused by the fact that the Drupal root is set to be the web folder - but the project root folder where the composer.json is saved is the folder above "web". All the trouble appears in composer_manager.module here:

`function composer_manager_initialized($root = NULL) {
  $root = $root ?: \Drupal::root();
  $package = \Drupal\composer_manager\JsonFile::read($root . '/composer.json');

  return isset($package['scripts']['drupal-rebuild']);
}`

Where `Drupal::root()`gives back "web". I feel that it still not really clear where to save the composer.json? Or maybe this project here is already outdated? (see https://bojanz.wordpress.com/2015/09/18/d8-composer-definitive-intro/)... or is this blog article outdated?

Best,
Tobias

**Comment by webflo** [comment]
Hi, 

looks like composer_manager and the project template are incompatible. But i can´t think of any real reason to use composer_manager with it. Can you explain your use-case? Thanks!

// cc @bojanz

**Comment by tobiberlin** [comment]
Hi... I am just doing my first steps with Drupal 8 and composer and 
found this problem. In my eyes it is not a good idea to change the place 
of the composer.json here when in Drupal standard installation the file 
is placed within Drupal root and modules may rely on it?!

**Comment by bojanz** [comment]
There's no point in using composer_manager if Composer is already used to manage the whole site.
Composer Manager is redundant here.

**Comment by webflo** [comment]
If you still need the functionally from Composer Manager you could the [merge plugin](https://github.com/wikimedia/composer-merge-plugin) directly.

**Comment by tobiberlin** [comment]
Ok, got it... but why is the folder structure changed in this project 
here compared to the Drupal I can download from drupal.org?

**Comment by webflo** [comment]
The folder layout is considered as a best practice, because its the most secure to make some file not web accessible. Docs, tests, composers vendor folder etc.

**Comment by tobiberlin** [comment]
Thx for your explanations
