### ISSUE TITLE
AmazonS3

### ISSUE THREAD

**Issue by albertvolkman** [drupal-composer/drupal-composer-project#83]
http://pastebin.com/kSuidsse

@webflo This may be an issue with [composer-merge-plugin](https://github.com/wikimedia/composer-merge-plugin) instead (or even more likely user error on my part). However, when I add the above patch to my code, it works when I the amazons3 module already exists, but when doing a fresh build from Composer, it fails as it can't find the yet-to-be-download amazons3 composer.json. Am I going about this the wrong way, or perhaps missing something?

**Comment by webflo** [comment]
You should not require <code> drupal/amazons3</code> and include the amazons3s composer.json at the same time. You have to choose one of the methods.

**Comment by albertvolkman** [comment]
When I remove the require, it does not install.

**Comment by albertvolkman** [comment]
This fails as well-

http://pastebin.com/jydUt5Va

**Comment by webflo** [comment]
Hmm you added only one of the two custom repositories. I think you need both. http://cgit.drupalcode.org/amazons3/tree/composer.json#n35

**Comment by albertvolkman** [comment]
I've tried adding both, and it still fails :(

**Comment by webflo** [comment]
https://gist.github.com/webflo/cdf901dc3833af489f97 works with out problems on my machine.

**Comment by albertvolkman** [comment]
So the difference is-

```
"drupal/amazons3": "7.*"
```

vs

```
"drupal/amazons3": "7.2.*"
```

The 7.1 branch does not have a composer file, but the 7.2 branch does. Which does not solve the issue of this module having it's own depdendencies.

**Comment by albertvolkman** [comment]
Nevermind, that was due to some remaining issues in my composer file. It appears to be working now, my apologies for the non-issue.
