### ISSUE TITLE
Do not assume that autoloader and vendor/ dir are present

### ISSUE THREAD

**Issue by franz-josef-kaiser** [drupal-composer/drupal-composer-project#88]
The [`autoload.php`](https://github.com/drupal-composer/drupal-project/blob/31260864df98758a193add15a6a3339d67f80306/web/autoload.php#L19) file assumes that the autoloader is
- added
- and installed into `../vendor`

Composer [allows changing this](https://getcomposer.org/doc/06-config.md#vendor-dir) by setting the `vendor-dir` argument, something that [the Drupal core `composer.json`](https://github.com/drupal/drupal/blob/5fd356756d6d8190fe1c9c2550b87b7ea49484ba/composer.json#L21-L22) notes as well. As a minimum there should be a check for `file_exists()` wrapping that statement and some human readable error message.

**Comment by derhasi** [comment]
The provided autoload.php is meant to be used with the composer.json of this project. When using `composer create-project ...` the autoloader will be in place.

We cannot foresee any possible change someone will make in an individual project. Therefore there should be only one default configuration.

A check with `file_exists()` does not make any sense, as the script should fail if no autoloader is present.

**Comment by greg-1-anderson** [comment]
Agree. If the end-user wants to customize the vendor location, then autoload.php must be customized as well.

**Comment by franz-josef-kaiser** [comment]
@greg-1-anderson @derhasi When you install and setup another project that includes this project here, then the autoloader will not be there, but somewhere upwards in the FS hierarchy. In that scenario it would fail as well. 
Anyway, if everybody disagrees here, then please close the issue. Thanks.

**Comment by greg-1-anderson** [comment]
@franz-josef-kaiser This project was designed to be an example of a top-level project, not something that is required as a dependency of some other projects. The `scripts` and `installer-paths` in the composer.json here are ignored if they are not in the top-level composer.json file, so I am not sure that the use-case for drupal-project being a dependency is supportable.

**Comment by franz-josef-kaiser** [comment]
No problem. Thanks for your explanations anyway!
