### ISSUE TITLE
Remove Drupal Console

### ISSUE THREAD

**Issue by bojanz** [drupal-composer/drupal-composer-project#89]
Drupal Console has instructions for global install. I think there's no reason to treat it otherwise.

The main problem with the current approach is that it gets put into vendor/bin/console, while all output actually suggests typing only "drupal" (assuming a global install under the "drupal" name).
This creates confusion in docs, at sprints, etc.

**Comment by jmolivas** [comment]
When can probably rename the Drupal Console configuration on the `composer.json file`
from:

```
"bin": ["bin/console"]
```

to:

```
"bin": ["bin/drupal"]
```

**Comment by bojanz** [comment]
@jmolivas That's a good initial step, but the bigger question is whether you as a maintainer of Drupal Console prefer people to have a global installation, or want to promote per-site installs as a best practise?

**Comment by yched** [comment]
I thought the goal with "local drush" was to have one single /vendor with all dependencies resolved in the same dependency pool across web drupal + drush + console + ...

i.e if the code runs together (drush runs code from drupal, Drupal console runs code from drupal), then it should be all a single pool of deps in a single /vendor ?

Doesn't the same reasoning apply to Drupal console ?

**Comment by derhasi** [comment]
@yched, I think so too.

The project/site dependencies should be managed in the project itself and should not rely on anyone's global installation. This way you make sure the team is working with the intended version. Build and maintenance scripts can rely on the dependencies too and do not have to care about absolute paths.

For making the `./vendor/bin/...` calls easier to perform there are some approaches like https://github.com/drupal-composer/drupal-project/pull/66 or https://github.com/derhasi/buddy

**Comment by greg-1-anderson** [comment]
Yes, Drupal Console is vulnerable to dependency hell, and should only be used in a project-local context.

If you use a global install of Drupal Console, then all of your local and remote instances of Drupal should be at the same version. This typically is not practical. Note that Drush has the 'drush finder' to make it easier to use a site-local Drush as if it were installed globally.  Drupal Console could utilize a similar technique.

**Comment by bojanz** [comment]
Okay, I stand corrected. Thanks, everyone.
