### ISSUE TITLE
Permission denied 

### ISSUE THREAD

**Issue by aaronbauman** [drupal-composer/drupal-composer-project#90]
"composer create-project" command dies with error:

```
[ErrorException]                          
  touch(): Utime failed: Permission denied  
```

Is sudo required?

**Comment by webflo** [comment]
It should work without sudo. Can you paste the full commands? Thanks!

**Comment by aaronbauman** [comment]
Full command was

```
composer create-project drupal-composer/drupal-project:8.x-dev --stability dev
```

run in an empty, newly-created directory i created just for this purpose
composer v 1.0.0-alpha10, as installed by homebrew

**Comment by webflo** [comment]
We change the project template recently, could you try it again? Thanks!

**Comment by webflo** [comment]
I’m closing this issue because it has been inactive for a few weeks.  Please reopen if you still encounter this issue with the latest version.

Thanks!
