### ISSUE TITLE
Generate hash_salt while install

### ISSUE THREAD

**Issue by zviryatko** [drupal-composer/drupal-composer-project#92]
If you have an active project based on this repo and someone has cloned it and running locally he gets php throwable error, because Drupal is required a hash salt.
So is it secure to generate hash_salt in post-install script via this command?
`echo "\$settings['hash_salt'] = '$(php -r 'print bin2hex(openssl_random_pseudo_bytes(32, $cstrong = TRUE));')';" >> web/sites/default/settings.php`

**Comment by greg-1-anderson** [comment]
`openssl_random_pseudo_bytes` is available in php 5.3 and later, so seems good to me.

Maybe we should first check to see if settings.php already defines 'hash_salt'?

**Comment by zviryatko** [comment]
We can put it into this check: `if [ ! -f web/sites/default/settings.php ]`.

**Comment by FatherShawn** [comment]
The code that preps and copies `settings.php` in `scripts/composer/ScriptHandler.php` is in a conditional check for settings.php already existing.  So why does running `composer require` wipe my salt value?

**Comment by AlexSkrypnyk** [comment]
This pull request/issue has been inactive for over a year and is being closed due to inactivity. If the issue still persists or the contribution is still relevant, please feel free to reopen it or create a new one.

Thank you for your understanding and your contributions to the project!
